// Code generated by mash-featgen. DO NOT EDIT.

package features

import "github.com/mash-protocol/mash-go/pkg/model"

// Measurement attribute IDs.
const (
	MeasurementAttrACActivePower             uint16 = 1
	MeasurementAttrACReactivePower           uint16 = 2
	MeasurementAttrACApparentPower           uint16 = 3
	MeasurementAttrACActivePowerPerPhase     uint16 = 10
	MeasurementAttrACReactivePowerPerPhase   uint16 = 11
	MeasurementAttrACApparentPowerPerPhase   uint16 = 12
	MeasurementAttrACCurrentPerPhase         uint16 = 20
	MeasurementAttrACVoltagePerPhase         uint16 = 21
	MeasurementAttrACVoltagePhaseToPhasePair uint16 = 22
	MeasurementAttrACFrequency               uint16 = 23
	MeasurementAttrPowerFactor               uint16 = 24
	MeasurementAttrACEnergyConsumed          uint16 = 30
	MeasurementAttrACEnergyProduced          uint16 = 31
	MeasurementAttrDCPower                   uint16 = 40
	MeasurementAttrDCCurrent                 uint16 = 41
	MeasurementAttrDCVoltage                 uint16 = 42
	MeasurementAttrDCEnergyIn                uint16 = 43
	MeasurementAttrDCEnergyOut               uint16 = 44
	MeasurementAttrStateOfCharge             uint16 = 50
	MeasurementAttrStateOfHealth             uint16 = 51
	MeasurementAttrStateOfEnergy             uint16 = 52
	MeasurementAttrUseableCapacity           uint16 = 53
	MeasurementAttrCycleCount                uint16 = 54
	MeasurementAttrTemperature               uint16 = 60
)

// MeasurementFeatureRevision is the current revision of the Measurement feature.
const MeasurementFeatureRevision uint16 = 1

// Measurement wraps a Feature with Measurement-specific functionality.
// Real-time telemetry: power, energy, voltage, current readings.
type Measurement struct {
	*model.Feature
}

// NewMeasurement creates a new Measurement feature.
func NewMeasurement() *Measurement {
	f := model.NewFeature(model.FeatureMeasurement, MeasurementFeatureRevision)

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrACActivePower,
		Name:        "acActivePower",
		Type:        model.DataTypeInt64,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Unit:        "mW",
		Description: "Active/real power",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrACReactivePower,
		Name:        "acReactivePower",
		Type:        model.DataTypeInt64,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Unit:        "mVAR",
		Description: "Reactive power",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrACApparentPower,
		Name:        "acApparentPower",
		Type:        model.DataTypeUint64,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Unit:        "mVA",
		Description: "Apparent power (always positive)",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrACActivePowerPerPhase,
		Name:        "acActivePowerPerPhase",
		Type:        model.DataTypeMap,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Description: "Active power per phase (Phase -> mW)",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrACReactivePowerPerPhase,
		Name:        "acReactivePowerPerPhase",
		Type:        model.DataTypeMap,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Description: "Reactive power per phase (Phase -> mVAR)",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrACApparentPowerPerPhase,
		Name:        "acApparentPowerPerPhase",
		Type:        model.DataTypeMap,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Description: "Apparent power per phase (Phase -> mVA)",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrACCurrentPerPhase,
		Name:        "acCurrentPerPhase",
		Type:        model.DataTypeMap,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Description: "Current per phase (Phase -> mA, signed)",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrACVoltagePerPhase,
		Name:        "acVoltagePerPhase",
		Type:        model.DataTypeMap,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Description: "Phase-to-neutral voltage (Phase -> mV)",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrACVoltagePhaseToPhasePair,
		Name:        "acVoltagePhaseToPhasePair",
		Type:        model.DataTypeMap,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Description: "Phase-to-phase voltage (PhasePair -> mV)",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrACFrequency,
		Name:        "acFrequency",
		Type:        model.DataTypeUint32,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Unit:        "mHz",
		Description: "Grid frequency (e.g., 50000 = 50.000 Hz)",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrPowerFactor,
		Name:        "powerFactor",
		Type:        model.DataTypeInt16,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		MinValue:    int16(-1000),
		MaxValue:    int16(1000),
		Description: "Power factor (0.001 units, -1.0 to +1.0)",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrACEnergyConsumed,
		Name:        "acEnergyConsumed",
		Type:        model.DataTypeUint64,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Unit:        "mWh",
		Description: "Total energy consumed from grid",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrACEnergyProduced,
		Name:        "acEnergyProduced",
		Type:        model.DataTypeUint64,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Unit:        "mWh",
		Description: "Total energy produced/fed-in to grid",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrDCPower,
		Name:        "dcPower",
		Type:        model.DataTypeInt64,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Unit:        "mW",
		Description: "DC power (+ into device, - out)",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrDCCurrent,
		Name:        "dcCurrent",
		Type:        model.DataTypeInt64,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Unit:        "mA",
		Description: "DC current (+ into device, - out)",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrDCVoltage,
		Name:        "dcVoltage",
		Type:        model.DataTypeUint32,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Unit:        "mV",
		Description: "DC voltage",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrDCEnergyIn,
		Name:        "dcEnergyIn",
		Type:        model.DataTypeUint64,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Unit:        "mWh",
		Description: "Energy into this component",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrDCEnergyOut,
		Name:        "dcEnergyOut",
		Type:        model.DataTypeUint64,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Unit:        "mWh",
		Description: "Energy out of this component",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrStateOfCharge,
		Name:        "stateOfCharge",
		Type:        model.DataTypeUint8,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		MinValue:    uint8(0),
		MaxValue:    uint8(100),
		Unit:        "%",
		Description: "State of charge (0-100%)",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrStateOfHealth,
		Name:        "stateOfHealth",
		Type:        model.DataTypeUint8,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		MinValue:    uint8(0),
		MaxValue:    uint8(100),
		Unit:        "%",
		Description: "State of health (0-100%, battery degradation)",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrStateOfEnergy,
		Name:        "stateOfEnergy",
		Type:        model.DataTypeUint64,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Unit:        "mWh",
		Description: "Available energy at current SoC",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrUseableCapacity,
		Name:        "useableCapacity",
		Type:        model.DataTypeUint64,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Unit:        "mWh",
		Description: "Current useable capacity",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrCycleCount,
		Name:        "cycleCount",
		Type:        model.DataTypeUint32,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Description: "Charge/discharge cycles",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          MeasurementAttrTemperature,
		Name:        "temperature",
		Type:        model.DataTypeInt16,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Unit:        "centi-C",
		Description: "Temperature (e.g., 2500 = 25.00C)",
	}))

	return &Measurement{Feature: f}
}

// ACActivePower returns the active/real power.
func (m *Measurement) ACActivePower() (int64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrACActivePower)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(int64); ok {
		return v, true
	}
	return 0, false
}

// ACReactivePower returns the reactive power.
func (m *Measurement) ACReactivePower() (int64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrACReactivePower)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(int64); ok {
		return v, true
	}
	return 0, false
}

// ACApparentPower returns the apparent power (always positive).
func (m *Measurement) ACApparentPower() (uint64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrACApparentPower)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(uint64); ok {
		return v, true
	}
	return 0, false
}

// ACActivePowerPerPhase returns the active power per phase (Phase -> mW).
func (m *Measurement) ACActivePowerPerPhase() (map[Phase]int64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrACActivePowerPerPhase)
	if err != nil || val == nil {
		return nil, false
	}
	if v, ok := val.(map[Phase]int64); ok {
		return v, true
	}
	return nil, false
}

// ACReactivePowerPerPhase returns the reactive power per phase (Phase -> mVAR).
func (m *Measurement) ACReactivePowerPerPhase() (map[Phase]int64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrACReactivePowerPerPhase)
	if err != nil || val == nil {
		return nil, false
	}
	if v, ok := val.(map[Phase]int64); ok {
		return v, true
	}
	return nil, false
}

// ACApparentPowerPerPhase returns the apparent power per phase (Phase -> mVA).
func (m *Measurement) ACApparentPowerPerPhase() (map[Phase]uint64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrACApparentPowerPerPhase)
	if err != nil || val == nil {
		return nil, false
	}
	if v, ok := val.(map[Phase]uint64); ok {
		return v, true
	}
	return nil, false
}

// ACCurrentPerPhase returns the current per phase (Phase -> mA, signed).
func (m *Measurement) ACCurrentPerPhase() (map[Phase]int64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrACCurrentPerPhase)
	if err != nil || val == nil {
		return nil, false
	}
	if v, ok := val.(map[Phase]int64); ok {
		return v, true
	}
	return nil, false
}

// ACVoltagePerPhase returns the phase-to-neutral voltage (Phase -> mV).
func (m *Measurement) ACVoltagePerPhase() (map[Phase]uint32, bool) {
	val, err := m.ReadAttribute(MeasurementAttrACVoltagePerPhase)
	if err != nil || val == nil {
		return nil, false
	}
	if v, ok := val.(map[Phase]uint32); ok {
		return v, true
	}
	return nil, false
}

// ACVoltagePhaseToPhasePair returns the phase-to-phase voltage (PhasePair -> mV).
func (m *Measurement) ACVoltagePhaseToPhasePair() (map[PhasePair]uint32, bool) {
	val, err := m.ReadAttribute(MeasurementAttrACVoltagePhaseToPhasePair)
	if err != nil || val == nil {
		return nil, false
	}
	if v, ok := val.(map[PhasePair]uint32); ok {
		return v, true
	}
	return nil, false
}

// ACFrequency returns the grid frequency (e.g., 50000 = 50.000 Hz).
func (m *Measurement) ACFrequency() (uint32, bool) {
	val, err := m.ReadAttribute(MeasurementAttrACFrequency)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(uint32); ok {
		return v, true
	}
	return 0, false
}

// PowerFactor returns the power factor (0.001 units, -1.0 to +1.0).
func (m *Measurement) PowerFactor() (int16, bool) {
	val, err := m.ReadAttribute(MeasurementAttrPowerFactor)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(int16); ok {
		return v, true
	}
	return 0, false
}

// ACEnergyConsumed returns the total energy consumed from grid.
func (m *Measurement) ACEnergyConsumed() (uint64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrACEnergyConsumed)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(uint64); ok {
		return v, true
	}
	return 0, false
}

// ACEnergyProduced returns the total energy produced/fed-in to grid.
func (m *Measurement) ACEnergyProduced() (uint64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrACEnergyProduced)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(uint64); ok {
		return v, true
	}
	return 0, false
}

// DCPower returns the dC power (+ into device, - out).
func (m *Measurement) DCPower() (int64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrDCPower)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(int64); ok {
		return v, true
	}
	return 0, false
}

// DCCurrent returns the dC current (+ into device, - out).
func (m *Measurement) DCCurrent() (int64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrDCCurrent)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(int64); ok {
		return v, true
	}
	return 0, false
}

// DCVoltage returns the dC voltage.
func (m *Measurement) DCVoltage() (uint32, bool) {
	val, err := m.ReadAttribute(MeasurementAttrDCVoltage)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(uint32); ok {
		return v, true
	}
	return 0, false
}

// DCEnergyIn returns the energy into this component.
func (m *Measurement) DCEnergyIn() (uint64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrDCEnergyIn)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(uint64); ok {
		return v, true
	}
	return 0, false
}

// DCEnergyOut returns the energy out of this component.
func (m *Measurement) DCEnergyOut() (uint64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrDCEnergyOut)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(uint64); ok {
		return v, true
	}
	return 0, false
}

// StateOfCharge returns the state of charge (0-100%).
func (m *Measurement) StateOfCharge() (uint8, bool) {
	val, err := m.ReadAttribute(MeasurementAttrStateOfCharge)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(uint8); ok {
		return v, true
	}
	return 0, false
}

// StateOfHealth returns the state of health (0-100%, battery degradation).
func (m *Measurement) StateOfHealth() (uint8, bool) {
	val, err := m.ReadAttribute(MeasurementAttrStateOfHealth)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(uint8); ok {
		return v, true
	}
	return 0, false
}

// StateOfEnergy returns the available energy at current SoC.
func (m *Measurement) StateOfEnergy() (uint64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrStateOfEnergy)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(uint64); ok {
		return v, true
	}
	return 0, false
}

// UseableCapacity returns the current useable capacity.
func (m *Measurement) UseableCapacity() (uint64, bool) {
	val, err := m.ReadAttribute(MeasurementAttrUseableCapacity)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(uint64); ok {
		return v, true
	}
	return 0, false
}

// CycleCount returns the charge/discharge cycles.
func (m *Measurement) CycleCount() (uint32, bool) {
	val, err := m.ReadAttribute(MeasurementAttrCycleCount)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(uint32); ok {
		return v, true
	}
	return 0, false
}

// Temperature returns the temperature (e.g., 2500 = 25.00C).
func (m *Measurement) Temperature() (int16, bool) {
	val, err := m.ReadAttribute(MeasurementAttrTemperature)
	if err != nil || val == nil {
		return 0, false
	}
	if v, ok := val.(int16); ok {
		return v, true
	}
	return 0, false
}

// SetACActivePower sets the active/real power.
func (m *Measurement) SetACActivePower(acActivePower int64) error {
	attr, err := m.GetAttribute(MeasurementAttrACActivePower)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(acActivePower)
}

// ClearACActivePower clears the active/real power.
func (m *Measurement) ClearACActivePower() error {
	attr, err := m.GetAttribute(MeasurementAttrACActivePower)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetACActivePowerPtr sets or clears the active/real power from a pointer.
func (m *Measurement) SetACActivePowerPtr(v *int64) error {
	if v == nil {
		return m.ClearACActivePower()
	}
	return m.SetACActivePower(*v)
}

// SetACReactivePower sets the reactive power.
func (m *Measurement) SetACReactivePower(acReactivePower int64) error {
	attr, err := m.GetAttribute(MeasurementAttrACReactivePower)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(acReactivePower)
}

// ClearACReactivePower clears the reactive power.
func (m *Measurement) ClearACReactivePower() error {
	attr, err := m.GetAttribute(MeasurementAttrACReactivePower)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetACReactivePowerPtr sets or clears the reactive power from a pointer.
func (m *Measurement) SetACReactivePowerPtr(v *int64) error {
	if v == nil {
		return m.ClearACReactivePower()
	}
	return m.SetACReactivePower(*v)
}

// SetACApparentPower sets the apparent power (always positive).
func (m *Measurement) SetACApparentPower(acApparentPower uint64) error {
	attr, err := m.GetAttribute(MeasurementAttrACApparentPower)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(acApparentPower)
}

// ClearACApparentPower clears the apparent power (always positive).
func (m *Measurement) ClearACApparentPower() error {
	attr, err := m.GetAttribute(MeasurementAttrACApparentPower)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetACApparentPowerPtr sets or clears the apparent power (always positive) from a pointer.
func (m *Measurement) SetACApparentPowerPtr(v *uint64) error {
	if v == nil {
		return m.ClearACApparentPower()
	}
	return m.SetACApparentPower(*v)
}

// SetACActivePowerPerPhase sets the active power per phase (Phase -> mW).
func (m *Measurement) SetACActivePowerPerPhase(acActivePowerPerPhase map[Phase]int64) error {
	attr, err := m.GetAttribute(MeasurementAttrACActivePowerPerPhase)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(acActivePowerPerPhase)
}

// ClearACActivePowerPerPhase clears the active power per phase (Phase -> mW).
func (m *Measurement) ClearACActivePowerPerPhase() error {
	attr, err := m.GetAttribute(MeasurementAttrACActivePowerPerPhase)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetACActivePowerPerPhasePtr sets or clears the active power per phase (Phase -> mW) from a pointer.
func (m *Measurement) SetACActivePowerPerPhasePtr(v *map[Phase]int64) error {
	if v == nil {
		return m.ClearACActivePowerPerPhase()
	}
	return m.SetACActivePowerPerPhase(*v)
}

// SetACReactivePowerPerPhase sets the reactive power per phase (Phase -> mVAR).
func (m *Measurement) SetACReactivePowerPerPhase(acReactivePowerPerPhase map[Phase]int64) error {
	attr, err := m.GetAttribute(MeasurementAttrACReactivePowerPerPhase)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(acReactivePowerPerPhase)
}

// ClearACReactivePowerPerPhase clears the reactive power per phase (Phase -> mVAR).
func (m *Measurement) ClearACReactivePowerPerPhase() error {
	attr, err := m.GetAttribute(MeasurementAttrACReactivePowerPerPhase)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetACReactivePowerPerPhasePtr sets or clears the reactive power per phase (Phase -> mVAR) from a pointer.
func (m *Measurement) SetACReactivePowerPerPhasePtr(v *map[Phase]int64) error {
	if v == nil {
		return m.ClearACReactivePowerPerPhase()
	}
	return m.SetACReactivePowerPerPhase(*v)
}

// SetACApparentPowerPerPhase sets the apparent power per phase (Phase -> mVA).
func (m *Measurement) SetACApparentPowerPerPhase(acApparentPowerPerPhase map[Phase]uint64) error {
	attr, err := m.GetAttribute(MeasurementAttrACApparentPowerPerPhase)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(acApparentPowerPerPhase)
}

// ClearACApparentPowerPerPhase clears the apparent power per phase (Phase -> mVA).
func (m *Measurement) ClearACApparentPowerPerPhase() error {
	attr, err := m.GetAttribute(MeasurementAttrACApparentPowerPerPhase)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetACApparentPowerPerPhasePtr sets or clears the apparent power per phase (Phase -> mVA) from a pointer.
func (m *Measurement) SetACApparentPowerPerPhasePtr(v *map[Phase]uint64) error {
	if v == nil {
		return m.ClearACApparentPowerPerPhase()
	}
	return m.SetACApparentPowerPerPhase(*v)
}

// SetACCurrentPerPhase sets the current per phase (Phase -> mA, signed).
func (m *Measurement) SetACCurrentPerPhase(acCurrentPerPhase map[Phase]int64) error {
	attr, err := m.GetAttribute(MeasurementAttrACCurrentPerPhase)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(acCurrentPerPhase)
}

// ClearACCurrentPerPhase clears the current per phase (Phase -> mA, signed).
func (m *Measurement) ClearACCurrentPerPhase() error {
	attr, err := m.GetAttribute(MeasurementAttrACCurrentPerPhase)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetACCurrentPerPhasePtr sets or clears the current per phase (Phase -> mA, signed) from a pointer.
func (m *Measurement) SetACCurrentPerPhasePtr(v *map[Phase]int64) error {
	if v == nil {
		return m.ClearACCurrentPerPhase()
	}
	return m.SetACCurrentPerPhase(*v)
}

// SetACVoltagePerPhase sets the phase-to-neutral voltage (Phase -> mV).
func (m *Measurement) SetACVoltagePerPhase(acVoltagePerPhase map[Phase]uint32) error {
	attr, err := m.GetAttribute(MeasurementAttrACVoltagePerPhase)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(acVoltagePerPhase)
}

// ClearACVoltagePerPhase clears the phase-to-neutral voltage (Phase -> mV).
func (m *Measurement) ClearACVoltagePerPhase() error {
	attr, err := m.GetAttribute(MeasurementAttrACVoltagePerPhase)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetACVoltagePerPhasePtr sets or clears the phase-to-neutral voltage (Phase -> mV) from a pointer.
func (m *Measurement) SetACVoltagePerPhasePtr(v *map[Phase]uint32) error {
	if v == nil {
		return m.ClearACVoltagePerPhase()
	}
	return m.SetACVoltagePerPhase(*v)
}

// SetACVoltagePhaseToPhasePair sets the phase-to-phase voltage (PhasePair -> mV).
func (m *Measurement) SetACVoltagePhaseToPhasePair(acVoltagePhaseToPhasePair map[PhasePair]uint32) error {
	attr, err := m.GetAttribute(MeasurementAttrACVoltagePhaseToPhasePair)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(acVoltagePhaseToPhasePair)
}

// ClearACVoltagePhaseToPhasePair clears the phase-to-phase voltage (PhasePair -> mV).
func (m *Measurement) ClearACVoltagePhaseToPhasePair() error {
	attr, err := m.GetAttribute(MeasurementAttrACVoltagePhaseToPhasePair)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetACVoltagePhaseToPhasePairPtr sets or clears the phase-to-phase voltage (PhasePair -> mV) from a pointer.
func (m *Measurement) SetACVoltagePhaseToPhasePairPtr(v *map[PhasePair]uint32) error {
	if v == nil {
		return m.ClearACVoltagePhaseToPhasePair()
	}
	return m.SetACVoltagePhaseToPhasePair(*v)
}

// SetACFrequency sets the grid frequency (e.g., 50000 = 50.000 Hz).
func (m *Measurement) SetACFrequency(acFrequency uint32) error {
	attr, err := m.GetAttribute(MeasurementAttrACFrequency)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(acFrequency)
}

// ClearACFrequency clears the grid frequency (e.g., 50000 = 50.000 Hz).
func (m *Measurement) ClearACFrequency() error {
	attr, err := m.GetAttribute(MeasurementAttrACFrequency)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetACFrequencyPtr sets or clears the grid frequency (e.g., 50000 = 50.000 Hz) from a pointer.
func (m *Measurement) SetACFrequencyPtr(v *uint32) error {
	if v == nil {
		return m.ClearACFrequency()
	}
	return m.SetACFrequency(*v)
}

// SetPowerFactor sets the power factor (0.001 units, -1.0 to +1.0).
func (m *Measurement) SetPowerFactor(powerFactor int16) error {
	attr, err := m.GetAttribute(MeasurementAttrPowerFactor)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(powerFactor)
}

// ClearPowerFactor clears the power factor (0.001 units, -1.0 to +1.0).
func (m *Measurement) ClearPowerFactor() error {
	attr, err := m.GetAttribute(MeasurementAttrPowerFactor)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetPowerFactorPtr sets or clears the power factor (0.001 units, -1.0 to +1.0) from a pointer.
func (m *Measurement) SetPowerFactorPtr(v *int16) error {
	if v == nil {
		return m.ClearPowerFactor()
	}
	return m.SetPowerFactor(*v)
}

// SetACEnergyConsumed sets the total energy consumed from grid.
func (m *Measurement) SetACEnergyConsumed(acEnergyConsumed uint64) error {
	attr, err := m.GetAttribute(MeasurementAttrACEnergyConsumed)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(acEnergyConsumed)
}

// ClearACEnergyConsumed clears the total energy consumed from grid.
func (m *Measurement) ClearACEnergyConsumed() error {
	attr, err := m.GetAttribute(MeasurementAttrACEnergyConsumed)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetACEnergyConsumedPtr sets or clears the total energy consumed from grid from a pointer.
func (m *Measurement) SetACEnergyConsumedPtr(v *uint64) error {
	if v == nil {
		return m.ClearACEnergyConsumed()
	}
	return m.SetACEnergyConsumed(*v)
}

// SetACEnergyProduced sets the total energy produced/fed-in to grid.
func (m *Measurement) SetACEnergyProduced(acEnergyProduced uint64) error {
	attr, err := m.GetAttribute(MeasurementAttrACEnergyProduced)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(acEnergyProduced)
}

// ClearACEnergyProduced clears the total energy produced/fed-in to grid.
func (m *Measurement) ClearACEnergyProduced() error {
	attr, err := m.GetAttribute(MeasurementAttrACEnergyProduced)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetACEnergyProducedPtr sets or clears the total energy produced/fed-in to grid from a pointer.
func (m *Measurement) SetACEnergyProducedPtr(v *uint64) error {
	if v == nil {
		return m.ClearACEnergyProduced()
	}
	return m.SetACEnergyProduced(*v)
}

// SetDCPower sets the dC power (+ into device, - out).
func (m *Measurement) SetDCPower(dcPower int64) error {
	attr, err := m.GetAttribute(MeasurementAttrDCPower)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(dcPower)
}

// ClearDCPower clears the dC power (+ into device, - out).
func (m *Measurement) ClearDCPower() error {
	attr, err := m.GetAttribute(MeasurementAttrDCPower)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetDCPowerPtr sets or clears the dC power (+ into device, - out) from a pointer.
func (m *Measurement) SetDCPowerPtr(v *int64) error {
	if v == nil {
		return m.ClearDCPower()
	}
	return m.SetDCPower(*v)
}

// SetDCCurrent sets the dC current (+ into device, - out).
func (m *Measurement) SetDCCurrent(dcCurrent int64) error {
	attr, err := m.GetAttribute(MeasurementAttrDCCurrent)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(dcCurrent)
}

// ClearDCCurrent clears the dC current (+ into device, - out).
func (m *Measurement) ClearDCCurrent() error {
	attr, err := m.GetAttribute(MeasurementAttrDCCurrent)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetDCCurrentPtr sets or clears the dC current (+ into device, - out) from a pointer.
func (m *Measurement) SetDCCurrentPtr(v *int64) error {
	if v == nil {
		return m.ClearDCCurrent()
	}
	return m.SetDCCurrent(*v)
}

// SetDCVoltage sets the dC voltage.
func (m *Measurement) SetDCVoltage(dcVoltage uint32) error {
	attr, err := m.GetAttribute(MeasurementAttrDCVoltage)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(dcVoltage)
}

// ClearDCVoltage clears the dC voltage.
func (m *Measurement) ClearDCVoltage() error {
	attr, err := m.GetAttribute(MeasurementAttrDCVoltage)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetDCVoltagePtr sets or clears the dC voltage from a pointer.
func (m *Measurement) SetDCVoltagePtr(v *uint32) error {
	if v == nil {
		return m.ClearDCVoltage()
	}
	return m.SetDCVoltage(*v)
}

// SetDCEnergyIn sets the energy into this component.
func (m *Measurement) SetDCEnergyIn(dcEnergyIn uint64) error {
	attr, err := m.GetAttribute(MeasurementAttrDCEnergyIn)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(dcEnergyIn)
}

// ClearDCEnergyIn clears the energy into this component.
func (m *Measurement) ClearDCEnergyIn() error {
	attr, err := m.GetAttribute(MeasurementAttrDCEnergyIn)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetDCEnergyInPtr sets or clears the energy into this component from a pointer.
func (m *Measurement) SetDCEnergyInPtr(v *uint64) error {
	if v == nil {
		return m.ClearDCEnergyIn()
	}
	return m.SetDCEnergyIn(*v)
}

// SetDCEnergyOut sets the energy out of this component.
func (m *Measurement) SetDCEnergyOut(dcEnergyOut uint64) error {
	attr, err := m.GetAttribute(MeasurementAttrDCEnergyOut)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(dcEnergyOut)
}

// ClearDCEnergyOut clears the energy out of this component.
func (m *Measurement) ClearDCEnergyOut() error {
	attr, err := m.GetAttribute(MeasurementAttrDCEnergyOut)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetDCEnergyOutPtr sets or clears the energy out of this component from a pointer.
func (m *Measurement) SetDCEnergyOutPtr(v *uint64) error {
	if v == nil {
		return m.ClearDCEnergyOut()
	}
	return m.SetDCEnergyOut(*v)
}

// SetStateOfCharge sets the state of charge (0-100%).
func (m *Measurement) SetStateOfCharge(stateOfCharge uint8) error {
	attr, err := m.GetAttribute(MeasurementAttrStateOfCharge)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(stateOfCharge)
}

// ClearStateOfCharge clears the state of charge (0-100%).
func (m *Measurement) ClearStateOfCharge() error {
	attr, err := m.GetAttribute(MeasurementAttrStateOfCharge)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetStateOfChargePtr sets or clears the state of charge (0-100%) from a pointer.
func (m *Measurement) SetStateOfChargePtr(v *uint8) error {
	if v == nil {
		return m.ClearStateOfCharge()
	}
	return m.SetStateOfCharge(*v)
}

// SetStateOfHealth sets the state of health (0-100%, battery degradation).
func (m *Measurement) SetStateOfHealth(stateOfHealth uint8) error {
	attr, err := m.GetAttribute(MeasurementAttrStateOfHealth)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(stateOfHealth)
}

// ClearStateOfHealth clears the state of health (0-100%, battery degradation).
func (m *Measurement) ClearStateOfHealth() error {
	attr, err := m.GetAttribute(MeasurementAttrStateOfHealth)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetStateOfHealthPtr sets or clears the state of health (0-100%, battery degradation) from a pointer.
func (m *Measurement) SetStateOfHealthPtr(v *uint8) error {
	if v == nil {
		return m.ClearStateOfHealth()
	}
	return m.SetStateOfHealth(*v)
}

// SetStateOfEnergy sets the available energy at current SoC.
func (m *Measurement) SetStateOfEnergy(stateOfEnergy uint64) error {
	attr, err := m.GetAttribute(MeasurementAttrStateOfEnergy)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(stateOfEnergy)
}

// ClearStateOfEnergy clears the available energy at current SoC.
func (m *Measurement) ClearStateOfEnergy() error {
	attr, err := m.GetAttribute(MeasurementAttrStateOfEnergy)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetStateOfEnergyPtr sets or clears the available energy at current SoC from a pointer.
func (m *Measurement) SetStateOfEnergyPtr(v *uint64) error {
	if v == nil {
		return m.ClearStateOfEnergy()
	}
	return m.SetStateOfEnergy(*v)
}

// SetUseableCapacity sets the current useable capacity.
func (m *Measurement) SetUseableCapacity(useableCapacity uint64) error {
	attr, err := m.GetAttribute(MeasurementAttrUseableCapacity)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(useableCapacity)
}

// ClearUseableCapacity clears the current useable capacity.
func (m *Measurement) ClearUseableCapacity() error {
	attr, err := m.GetAttribute(MeasurementAttrUseableCapacity)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetUseableCapacityPtr sets or clears the current useable capacity from a pointer.
func (m *Measurement) SetUseableCapacityPtr(v *uint64) error {
	if v == nil {
		return m.ClearUseableCapacity()
	}
	return m.SetUseableCapacity(*v)
}

// SetCycleCount sets the charge/discharge cycles.
func (m *Measurement) SetCycleCount(cycleCount uint32) error {
	attr, err := m.GetAttribute(MeasurementAttrCycleCount)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(cycleCount)
}

// ClearCycleCount clears the charge/discharge cycles.
func (m *Measurement) ClearCycleCount() error {
	attr, err := m.GetAttribute(MeasurementAttrCycleCount)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetCycleCountPtr sets or clears the charge/discharge cycles from a pointer.
func (m *Measurement) SetCycleCountPtr(v *uint32) error {
	if v == nil {
		return m.ClearCycleCount()
	}
	return m.SetCycleCount(*v)
}

// SetTemperature sets the temperature (e.g., 2500 = 25.00C).
func (m *Measurement) SetTemperature(temperature int16) error {
	attr, err := m.GetAttribute(MeasurementAttrTemperature)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(temperature)
}

// ClearTemperature clears the temperature (e.g., 2500 = 25.00C).
func (m *Measurement) ClearTemperature() error {
	attr, err := m.GetAttribute(MeasurementAttrTemperature)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetTemperaturePtr sets or clears the temperature (e.g., 2500 = 25.00C) from a pointer.
func (m *Measurement) SetTemperaturePtr(v *int16) error {
	if v == nil {
		return m.ClearTemperature()
	}
	return m.SetTemperature(*v)
}
