// Code generated by mash-featgen. DO NOT EDIT.

package features

// Phase represents device phase (internal).
type Phase uint8

const (
	PhaseA Phase = 0x00
	PhaseB Phase = 0x01
	PhaseC Phase = 0x02
)

// String returns the phase name.
func (v Phase) String() string {
	switch v {
	case PhaseA:
		return "A"
	case PhaseB:
		return "B"
	case PhaseC:
		return "C"
	default:
		return "UNKNOWN"
	}
}

// GridPhase represents grid phase.
type GridPhase uint8

const (
	GridPhaseL1 GridPhase = 0x00
	GridPhaseL2 GridPhase = 0x01
	GridPhaseL3 GridPhase = 0x02
)

// String returns the gridPhase name.
func (v GridPhase) String() string {
	switch v {
	case GridPhaseL1:
		return "L1"
	case GridPhaseL2:
		return "L2"
	case GridPhaseL3:
		return "L3"
	default:
		return "UNKNOWN"
	}
}

// PhasePair represents phase pair for phase-to-phase voltage.
type PhasePair uint8

const (
	PhasePairAB PhasePair = 0x00
	PhasePairBC PhasePair = 0x01
	PhasePairCA PhasePair = 0x02
)

// String returns the phasePair name.
func (v PhasePair) String() string {
	switch v {
	case PhasePairAB:
		return "AB"
	case PhasePairBC:
		return "BC"
	case PhasePairCA:
		return "CA"
	default:
		return "UNKNOWN"
	}
}

// Direction represents power flow direction capability.
type Direction uint8

const (
	DirectionConsumption   Direction = 0x00
	DirectionProduction    Direction = 0x01
	DirectionBidirectional Direction = 0x02
)

// String returns the direction name.
func (v Direction) String() string {
	switch v {
	case DirectionConsumption:
		return "CONSUMPTION"
	case DirectionProduction:
		return "PRODUCTION"
	case DirectionBidirectional:
		return "BIDIRECTIONAL"
	default:
		return "UNKNOWN"
	}
}

// AsymmetricSupport represents per-phase asymmetric control capability.
type AsymmetricSupport uint8

const (
	AsymmetricSupportNone          AsymmetricSupport = 0x00
	AsymmetricSupportConsumption   AsymmetricSupport = 0x01
	AsymmetricSupportProduction    AsymmetricSupport = 0x02
	AsymmetricSupportBidirectional AsymmetricSupport = 0x03
)

// String returns the asymmetricSupport name.
func (v AsymmetricSupport) String() string {
	switch v {
	case AsymmetricSupportNone:
		return "NONE"
	case AsymmetricSupportConsumption:
		return "CONSUMPTION"
	case AsymmetricSupportProduction:
		return "PRODUCTION"
	case AsymmetricSupportBidirectional:
		return "BIDIRECTIONAL"
	default:
		return "UNKNOWN"
	}
}
