// Code generated by mash-featgen. DO NOT EDIT.

package features

import (
	"context"

	"github.com/mash-protocol/mash-go/pkg/model"
	"github.com/mash-protocol/mash-go/pkg/wire"
)

// Tariff attribute IDs.
const (
	TariffAttrTariffID          uint16 = 1
	TariffAttrCurrency          uint16 = 2
	TariffAttrPriceUnit         uint16 = 3
	TariffAttrTariffDescription uint16 = 4
)

// TariffFeatureRevision is the current revision of the Tariff feature.
const TariffFeatureRevision uint16 = 1

// PriceUnit represents unit for price values.
type PriceUnit uint8

const (
	// PriceUnitPerKwh price per kilowatt-hour.
	PriceUnitPerKwh PriceUnit = 0x00
	// PriceUnitPerKvah price per kilovolt-ampere-hour.
	PriceUnitPerKvah PriceUnit = 0x01
)

// String returns the priceUnit name.
func (v PriceUnit) String() string {
	switch v {
	case PriceUnitPerKwh:
		return "PER_KWH"
	case PriceUnitPerKvah:
		return "PER_KVAH"
	default:
		return "UNKNOWN"
	}
}

// Tariff wraps a Feature with Tariff-specific functionality.
// Static tariff metadata: currency context for Signals price values.
type Tariff struct {
	*model.Feature
	onSetTariff func(ctx context.Context, req SetTariffRequest) error
}

// NewTariff creates a new Tariff feature.
func NewTariff() *Tariff {
	f := model.NewFeature(model.FeatureTariff, TariffFeatureRevision)

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          TariffAttrTariffID,
		Name:        "tariffId",
		Type:        model.DataTypeUint32,
		Access:      model.AccessReadOnly,
		Default:     uint32(0),
		Description: "Tariff identifier",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          TariffAttrCurrency,
		Name:        "currency",
		Type:        model.DataTypeString,
		Access:      model.AccessReadOnly,
		Description: "ISO 4217 currency code (EUR, USD, etc.)",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          TariffAttrPriceUnit,
		Name:        "priceUnit",
		Type:        model.DataTypeUint8,
		Access:      model.AccessReadOnly,
		Default:     uint8(PriceUnitPerKwh),
		Description: "Unit for price values in Signals",
	}))

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          TariffAttrTariffDescription,
		Name:        "tariffDescription",
		Type:        model.DataTypeString,
		Access:      model.AccessReadOnly,
		Nullable:    true,
		Description: "Human-readable tariff name",
	}))

	t := &Tariff{Feature: f}
	t.addCommands()

	return t
}

// TariffID returns the tariff identifier.
func (t *Tariff) TariffID() uint32 {
	val, _ := t.ReadAttribute(TariffAttrTariffID)
	if v, ok := val.(uint32); ok {
		return v
	}
	return uint32(0)
}

// Currency returns the iSO 4217 currency code (EUR, USD, etc.).
func (t *Tariff) Currency() string {
	val, _ := t.ReadAttribute(TariffAttrCurrency)
	if v, ok := val.(string); ok {
		return v
	}
	return ""
}

// PriceUnit returns the unit for price values in Signals.
func (t *Tariff) PriceUnit() PriceUnit {
	val, _ := t.ReadAttribute(TariffAttrPriceUnit)
	if v, ok := val.(uint8); ok {
		return PriceUnit(v)
	}
	return PriceUnitPerKwh
}

// TariffDescription returns the human-readable tariff name.
func (t *Tariff) TariffDescription() (string, bool) {
	val, err := t.ReadAttribute(TariffAttrTariffDescription)
	if err != nil || val == nil {
		return "", false
	}
	if v, ok := val.(string); ok {
		return v, true
	}
	return "", false
}

// SetTariffID sets the tariff identifier.
func (t *Tariff) SetTariffID(tariffId uint32) error {
	attr, err := t.GetAttribute(TariffAttrTariffID)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(tariffId)
}

// SetCurrency sets the iSO 4217 currency code (EUR, USD, etc.).
func (t *Tariff) SetCurrency(currency string) error {
	attr, err := t.GetAttribute(TariffAttrCurrency)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(currency)
}

// SetPriceUnit sets the unit for price values in Signals.
func (t *Tariff) SetPriceUnit(priceUnit PriceUnit) error {
	attr, err := t.GetAttribute(TariffAttrPriceUnit)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(uint8(priceUnit))
}

// SetTariffDescription sets the human-readable tariff name.
func (t *Tariff) SetTariffDescription(tariffDescription string) error {
	attr, err := t.GetAttribute(TariffAttrTariffDescription)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(tariffDescription)
}

// ClearTariffDescription clears the human-readable tariff name.
func (t *Tariff) ClearTariffDescription() error {
	attr, err := t.GetAttribute(TariffAttrTariffDescription)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(nil)
}

// SetTariffDescriptionPtr sets or clears the human-readable tariff name from a pointer.
func (t *Tariff) SetTariffDescriptionPtr(v *string) error {
	if v == nil {
		return t.ClearTariffDescription()
	}
	return t.SetTariffDescription(*v)
}

// Tariff command IDs.
const (
	TariffCmdSetTariff uint8 = 1
)

// SetTariffRequest represents the setTariff command parameters.
type SetTariffRequest struct {
	TariffID    uint32
	Currency    string
	PriceUnit   *PriceUnit
	Description *string
}

// addCommands adds the Tariff commands.
func (t *Tariff) addCommands() {
	t.AddCommand(model.NewCommand(&model.CommandMetadata{
		ID:          TariffCmdSetTariff,
		Name:        "setTariff",
		Description: "Set tariff metadata",
		Parameters: []model.ParameterMetadata{
			{Name: "tariffId", Type: model.DataTypeUint32, Required: true},
			{Name: "currency", Type: model.DataTypeString, Required: true},
			{Name: "priceUnit", Type: model.DataTypeUint8, Required: false},
			{Name: "description", Type: model.DataTypeString, Required: false},
		},
	}, t.handleSetTariff))

}

func (t *Tariff) handleSetTariff(ctx context.Context, params map[string]any) (map[string]any, error) {
	if t.onSetTariff == nil {
		return map[string]any{"success": false}, nil
	}

	req := SetTariffRequest{}
	if raw, exists := params["tariffId"]; exists {
		if v, ok := wire.ToUint32(raw); ok {
			req.TariffID = v
		}
	}
	if raw, exists := params["currency"]; exists {
		if v, ok := raw.(string); ok {
			req.Currency = v
		}
	}
	if raw, exists := params["priceUnit"]; exists {
		if v, ok := wire.ToUint8Public(raw); ok {
			tmp := PriceUnit(v)
			req.PriceUnit = &tmp
		}
	}
	if raw, exists := params["description"]; exists {
		if v, ok := raw.(string); ok {
			req.Description = &v
		}
	}

	err := t.onSetTariff(ctx, req)
	return map[string]any{"success": err == nil}, err
}

// OnSetTariff sets the handler for setTariff command.
func (t *Tariff) OnSetTariff(handler func(ctx context.Context, req SetTariffRequest) error) {
	t.onSetTariff = handler
}
