// Code generated by mash-featgen. DO NOT EDIT.

package features

import (
	"context"

	"github.com/mash-protocol/mash-go/pkg/model"
	"github.com/mash-protocol/mash-go/pkg/wire"
)

// TestControl attribute IDs.
const (
	TestControlAttrTestEventTriggersEnabled uint16 = 1
)

// TestControlFeatureRevision is the current revision of the TestControl feature.
const TestControlFeatureRevision uint16 = 1

// TestControl wraps a Feature with TestControl-specific functionality.
// Test control and event triggering for conformance testing (Matter-inspired).
type TestControl struct {
	*model.Feature
	onTriggerTestEvent               func(ctx context.Context, req TriggerTestEventRequest) error
	onSetCommissioningWindowDuration func(ctx context.Context, req SetCommissioningWindowDurationRequest) error
}

// NewTestControl creates a new TestControl feature.
func NewTestControl() *TestControl {
	f := model.NewFeature(model.FeatureTestControl, TestControlFeatureRevision)

	f.AddAttribute(model.NewAttribute(&model.AttributeMetadata{
		ID:          TestControlAttrTestEventTriggersEnabled,
		Name:        "testEventTriggersEnabled",
		Type:        model.DataTypeBool,
		Access:      model.AccessReadOnly,
		Default:     false,
		Description: "Whether test event triggers are enabled on this device.",
	}))

	t := &TestControl{Feature: f}
	t.addCommands()

	return t
}

// TestEventTriggersEnabled returns the whether test event triggers are enabled on this device..
func (t *TestControl) TestEventTriggersEnabled() bool {
	val, _ := t.ReadAttribute(TestControlAttrTestEventTriggersEnabled)
	if v, ok := val.(bool); ok {
		return v
	}
	return false
}

// SetTestEventTriggersEnabled sets the whether test event triggers are enabled on this device..
func (t *TestControl) SetTestEventTriggersEnabled(testEventTriggersEnabled bool) error {
	attr, err := t.GetAttribute(TestControlAttrTestEventTriggersEnabled)
	if err != nil {
		return err
	}
	return attr.SetValueInternal(testEventTriggersEnabled)
}

// TestControl command IDs.
const (
	TestControlCmdTriggerTestEvent               uint8 = 1
	TestControlCmdSetCommissioningWindowDuration uint8 = 2
)

// TriggerTestEventRequest represents the triggerTestEvent command parameters.
type TriggerTestEventRequest struct {
	EnableKey    string
	EventTrigger uint64
}

// SetCommissioningWindowDurationRequest represents the setCommissioningWindowDuration command parameters.
type SetCommissioningWindowDurationRequest struct {
	EnableKey       string
	DurationSeconds uint32
}

// addCommands adds the TestControl commands.
func (t *TestControl) addCommands() {
	t.AddCommand(model.NewCommand(&model.CommandMetadata{
		ID:          TestControlCmdTriggerTestEvent,
		Name:        "triggerTestEvent",
		Description: "Trigger a test event by opcode. Requires matching 128-bit enableKey (hex-encoded, 32 chars). Matter-inspired safety gate.",
		Parameters: []model.ParameterMetadata{
			{Name: "enableKey", Type: model.DataTypeString, Required: true},
			{Name: "eventTrigger", Type: model.DataTypeUint64, Required: true},
		},
	}, t.handleTriggerTestEvent))

	t.AddCommand(model.NewCommand(&model.CommandMetadata{
		ID:          TestControlCmdSetCommissioningWindowDuration,
		Name:        "setCommissioningWindowDuration",
		Description: "Set commissioning window duration (test mode only). Requires matching enableKey.",
		Parameters: []model.ParameterMetadata{
			{Name: "enableKey", Type: model.DataTypeString, Required: true},
			{Name: "durationSeconds", Type: model.DataTypeUint32, Required: true},
		},
	}, t.handleSetCommissioningWindowDuration))

}

func (t *TestControl) handleTriggerTestEvent(ctx context.Context, params map[string]any) (map[string]any, error) {
	if t.onTriggerTestEvent == nil {
		return map[string]any{"success": false}, nil
	}

	req := TriggerTestEventRequest{}
	if raw, exists := params["enableKey"]; exists {
		if v, ok := raw.(string); ok {
			req.EnableKey = v
		}
	}
	if raw, exists := params["eventTrigger"]; exists {
		if v, ok := raw.(uint64); ok {
			req.EventTrigger = v
		}
	}

	err := t.onTriggerTestEvent(ctx, req)
	return map[string]any{"success": err == nil}, err
}

func (t *TestControl) handleSetCommissioningWindowDuration(ctx context.Context, params map[string]any) (map[string]any, error) {
	if t.onSetCommissioningWindowDuration == nil {
		return map[string]any{"success": false}, nil
	}

	req := SetCommissioningWindowDurationRequest{}
	if raw, exists := params["enableKey"]; exists {
		if v, ok := raw.(string); ok {
			req.EnableKey = v
		}
	}
	if raw, exists := params["durationSeconds"]; exists {
		if v, ok := wire.ToUint32(raw); ok {
			req.DurationSeconds = v
		}
	}

	err := t.onSetCommissioningWindowDuration(ctx, req)
	return map[string]any{"success": err == nil}, err
}

// OnTriggerTestEvent sets the handler for triggerTestEvent command.
func (t *TestControl) OnTriggerTestEvent(handler func(ctx context.Context, req TriggerTestEventRequest) error) {
	t.onTriggerTestEvent = handler
}

// OnSetCommissioningWindowDuration sets the handler for setCommissioningWindowDuration command.
func (t *TestControl) OnSetCommissioningWindowDuration(handler func(ctx context.Context, req SetCommissioningWindowDurationRequest) error) {
	t.onSetCommissioningWindowDuration = handler
}
