// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	discovery "github.com/mash-protocol/mash-go/pkg/discovery"
	mock "github.com/stretchr/testify/mock"
)

// MockBrowser is an autogenerated mock type for the Browser type
type MockBrowser struct {
	mock.Mock
}

type MockBrowser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrowser) EXPECT() *MockBrowser_Expecter {
	return &MockBrowser_Expecter{mock: &_m.Mock}
}

// BrowseCommissionable provides a mock function with given fields: ctx
func (_m *MockBrowser) BrowseCommissionable(ctx context.Context) (<-chan *discovery.CommissionableService, <-chan *discovery.CommissionableService, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BrowseCommissionable")
	}

	var r0 <-chan *discovery.CommissionableService
	var r1 <-chan *discovery.CommissionableService
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan *discovery.CommissionableService, <-chan *discovery.CommissionableService, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan *discovery.CommissionableService); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *discovery.CommissionableService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) <-chan *discovery.CommissionableService); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan *discovery.CommissionableService)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBrowser_BrowseCommissionable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BrowseCommissionable'
type MockBrowser_BrowseCommissionable_Call struct {
	*mock.Call
}

// BrowseCommissionable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBrowser_Expecter) BrowseCommissionable(ctx interface{}) *MockBrowser_BrowseCommissionable_Call {
	return &MockBrowser_BrowseCommissionable_Call{Call: _e.mock.On("BrowseCommissionable", ctx)}
}

func (_c *MockBrowser_BrowseCommissionable_Call) Run(run func(ctx context.Context)) *MockBrowser_BrowseCommissionable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBrowser_BrowseCommissionable_Call) Return(added <-chan *discovery.CommissionableService, removed <-chan *discovery.CommissionableService, err error) *MockBrowser_BrowseCommissionable_Call {
	_c.Call.Return(added, removed, err)
	return _c
}

func (_c *MockBrowser_BrowseCommissionable_Call) RunAndReturn(run func(context.Context) (<-chan *discovery.CommissionableService, <-chan *discovery.CommissionableService, error)) *MockBrowser_BrowseCommissionable_Call {
	_c.Call.Return(run)
	return _c
}

// BrowseCommissioners provides a mock function with given fields: ctx
func (_m *MockBrowser) BrowseCommissioners(ctx context.Context) (<-chan *discovery.CommissionerService, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BrowseCommissioners")
	}

	var r0 <-chan *discovery.CommissionerService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan *discovery.CommissionerService, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan *discovery.CommissionerService); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *discovery.CommissionerService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBrowser_BrowseCommissioners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BrowseCommissioners'
type MockBrowser_BrowseCommissioners_Call struct {
	*mock.Call
}

// BrowseCommissioners is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBrowser_Expecter) BrowseCommissioners(ctx interface{}) *MockBrowser_BrowseCommissioners_Call {
	return &MockBrowser_BrowseCommissioners_Call{Call: _e.mock.On("BrowseCommissioners", ctx)}
}

func (_c *MockBrowser_BrowseCommissioners_Call) Run(run func(ctx context.Context)) *MockBrowser_BrowseCommissioners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBrowser_BrowseCommissioners_Call) Return(_a0 <-chan *discovery.CommissionerService, _a1 error) *MockBrowser_BrowseCommissioners_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBrowser_BrowseCommissioners_Call) RunAndReturn(run func(context.Context) (<-chan *discovery.CommissionerService, error)) *MockBrowser_BrowseCommissioners_Call {
	_c.Call.Return(run)
	return _c
}

// BrowseOperational provides a mock function with given fields: ctx, zoneID
func (_m *MockBrowser) BrowseOperational(ctx context.Context, zoneID string) (<-chan *discovery.OperationalService, error) {
	ret := _m.Called(ctx, zoneID)

	if len(ret) == 0 {
		panic("no return value specified for BrowseOperational")
	}

	var r0 <-chan *discovery.OperationalService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (<-chan *discovery.OperationalService, error)); ok {
		return rf(ctx, zoneID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan *discovery.OperationalService); ok {
		r0 = rf(ctx, zoneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *discovery.OperationalService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, zoneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBrowser_BrowseOperational_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BrowseOperational'
type MockBrowser_BrowseOperational_Call struct {
	*mock.Call
}

// BrowseOperational is a helper method to define mock.On call
//   - ctx context.Context
//   - zoneID string
func (_e *MockBrowser_Expecter) BrowseOperational(ctx interface{}, zoneID interface{}) *MockBrowser_BrowseOperational_Call {
	return &MockBrowser_BrowseOperational_Call{Call: _e.mock.On("BrowseOperational", ctx, zoneID)}
}

func (_c *MockBrowser_BrowseOperational_Call) Run(run func(ctx context.Context, zoneID string)) *MockBrowser_BrowseOperational_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBrowser_BrowseOperational_Call) Return(_a0 <-chan *discovery.OperationalService, _a1 error) *MockBrowser_BrowseOperational_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBrowser_BrowseOperational_Call) RunAndReturn(run func(context.Context, string) (<-chan *discovery.OperationalService, error)) *MockBrowser_BrowseOperational_Call {
	_c.Call.Return(run)
	return _c
}

// BrowsePairingRequests provides a mock function with given fields: ctx, callback
func (_m *MockBrowser) BrowsePairingRequests(ctx context.Context, callback func(discovery.PairingRequestService)) error {
	ret := _m.Called(ctx, callback)

	if len(ret) == 0 {
		panic("no return value specified for BrowsePairingRequests")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(discovery.PairingRequestService)) error); ok {
		r0 = rf(ctx, callback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBrowser_BrowsePairingRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BrowsePairingRequests'
type MockBrowser_BrowsePairingRequests_Call struct {
	*mock.Call
}

// BrowsePairingRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - callback func(discovery.PairingRequestService)
func (_e *MockBrowser_Expecter) BrowsePairingRequests(ctx interface{}, callback interface{}) *MockBrowser_BrowsePairingRequests_Call {
	return &MockBrowser_BrowsePairingRequests_Call{Call: _e.mock.On("BrowsePairingRequests", ctx, callback)}
}

func (_c *MockBrowser_BrowsePairingRequests_Call) Run(run func(ctx context.Context, callback func(discovery.PairingRequestService))) *MockBrowser_BrowsePairingRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(discovery.PairingRequestService)))
	})
	return _c
}

func (_c *MockBrowser_BrowsePairingRequests_Call) Return(_a0 error) *MockBrowser_BrowsePairingRequests_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBrowser_BrowsePairingRequests_Call) RunAndReturn(run func(context.Context, func(discovery.PairingRequestService)) error) *MockBrowser_BrowsePairingRequests_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByDiscriminator provides a mock function with given fields: ctx, discriminator
func (_m *MockBrowser) FindAllByDiscriminator(ctx context.Context, discriminator uint16) ([]*discovery.CommissionableService, error) {
	ret := _m.Called(ctx, discriminator)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByDiscriminator")
	}

	var r0 []*discovery.CommissionableService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint16) ([]*discovery.CommissionableService, error)); ok {
		return rf(ctx, discriminator)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint16) []*discovery.CommissionableService); ok {
		r0 = rf(ctx, discriminator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*discovery.CommissionableService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint16) error); ok {
		r1 = rf(ctx, discriminator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBrowser_FindAllByDiscriminator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByDiscriminator'
type MockBrowser_FindAllByDiscriminator_Call struct {
	*mock.Call
}

// FindAllByDiscriminator is a helper method to define mock.On call
//   - ctx context.Context
//   - discriminator uint16
func (_e *MockBrowser_Expecter) FindAllByDiscriminator(ctx interface{}, discriminator interface{}) *MockBrowser_FindAllByDiscriminator_Call {
	return &MockBrowser_FindAllByDiscriminator_Call{Call: _e.mock.On("FindAllByDiscriminator", ctx, discriminator)}
}

func (_c *MockBrowser_FindAllByDiscriminator_Call) Run(run func(ctx context.Context, discriminator uint16)) *MockBrowser_FindAllByDiscriminator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint16))
	})
	return _c
}

func (_c *MockBrowser_FindAllByDiscriminator_Call) Return(_a0 []*discovery.CommissionableService, _a1 error) *MockBrowser_FindAllByDiscriminator_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBrowser_FindAllByDiscriminator_Call) RunAndReturn(run func(context.Context, uint16) ([]*discovery.CommissionableService, error)) *MockBrowser_FindAllByDiscriminator_Call {
	_c.Call.Return(run)
	return _c
}

// FindByDiscriminator provides a mock function with given fields: ctx, discriminator
func (_m *MockBrowser) FindByDiscriminator(ctx context.Context, discriminator uint16) (*discovery.CommissionableService, error) {
	ret := _m.Called(ctx, discriminator)

	if len(ret) == 0 {
		panic("no return value specified for FindByDiscriminator")
	}

	var r0 *discovery.CommissionableService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint16) (*discovery.CommissionableService, error)); ok {
		return rf(ctx, discriminator)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint16) *discovery.CommissionableService); ok {
		r0 = rf(ctx, discriminator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*discovery.CommissionableService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint16) error); ok {
		r1 = rf(ctx, discriminator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBrowser_FindByDiscriminator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByDiscriminator'
type MockBrowser_FindByDiscriminator_Call struct {
	*mock.Call
}

// FindByDiscriminator is a helper method to define mock.On call
//   - ctx context.Context
//   - discriminator uint16
func (_e *MockBrowser_Expecter) FindByDiscriminator(ctx interface{}, discriminator interface{}) *MockBrowser_FindByDiscriminator_Call {
	return &MockBrowser_FindByDiscriminator_Call{Call: _e.mock.On("FindByDiscriminator", ctx, discriminator)}
}

func (_c *MockBrowser_FindByDiscriminator_Call) Run(run func(ctx context.Context, discriminator uint16)) *MockBrowser_FindByDiscriminator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint16))
	})
	return _c
}

func (_c *MockBrowser_FindByDiscriminator_Call) Return(_a0 *discovery.CommissionableService, _a1 error) *MockBrowser_FindByDiscriminator_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBrowser_FindByDiscriminator_Call) RunAndReturn(run func(context.Context, uint16) (*discovery.CommissionableService, error)) *MockBrowser_FindByDiscriminator_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockBrowser) Stop() {
	_m.Called()
}

// MockBrowser_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockBrowser_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockBrowser_Expecter) Stop() *MockBrowser_Stop_Call {
	return &MockBrowser_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockBrowser_Stop_Call) Run(run func()) *MockBrowser_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrowser_Stop_Call) Return() *MockBrowser_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBrowser_Stop_Call) RunAndReturn(run func()) *MockBrowser_Stop_Call {
	_c.Run(run)
	return _c
}

// NewMockBrowser creates a new instance of MockBrowser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrowser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrowser {
	mock := &MockBrowser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
