// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/mash-protocol/mash-go/pkg/model"
	"github.com/mash-protocol/mash-go/pkg/subscription"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSubscriptionTracker creates a new instance of MockSubscriptionTracker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionTracker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionTracker {
	mock := &MockSubscriptionTracker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriptionTracker is an autogenerated mock type for the SubscriptionTracker type
type MockSubscriptionTracker struct {
	mock.Mock
}

type MockSubscriptionTracker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionTracker) EXPECT() *MockSubscriptionTracker_Expecter {
	return &MockSubscriptionTracker_Expecter{mock: &_m.Mock}
}

// ClearAll provides a mock function for the type MockSubscriptionTracker
func (_mock *MockSubscriptionTracker) ClearAll() {
	_mock.Called()
	return
}

// MockSubscriptionTracker_ClearAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAll'
type MockSubscriptionTracker_ClearAll_Call struct {
	*mock.Call
}

// ClearAll is a helper method to define mock.On call
func (_e *MockSubscriptionTracker_Expecter) ClearAll() *MockSubscriptionTracker_ClearAll_Call {
	return &MockSubscriptionTracker_ClearAll_Call{Call: _e.mock.On("ClearAll")}
}

func (_c *MockSubscriptionTracker_ClearAll_Call) Run(run func()) *MockSubscriptionTracker_ClearAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSubscriptionTracker_ClearAll_Call) Return() *MockSubscriptionTracker_ClearAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSubscriptionTracker_ClearAll_Call) RunAndReturn(run func()) *MockSubscriptionTracker_ClearAll_Call {
	_c.Run(run)
	return _c
}

// Count provides a mock function for the type MockSubscriptionTracker
func (_mock *MockSubscriptionTracker) Count() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockSubscriptionTracker_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockSubscriptionTracker_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
func (_e *MockSubscriptionTracker_Expecter) Count() *MockSubscriptionTracker_Count_Call {
	return &MockSubscriptionTracker_Count_Call{Call: _e.mock.On("Count")}
}

func (_c *MockSubscriptionTracker_Count_Call) Run(run func()) *MockSubscriptionTracker_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSubscriptionTracker_Count_Call) Return(n int) *MockSubscriptionTracker_Count_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockSubscriptionTracker_Count_Call) RunAndReturn(run func() int) *MockSubscriptionTracker_Count_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyChange provides a mock function for the type MockSubscriptionTracker
func (_mock *MockSubscriptionTracker) NotifyChange(endpointID uint16, featureID uint16, attrID uint16, value any) {
	_mock.Called(endpointID, featureID, attrID, value)
	return
}

// MockSubscriptionTracker_NotifyChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyChange'
type MockSubscriptionTracker_NotifyChange_Call struct {
	*mock.Call
}

// NotifyChange is a helper method to define mock.On call
//   - endpointID uint16
//   - featureID uint16
//   - attrID uint16
//   - value any
func (_e *MockSubscriptionTracker_Expecter) NotifyChange(endpointID interface{}, featureID interface{}, attrID interface{}, value interface{}) *MockSubscriptionTracker_NotifyChange_Call {
	return &MockSubscriptionTracker_NotifyChange_Call{Call: _e.mock.On("NotifyChange", endpointID, featureID, attrID, value)}
}

func (_c *MockSubscriptionTracker_NotifyChange_Call) Run(run func(endpointID uint16, featureID uint16, attrID uint16, value any)) *MockSubscriptionTracker_NotifyChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint16
		if args[0] != nil {
			arg0 = args[0].(uint16)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSubscriptionTracker_NotifyChange_Call) Return() *MockSubscriptionTracker_NotifyChange_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSubscriptionTracker_NotifyChange_Call) RunAndReturn(run func(endpointID uint16, featureID uint16, attrID uint16, value any)) *MockSubscriptionTracker_NotifyChange_Call {
	_c.Run(run)
	return _c
}

// NotifyChanges provides a mock function for the type MockSubscriptionTracker
func (_mock *MockSubscriptionTracker) NotifyChanges(endpointID uint16, featureID uint16, changes map[uint16]any) {
	_mock.Called(endpointID, featureID, changes)
	return
}

// MockSubscriptionTracker_NotifyChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyChanges'
type MockSubscriptionTracker_NotifyChanges_Call struct {
	*mock.Call
}

// NotifyChanges is a helper method to define mock.On call
//   - endpointID uint16
//   - featureID uint16
//   - changes map[uint16]any
func (_e *MockSubscriptionTracker_Expecter) NotifyChanges(endpointID interface{}, featureID interface{}, changes interface{}) *MockSubscriptionTracker_NotifyChanges_Call {
	return &MockSubscriptionTracker_NotifyChanges_Call{Call: _e.mock.On("NotifyChanges", endpointID, featureID, changes)}
}

func (_c *MockSubscriptionTracker_NotifyChanges_Call) Run(run func(endpointID uint16, featureID uint16, changes map[uint16]any)) *MockSubscriptionTracker_NotifyChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint16
		if args[0] != nil {
			arg0 = args[0].(uint16)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		var arg2 map[uint16]any
		if args[2] != nil {
			arg2 = args[2].(map[uint16]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriptionTracker_NotifyChanges_Call) Return() *MockSubscriptionTracker_NotifyChanges_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSubscriptionTracker_NotifyChanges_Call) RunAndReturn(run func(endpointID uint16, featureID uint16, changes map[uint16]any)) *MockSubscriptionTracker_NotifyChanges_Call {
	_c.Run(run)
	return _c
}

// OnNotification provides a mock function for the type MockSubscriptionTracker
func (_mock *MockSubscriptionTracker) OnNotification(fn func(subscription.Notification)) {
	_mock.Called(fn)
	return
}

// MockSubscriptionTracker_OnNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnNotification'
type MockSubscriptionTracker_OnNotification_Call struct {
	*mock.Call
}

// OnNotification is a helper method to define mock.On call
//   - fn func(subscription.Notification)
func (_e *MockSubscriptionTracker_Expecter) OnNotification(fn interface{}) *MockSubscriptionTracker_OnNotification_Call {
	return &MockSubscriptionTracker_OnNotification_Call{Call: _e.mock.On("OnNotification", fn)}
}

func (_c *MockSubscriptionTracker_OnNotification_Call) Run(run func(fn func(subscription.Notification))) *MockSubscriptionTracker_OnNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(subscription.Notification)
		if args[0] != nil {
			arg0 = args[0].(func(subscription.Notification))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSubscriptionTracker_OnNotification_Call) Return() *MockSubscriptionTracker_OnNotification_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSubscriptionTracker_OnNotification_Call) RunAndReturn(run func(fn func(subscription.Notification))) *MockSubscriptionTracker_OnNotification_Call {
	_c.Run(run)
	return _c
}

// ProcessNotifications provides a mock function for the type MockSubscriptionTracker
func (_mock *MockSubscriptionTracker) ProcessNotifications() {
	_mock.Called()
	return
}

// MockSubscriptionTracker_ProcessNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessNotifications'
type MockSubscriptionTracker_ProcessNotifications_Call struct {
	*mock.Call
}

// ProcessNotifications is a helper method to define mock.On call
func (_e *MockSubscriptionTracker_Expecter) ProcessNotifications() *MockSubscriptionTracker_ProcessNotifications_Call {
	return &MockSubscriptionTracker_ProcessNotifications_Call{Call: _e.mock.On("ProcessNotifications")}
}

func (_c *MockSubscriptionTracker_ProcessNotifications_Call) Run(run func()) *MockSubscriptionTracker_ProcessNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSubscriptionTracker_ProcessNotifications_Call) Return() *MockSubscriptionTracker_ProcessNotifications_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSubscriptionTracker_ProcessNotifications_Call) RunAndReturn(run func()) *MockSubscriptionTracker_ProcessNotifications_Call {
	_c.Run(run)
	return _c
}

// Subscribe provides a mock function for the type MockSubscriptionTracker
func (_mock *MockSubscriptionTracker) Subscribe(endpointID uint16, featureID uint16, attributeIDs []uint16, minInterval time.Duration, maxInterval time.Duration, currentValues map[uint16]any) (uint32, error) {
	ret := _mock.Called(endpointID, featureID, attributeIDs, minInterval, maxInterval, currentValues)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint16, uint16, []uint16, time.Duration, time.Duration, map[uint16]any) (uint32, error)); ok {
		return returnFunc(endpointID, featureID, attributeIDs, minInterval, maxInterval, currentValues)
	}
	if returnFunc, ok := ret.Get(0).(func(uint16, uint16, []uint16, time.Duration, time.Duration, map[uint16]any) uint32); ok {
		r0 = returnFunc(endpointID, featureID, attributeIDs, minInterval, maxInterval, currentValues)
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func(uint16, uint16, []uint16, time.Duration, time.Duration, map[uint16]any) error); ok {
		r1 = returnFunc(endpointID, featureID, attributeIDs, minInterval, maxInterval, currentValues)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionTracker_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockSubscriptionTracker_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - endpointID uint16
//   - featureID uint16
//   - attributeIDs []uint16
//   - minInterval time.Duration
//   - maxInterval time.Duration
//   - currentValues map[uint16]any
func (_e *MockSubscriptionTracker_Expecter) Subscribe(endpointID interface{}, featureID interface{}, attributeIDs interface{}, minInterval interface{}, maxInterval interface{}, currentValues interface{}) *MockSubscriptionTracker_Subscribe_Call {
	return &MockSubscriptionTracker_Subscribe_Call{Call: _e.mock.On("Subscribe", endpointID, featureID, attributeIDs, minInterval, maxInterval, currentValues)}
}

func (_c *MockSubscriptionTracker_Subscribe_Call) Run(run func(endpointID uint16, featureID uint16, attributeIDs []uint16, minInterval time.Duration, maxInterval time.Duration, currentValues map[uint16]any)) *MockSubscriptionTracker_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint16
		if args[0] != nil {
			arg0 = args[0].(uint16)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		var arg2 []uint16
		if args[2] != nil {
			arg2 = args[2].([]uint16)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		var arg5 map[uint16]any
		if args[5] != nil {
			arg5 = args[5].(map[uint16]any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockSubscriptionTracker_Subscribe_Call) Return(v uint32, err error) *MockSubscriptionTracker_Subscribe_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockSubscriptionTracker_Subscribe_Call) RunAndReturn(run func(endpointID uint16, featureID uint16, attributeIDs []uint16, minInterval time.Duration, maxInterval time.Duration, currentValues map[uint16]any) (uint32, error)) *MockSubscriptionTracker_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type MockSubscriptionTracker
func (_mock *MockSubscriptionTracker) Unsubscribe(subscriptionID uint32) error {
	ret := _mock.Called(subscriptionID)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint32) error); ok {
		r0 = returnFunc(subscriptionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionTracker_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockSubscriptionTracker_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - subscriptionID uint32
func (_e *MockSubscriptionTracker_Expecter) Unsubscribe(subscriptionID interface{}) *MockSubscriptionTracker_Unsubscribe_Call {
	return &MockSubscriptionTracker_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", subscriptionID)}
}

func (_c *MockSubscriptionTracker_Unsubscribe_Call) Run(run func(subscriptionID uint32)) *MockSubscriptionTracker_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSubscriptionTracker_Unsubscribe_Call) Return(err error) *MockSubscriptionTracker_Unsubscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionTracker_Unsubscribe_Call) RunAndReturn(run func(subscriptionID uint32) error) *MockSubscriptionTracker_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeviceModel creates a new instance of MockDeviceModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceModel {
	mock := &MockDeviceModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceModel is an autogenerated mock type for the DeviceModel type
type MockDeviceModel struct {
	mock.Mock
}

type MockDeviceModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceModel) EXPECT() *MockDeviceModel_Expecter {
	return &MockDeviceModel_Expecter{mock: &_m.Mock}
}

// AddEndpoint provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) AddEndpoint(endpoint *model.Endpoint) error {
	ret := _mock.Called(endpoint)

	if len(ret) == 0 {
		panic("no return value specified for AddEndpoint")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Endpoint) error); ok {
		r0 = returnFunc(endpoint)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceModel_AddEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEndpoint'
type MockDeviceModel_AddEndpoint_Call struct {
	*mock.Call
}

// AddEndpoint is a helper method to define mock.On call
//   - endpoint *model.Endpoint
func (_e *MockDeviceModel_Expecter) AddEndpoint(endpoint interface{}) *MockDeviceModel_AddEndpoint_Call {
	return &MockDeviceModel_AddEndpoint_Call{Call: _e.mock.On("AddEndpoint", endpoint)}
}

func (_c *MockDeviceModel_AddEndpoint_Call) Run(run func(endpoint *model.Endpoint)) *MockDeviceModel_AddEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Endpoint
		if args[0] != nil {
			arg0 = args[0].(*model.Endpoint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceModel_AddEndpoint_Call) Return(err error) *MockDeviceModel_AddEndpoint_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceModel_AddEndpoint_Call) RunAndReturn(run func(endpoint *model.Endpoint) error) *MockDeviceModel_AddEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// DeviceID provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) DeviceID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeviceID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDeviceModel_DeviceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeviceID'
type MockDeviceModel_DeviceID_Call struct {
	*mock.Call
}

// DeviceID is a helper method to define mock.On call
func (_e *MockDeviceModel_Expecter) DeviceID() *MockDeviceModel_DeviceID_Call {
	return &MockDeviceModel_DeviceID_Call{Call: _e.mock.On("DeviceID")}
}

func (_c *MockDeviceModel_DeviceID_Call) Run(run func()) *MockDeviceModel_DeviceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceModel_DeviceID_Call) Return(s string) *MockDeviceModel_DeviceID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDeviceModel_DeviceID_Call) RunAndReturn(run func() string) *MockDeviceModel_DeviceID_Call {
	_c.Call.Return(run)
	return _c
}

// EndpointCount provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) EndpointCount() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EndpointCount")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockDeviceModel_EndpointCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndpointCount'
type MockDeviceModel_EndpointCount_Call struct {
	*mock.Call
}

// EndpointCount is a helper method to define mock.On call
func (_e *MockDeviceModel_Expecter) EndpointCount() *MockDeviceModel_EndpointCount_Call {
	return &MockDeviceModel_EndpointCount_Call{Call: _e.mock.On("EndpointCount")}
}

func (_c *MockDeviceModel_EndpointCount_Call) Run(run func()) *MockDeviceModel_EndpointCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceModel_EndpointCount_Call) Return(n int) *MockDeviceModel_EndpointCount_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockDeviceModel_EndpointCount_Call) RunAndReturn(run func() int) *MockDeviceModel_EndpointCount_Call {
	_c.Call.Return(run)
	return _c
}

// Endpoints provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) Endpoints() []*model.Endpoint {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Endpoints")
	}

	var r0 []*model.Endpoint
	if returnFunc, ok := ret.Get(0).(func() []*model.Endpoint); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Endpoint)
		}
	}
	return r0
}

// MockDeviceModel_Endpoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Endpoints'
type MockDeviceModel_Endpoints_Call struct {
	*mock.Call
}

// Endpoints is a helper method to define mock.On call
func (_e *MockDeviceModel_Expecter) Endpoints() *MockDeviceModel_Endpoints_Call {
	return &MockDeviceModel_Endpoints_Call{Call: _e.mock.On("Endpoints")}
}

func (_c *MockDeviceModel_Endpoints_Call) Run(run func()) *MockDeviceModel_Endpoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceModel_Endpoints_Call) Return(endpoints []*model.Endpoint) *MockDeviceModel_Endpoints_Call {
	_c.Call.Return(endpoints)
	return _c
}

func (_c *MockDeviceModel_Endpoints_Call) RunAndReturn(run func() []*model.Endpoint) *MockDeviceModel_Endpoints_Call {
	_c.Call.Return(run)
	return _c
}

// FindEndpointsByType provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) FindEndpointsByType(endpointType model.EndpointType) []*model.Endpoint {
	ret := _mock.Called(endpointType)

	if len(ret) == 0 {
		panic("no return value specified for FindEndpointsByType")
	}

	var r0 []*model.Endpoint
	if returnFunc, ok := ret.Get(0).(func(model.EndpointType) []*model.Endpoint); ok {
		r0 = returnFunc(endpointType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Endpoint)
		}
	}
	return r0
}

// MockDeviceModel_FindEndpointsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindEndpointsByType'
type MockDeviceModel_FindEndpointsByType_Call struct {
	*mock.Call
}

// FindEndpointsByType is a helper method to define mock.On call
//   - endpointType model.EndpointType
func (_e *MockDeviceModel_Expecter) FindEndpointsByType(endpointType interface{}) *MockDeviceModel_FindEndpointsByType_Call {
	return &MockDeviceModel_FindEndpointsByType_Call{Call: _e.mock.On("FindEndpointsByType", endpointType)}
}

func (_c *MockDeviceModel_FindEndpointsByType_Call) Run(run func(endpointType model.EndpointType)) *MockDeviceModel_FindEndpointsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.EndpointType
		if args[0] != nil {
			arg0 = args[0].(model.EndpointType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceModel_FindEndpointsByType_Call) Return(endpoints []*model.Endpoint) *MockDeviceModel_FindEndpointsByType_Call {
	_c.Call.Return(endpoints)
	return _c
}

func (_c *MockDeviceModel_FindEndpointsByType_Call) RunAndReturn(run func(endpointType model.EndpointType) []*model.Endpoint) *MockDeviceModel_FindEndpointsByType_Call {
	_c.Call.Return(run)
	return _c
}

// FindEndpointsWithFeature provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) FindEndpointsWithFeature(featureType model.FeatureType) []*model.Endpoint {
	ret := _mock.Called(featureType)

	if len(ret) == 0 {
		panic("no return value specified for FindEndpointsWithFeature")
	}

	var r0 []*model.Endpoint
	if returnFunc, ok := ret.Get(0).(func(model.FeatureType) []*model.Endpoint); ok {
		r0 = returnFunc(featureType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Endpoint)
		}
	}
	return r0
}

// MockDeviceModel_FindEndpointsWithFeature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindEndpointsWithFeature'
type MockDeviceModel_FindEndpointsWithFeature_Call struct {
	*mock.Call
}

// FindEndpointsWithFeature is a helper method to define mock.On call
//   - featureType model.FeatureType
func (_e *MockDeviceModel_Expecter) FindEndpointsWithFeature(featureType interface{}) *MockDeviceModel_FindEndpointsWithFeature_Call {
	return &MockDeviceModel_FindEndpointsWithFeature_Call{Call: _e.mock.On("FindEndpointsWithFeature", featureType)}
}

func (_c *MockDeviceModel_FindEndpointsWithFeature_Call) Run(run func(featureType model.FeatureType)) *MockDeviceModel_FindEndpointsWithFeature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.FeatureType
		if args[0] != nil {
			arg0 = args[0].(model.FeatureType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceModel_FindEndpointsWithFeature_Call) Return(endpoints []*model.Endpoint) *MockDeviceModel_FindEndpointsWithFeature_Call {
	_c.Call.Return(endpoints)
	return _c
}

func (_c *MockDeviceModel_FindEndpointsWithFeature_Call) RunAndReturn(run func(featureType model.FeatureType) []*model.Endpoint) *MockDeviceModel_FindEndpointsWithFeature_Call {
	_c.Call.Return(run)
	return _c
}

// GetEndpoint provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) GetEndpoint(id uint8) (*model.Endpoint, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetEndpoint")
	}

	var r0 *model.Endpoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint8) (*model.Endpoint, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint8) *model.Endpoint); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Endpoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint8) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceModel_GetEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndpoint'
type MockDeviceModel_GetEndpoint_Call struct {
	*mock.Call
}

// GetEndpoint is a helper method to define mock.On call
//   - id uint8
func (_e *MockDeviceModel_Expecter) GetEndpoint(id interface{}) *MockDeviceModel_GetEndpoint_Call {
	return &MockDeviceModel_GetEndpoint_Call{Call: _e.mock.On("GetEndpoint", id)}
}

func (_c *MockDeviceModel_GetEndpoint_Call) Run(run func(id uint8)) *MockDeviceModel_GetEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint8
		if args[0] != nil {
			arg0 = args[0].(uint8)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceModel_GetEndpoint_Call) Return(endpoint *model.Endpoint, err error) *MockDeviceModel_GetEndpoint_Call {
	_c.Call.Return(endpoint, err)
	return _c
}

func (_c *MockDeviceModel_GetEndpoint_Call) RunAndReturn(run func(id uint8) (*model.Endpoint, error)) *MockDeviceModel_GetEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetFeature provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) GetFeature(endpointID uint8, featureType model.FeatureType) (*model.Feature, error) {
	ret := _mock.Called(endpointID, featureType)

	if len(ret) == 0 {
		panic("no return value specified for GetFeature")
	}

	var r0 *model.Feature
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint8, model.FeatureType) (*model.Feature, error)); ok {
		return returnFunc(endpointID, featureType)
	}
	if returnFunc, ok := ret.Get(0).(func(uint8, model.FeatureType) *model.Feature); ok {
		r0 = returnFunc(endpointID, featureType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Feature)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint8, model.FeatureType) error); ok {
		r1 = returnFunc(endpointID, featureType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceModel_GetFeature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeature'
type MockDeviceModel_GetFeature_Call struct {
	*mock.Call
}

// GetFeature is a helper method to define mock.On call
//   - endpointID uint8
//   - featureType model.FeatureType
func (_e *MockDeviceModel_Expecter) GetFeature(endpointID interface{}, featureType interface{}) *MockDeviceModel_GetFeature_Call {
	return &MockDeviceModel_GetFeature_Call{Call: _e.mock.On("GetFeature", endpointID, featureType)}
}

func (_c *MockDeviceModel_GetFeature_Call) Run(run func(endpointID uint8, featureType model.FeatureType)) *MockDeviceModel_GetFeature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint8
		if args[0] != nil {
			arg0 = args[0].(uint8)
		}
		var arg1 model.FeatureType
		if args[1] != nil {
			arg1 = args[1].(model.FeatureType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceModel_GetFeature_Call) Return(feature *model.Feature, err error) *MockDeviceModel_GetFeature_Call {
	_c.Call.Return(feature, err)
	return _c
}

func (_c *MockDeviceModel_GetFeature_Call) RunAndReturn(run func(endpointID uint8, featureType model.FeatureType) (*model.Feature, error)) *MockDeviceModel_GetFeature_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) Info() *model.DeviceInfo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 *model.DeviceInfo
	if returnFunc, ok := ret.Get(0).(func() *model.DeviceInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DeviceInfo)
		}
	}
	return r0
}

// MockDeviceModel_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockDeviceModel_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
func (_e *MockDeviceModel_Expecter) Info() *MockDeviceModel_Info_Call {
	return &MockDeviceModel_Info_Call{Call: _e.mock.On("Info")}
}

func (_c *MockDeviceModel_Info_Call) Run(run func()) *MockDeviceModel_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceModel_Info_Call) Return(deviceInfo *model.DeviceInfo) *MockDeviceModel_Info_Call {
	_c.Call.Return(deviceInfo)
	return _c
}

func (_c *MockDeviceModel_Info_Call) RunAndReturn(run func() *model.DeviceInfo) *MockDeviceModel_Info_Call {
	_c.Call.Return(run)
	return _c
}

// InvokeCommand provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) InvokeCommand(ctx context.Context, endpointID uint8, featureType model.FeatureType, cmdID uint8, params map[string]any) (map[string]any, error) {
	ret := _mock.Called(ctx, endpointID, featureType, cmdID, params)

	if len(ret) == 0 {
		panic("no return value specified for InvokeCommand")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint8, model.FeatureType, uint8, map[string]any) (map[string]any, error)); ok {
		return returnFunc(ctx, endpointID, featureType, cmdID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint8, model.FeatureType, uint8, map[string]any) map[string]any); ok {
		r0 = returnFunc(ctx, endpointID, featureType, cmdID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint8, model.FeatureType, uint8, map[string]any) error); ok {
		r1 = returnFunc(ctx, endpointID, featureType, cmdID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceModel_InvokeCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvokeCommand'
type MockDeviceModel_InvokeCommand_Call struct {
	*mock.Call
}

// InvokeCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - endpointID uint8
//   - featureType model.FeatureType
//   - cmdID uint8
//   - params map[string]any
func (_e *MockDeviceModel_Expecter) InvokeCommand(ctx interface{}, endpointID interface{}, featureType interface{}, cmdID interface{}, params interface{}) *MockDeviceModel_InvokeCommand_Call {
	return &MockDeviceModel_InvokeCommand_Call{Call: _e.mock.On("InvokeCommand", ctx, endpointID, featureType, cmdID, params)}
}

func (_c *MockDeviceModel_InvokeCommand_Call) Run(run func(ctx context.Context, endpointID uint8, featureType model.FeatureType, cmdID uint8, params map[string]any)) *MockDeviceModel_InvokeCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint8
		if args[1] != nil {
			arg1 = args[1].(uint8)
		}
		var arg2 model.FeatureType
		if args[2] != nil {
			arg2 = args[2].(model.FeatureType)
		}
		var arg3 uint8
		if args[3] != nil {
			arg3 = args[3].(uint8)
		}
		var arg4 map[string]any
		if args[4] != nil {
			arg4 = args[4].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockDeviceModel_InvokeCommand_Call) Return(stringToV map[string]any, err error) *MockDeviceModel_InvokeCommand_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockDeviceModel_InvokeCommand_Call) RunAndReturn(run func(ctx context.Context, endpointID uint8, featureType model.FeatureType, cmdID uint8, params map[string]any) (map[string]any, error)) *MockDeviceModel_InvokeCommand_Call {
	_c.Call.Return(run)
	return _c
}

// ProductID provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) ProductID() uint16 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProductID")
	}

	var r0 uint16
	if returnFunc, ok := ret.Get(0).(func() uint16); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint16)
	}
	return r0
}

// MockDeviceModel_ProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProductID'
type MockDeviceModel_ProductID_Call struct {
	*mock.Call
}

// ProductID is a helper method to define mock.On call
func (_e *MockDeviceModel_Expecter) ProductID() *MockDeviceModel_ProductID_Call {
	return &MockDeviceModel_ProductID_Call{Call: _e.mock.On("ProductID")}
}

func (_c *MockDeviceModel_ProductID_Call) Run(run func()) *MockDeviceModel_ProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceModel_ProductID_Call) Return(v uint16) *MockDeviceModel_ProductID_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockDeviceModel_ProductID_Call) RunAndReturn(run func() uint16) *MockDeviceModel_ProductID_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAttribute provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) ReadAttribute(endpointID uint8, featureType model.FeatureType, attrID uint16) (any, error) {
	ret := _mock.Called(endpointID, featureType, attrID)

	if len(ret) == 0 {
		panic("no return value specified for ReadAttribute")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint8, model.FeatureType, uint16) (any, error)); ok {
		return returnFunc(endpointID, featureType, attrID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint8, model.FeatureType, uint16) any); ok {
		r0 = returnFunc(endpointID, featureType, attrID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint8, model.FeatureType, uint16) error); ok {
		r1 = returnFunc(endpointID, featureType, attrID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceModel_ReadAttribute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAttribute'
type MockDeviceModel_ReadAttribute_Call struct {
	*mock.Call
}

// ReadAttribute is a helper method to define mock.On call
//   - endpointID uint8
//   - featureType model.FeatureType
//   - attrID uint16
func (_e *MockDeviceModel_Expecter) ReadAttribute(endpointID interface{}, featureType interface{}, attrID interface{}) *MockDeviceModel_ReadAttribute_Call {
	return &MockDeviceModel_ReadAttribute_Call{Call: _e.mock.On("ReadAttribute", endpointID, featureType, attrID)}
}

func (_c *MockDeviceModel_ReadAttribute_Call) Run(run func(endpointID uint8, featureType model.FeatureType, attrID uint16)) *MockDeviceModel_ReadAttribute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint8
		if args[0] != nil {
			arg0 = args[0].(uint8)
		}
		var arg1 model.FeatureType
		if args[1] != nil {
			arg1 = args[1].(model.FeatureType)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeviceModel_ReadAttribute_Call) Return(v any, err error) *MockDeviceModel_ReadAttribute_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDeviceModel_ReadAttribute_Call) RunAndReturn(run func(endpointID uint8, featureType model.FeatureType, attrID uint16) (any, error)) *MockDeviceModel_ReadAttribute_Call {
	_c.Call.Return(run)
	return _c
}

// RootEndpoint provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) RootEndpoint() *model.Endpoint {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RootEndpoint")
	}

	var r0 *model.Endpoint
	if returnFunc, ok := ret.Get(0).(func() *model.Endpoint); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Endpoint)
		}
	}
	return r0
}

// MockDeviceModel_RootEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RootEndpoint'
type MockDeviceModel_RootEndpoint_Call struct {
	*mock.Call
}

// RootEndpoint is a helper method to define mock.On call
func (_e *MockDeviceModel_Expecter) RootEndpoint() *MockDeviceModel_RootEndpoint_Call {
	return &MockDeviceModel_RootEndpoint_Call{Call: _e.mock.On("RootEndpoint")}
}

func (_c *MockDeviceModel_RootEndpoint_Call) Run(run func()) *MockDeviceModel_RootEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceModel_RootEndpoint_Call) Return(endpoint *model.Endpoint) *MockDeviceModel_RootEndpoint_Call {
	_c.Call.Return(endpoint)
	return _c
}

func (_c *MockDeviceModel_RootEndpoint_Call) RunAndReturn(run func() *model.Endpoint) *MockDeviceModel_RootEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// SerialNumber provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) SerialNumber() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SerialNumber")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDeviceModel_SerialNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SerialNumber'
type MockDeviceModel_SerialNumber_Call struct {
	*mock.Call
}

// SerialNumber is a helper method to define mock.On call
func (_e *MockDeviceModel_Expecter) SerialNumber() *MockDeviceModel_SerialNumber_Call {
	return &MockDeviceModel_SerialNumber_Call{Call: _e.mock.On("SerialNumber")}
}

func (_c *MockDeviceModel_SerialNumber_Call) Run(run func()) *MockDeviceModel_SerialNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceModel_SerialNumber_Call) Return(s string) *MockDeviceModel_SerialNumber_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDeviceModel_SerialNumber_Call) RunAndReturn(run func() string) *MockDeviceModel_SerialNumber_Call {
	_c.Call.Return(run)
	return _c
}

// VendorID provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) VendorID() uint32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for VendorID")
	}

	var r0 uint32
	if returnFunc, ok := ret.Get(0).(func() uint32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint32)
	}
	return r0
}

// MockDeviceModel_VendorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VendorID'
type MockDeviceModel_VendorID_Call struct {
	*mock.Call
}

// VendorID is a helper method to define mock.On call
func (_e *MockDeviceModel_Expecter) VendorID() *MockDeviceModel_VendorID_Call {
	return &MockDeviceModel_VendorID_Call{Call: _e.mock.On("VendorID")}
}

func (_c *MockDeviceModel_VendorID_Call) Run(run func()) *MockDeviceModel_VendorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceModel_VendorID_Call) Return(v uint32) *MockDeviceModel_VendorID_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockDeviceModel_VendorID_Call) RunAndReturn(run func() uint32) *MockDeviceModel_VendorID_Call {
	_c.Call.Return(run)
	return _c
}

// WriteAttribute provides a mock function for the type MockDeviceModel
func (_mock *MockDeviceModel) WriteAttribute(endpointID uint8, featureType model.FeatureType, attrID uint16, value any) error {
	ret := _mock.Called(endpointID, featureType, attrID, value)

	if len(ret) == 0 {
		panic("no return value specified for WriteAttribute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint8, model.FeatureType, uint16, any) error); ok {
		r0 = returnFunc(endpointID, featureType, attrID, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceModel_WriteAttribute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteAttribute'
type MockDeviceModel_WriteAttribute_Call struct {
	*mock.Call
}

// WriteAttribute is a helper method to define mock.On call
//   - endpointID uint8
//   - featureType model.FeatureType
//   - attrID uint16
//   - value any
func (_e *MockDeviceModel_Expecter) WriteAttribute(endpointID interface{}, featureType interface{}, attrID interface{}, value interface{}) *MockDeviceModel_WriteAttribute_Call {
	return &MockDeviceModel_WriteAttribute_Call{Call: _e.mock.On("WriteAttribute", endpointID, featureType, attrID, value)}
}

func (_c *MockDeviceModel_WriteAttribute_Call) Run(run func(endpointID uint8, featureType model.FeatureType, attrID uint16, value any)) *MockDeviceModel_WriteAttribute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint8
		if args[0] != nil {
			arg0 = args[0].(uint8)
		}
		var arg1 model.FeatureType
		if args[1] != nil {
			arg1 = args[1].(model.FeatureType)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDeviceModel_WriteAttribute_Call) Return(err error) *MockDeviceModel_WriteAttribute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceModel_WriteAttribute_Call) RunAndReturn(run func(endpointID uint8, featureType model.FeatureType, attrID uint16, value any) error) *MockDeviceModel_WriteAttribute_Call {
	_c.Call.Return(run)
	return _c
}
