// Code generated by mash-featgen. DO NOT EDIT.

package inspect

import (
	"github.com/mash-protocol/mash-go/pkg/features"
	"github.com/mash-protocol/mash-go/pkg/model"
)

// generatedEndpointNames returns the endpoint name lookup table.
func generatedEndpointNames() map[string]uint8 {
	return map[string]uint8{
		"deviceroot":     uint8(model.EndpointDeviceRoot),
		"gridconnection": uint8(model.EndpointGridConnection),
		"inverter":       uint8(model.EndpointInverter),
		"pvstring":       uint8(model.EndpointPVString),
		"battery":        uint8(model.EndpointBattery),
		"evcharger":      uint8(model.EndpointEVCharger),
		"heatpump":       uint8(model.EndpointHeatPump),
		"waterheater":    uint8(model.EndpointWaterHeater),
		"hvac":           uint8(model.EndpointHVAC),
		"appliance":      uint8(model.EndpointAppliance),
		"submeter":       uint8(model.EndpointSubMeter),
	}
}

// generatedFeatureNames returns the feature name lookup table.
func generatedFeatureNames() map[string]uint8 {
	return map[string]uint8{
		"deviceinfo":      uint8(model.FeatureDeviceInfo),
		"status":          uint8(model.FeatureStatus),
		"electrical":      uint8(model.FeatureElectrical),
		"measurement":     uint8(model.FeatureMeasurement),
		"energycontrol":   uint8(model.FeatureEnergyControl),
		"chargingsession": uint8(model.FeatureChargingSession),
		"tariff":          uint8(model.FeatureTariff),
		"signals":         uint8(model.FeatureSignals),
		"plan":            uint8(model.FeaturePlan),
		"testcontrol":     uint8(model.FeatureTestControl),
	}
}

// initGeneratedNameTables populates the attribute and command name tables.
func initGeneratedNameTables() {
	globalAttrs := map[string]uint16{
		"featureMap":    model.AttrIDFeatureMap,
		"attributeList": model.AttrIDAttributeList,
		"commandList":   model.AttrIDCommandList,
	}

	electricalAttrs := map[string]uint16{
		"phaseCount":            features.ElectricalAttrPhaseCount,
		"phaseMapping":          features.ElectricalAttrPhaseMapping,
		"nominalVoltage":        features.ElectricalAttrNominalVoltage,
		"nominalFrequency":      features.ElectricalAttrNominalFrequency,
		"supportedDirections":   features.ElectricalAttrSupportedDirections,
		"nominalMaxConsumption": features.ElectricalAttrNominalMaxConsumption,
		"nominalMaxProduction":  features.ElectricalAttrNominalMaxProduction,
		"nominalMinPower":       features.ElectricalAttrNominalMinPower,
		"maxCurrentPerPhase":    features.ElectricalAttrMaxCurrentPerPhase,
		"minCurrentPerPhase":    features.ElectricalAttrMinCurrentPerPhase,
		"supportsAsymmetric":    features.ElectricalAttrSupportsAsymmetric,
		"energyCapacity":        features.ElectricalAttrEnergyCapacity,
	}
	for k, v := range globalAttrs {
		electricalAttrs[k] = v
	}
	attributeNames[uint8(model.FeatureElectrical)] = electricalAttrs

	measurementAttrs := map[string]uint16{
		"acActivePower":             features.MeasurementAttrACActivePower,
		"acReactivePower":           features.MeasurementAttrACReactivePower,
		"acApparentPower":           features.MeasurementAttrACApparentPower,
		"acActivePowerPerPhase":     features.MeasurementAttrACActivePowerPerPhase,
		"acReactivePowerPerPhase":   features.MeasurementAttrACReactivePowerPerPhase,
		"acApparentPowerPerPhase":   features.MeasurementAttrACApparentPowerPerPhase,
		"acCurrentPerPhase":         features.MeasurementAttrACCurrentPerPhase,
		"acVoltagePerPhase":         features.MeasurementAttrACVoltagePerPhase,
		"acVoltagePhaseToPhasePair": features.MeasurementAttrACVoltagePhaseToPhasePair,
		"acFrequency":               features.MeasurementAttrACFrequency,
		"powerFactor":               features.MeasurementAttrPowerFactor,
		"acEnergyConsumed":          features.MeasurementAttrACEnergyConsumed,
		"acEnergyProduced":          features.MeasurementAttrACEnergyProduced,
		"dcPower":                   features.MeasurementAttrDCPower,
		"dcCurrent":                 features.MeasurementAttrDCCurrent,
		"dcVoltage":                 features.MeasurementAttrDCVoltage,
		"dcEnergyIn":                features.MeasurementAttrDCEnergyIn,
		"dcEnergyOut":               features.MeasurementAttrDCEnergyOut,
		"stateOfCharge":             features.MeasurementAttrStateOfCharge,
		"stateOfHealth":             features.MeasurementAttrStateOfHealth,
		"stateOfEnergy":             features.MeasurementAttrStateOfEnergy,
		"useableCapacity":           features.MeasurementAttrUseableCapacity,
		"cycleCount":                features.MeasurementAttrCycleCount,
		"temperature":               features.MeasurementAttrTemperature,
	}
	for k, v := range globalAttrs {
		measurementAttrs[k] = v
	}
	attributeNames[uint8(model.FeatureMeasurement)] = measurementAttrs

	tariffAttrs := map[string]uint16{
		"tariffId":          features.TariffAttrTariffID,
		"currency":          features.TariffAttrCurrency,
		"priceUnit":         features.TariffAttrPriceUnit,
		"tariffDescription": features.TariffAttrTariffDescription,
	}
	for k, v := range globalAttrs {
		tariffAttrs[k] = v
	}
	attributeNames[uint8(model.FeatureTariff)] = tariffAttrs

	signalsAttrs := map[string]uint16{
		"signalSource":    features.SignalsAttrSignalSource,
		"startTime":       features.SignalsAttrStartTime,
		"validUntil":      features.SignalsAttrValidUntil,
		"priceSlots":      features.SignalsAttrPriceSlots,
		"constraintSlots": features.SignalsAttrConstraintSlots,
		"forecastSlots":   features.SignalsAttrForecastSlots,
	}
	for k, v := range globalAttrs {
		signalsAttrs[k] = v
	}
	attributeNames[uint8(model.FeatureSignals)] = signalsAttrs

	planAttrs := map[string]uint16{
		"planId":             features.PlanAttrPlanID,
		"planVersion":        features.PlanAttrPlanVersion,
		"commitment":         features.PlanAttrCommitment,
		"startTime":          features.PlanAttrStartTime,
		"endTime":            features.PlanAttrEndTime,
		"totalEnergyPlanned": features.PlanAttrTotalEnergyPlanned,
		"slots":              features.PlanAttrSlots,
	}
	for k, v := range globalAttrs {
		planAttrs[k] = v
	}
	attributeNames[uint8(model.FeaturePlan)] = planAttrs

	testControlAttrs := map[string]uint16{
		"testEventTriggersEnabled": features.TestControlAttrTestEventTriggersEnabled,
	}
	for k, v := range globalAttrs {
		testControlAttrs[k] = v
	}
	attributeNames[uint8(model.FeatureTestControl)] = testControlAttrs

	deviceInfoAttrs := map[string]uint16{
		"deviceId":        features.DeviceInfoAttrDeviceID,
		"vendorName":      features.DeviceInfoAttrVendorName,
		"productName":     features.DeviceInfoAttrProductName,
		"serialNumber":    features.DeviceInfoAttrSerialNumber,
		"vendorId":        features.DeviceInfoAttrVendorID,
		"productId":       features.DeviceInfoAttrProductID,
		"softwareVersion": features.DeviceInfoAttrSoftwareVersion,
		"hardwareVersion": features.DeviceInfoAttrHardwareVersion,
		"specVersion":     features.DeviceInfoAttrSpecVersion,
		"endpoints":       features.DeviceInfoAttrEndpoints,
		"useCases":        features.DeviceInfoAttrUseCases,
		"location":        features.DeviceInfoAttrLocation,
		"label":           features.DeviceInfoAttrLabel,
		"zoneCount":       features.DeviceInfoAttrZoneCount,
	}
	for k, v := range globalAttrs {
		deviceInfoAttrs[k] = v
	}
	attributeNames[uint8(model.FeatureDeviceInfo)] = deviceInfoAttrs

	energyControlAttrs := map[string]uint16{
		"deviceType":                           features.EnergyControlAttrDeviceType,
		"controlState":                         features.EnergyControlAttrControlState,
		"optOutState":                          features.EnergyControlAttrOptOutState,
		"acceptsLimits":                        features.EnergyControlAttrAcceptsLimits,
		"acceptsCurrentLimits":                 features.EnergyControlAttrAcceptsCurrentLimits,
		"acceptsSetpoints":                     features.EnergyControlAttrAcceptsSetpoints,
		"acceptsCurrentSetpoints":              features.EnergyControlAttrAcceptsCurrentSetpoints,
		"isPausable":                           features.EnergyControlAttrIsPausable,
		"isShiftable":                          features.EnergyControlAttrIsShiftable,
		"isStoppable":                          features.EnergyControlAttrIsStoppable,
		"effectiveConsumptionLimit":            features.EnergyControlAttrEffectiveConsumptionLimit,
		"myConsumptionLimit":                   features.EnergyControlAttrMyConsumptionLimit,
		"effectiveProductionLimit":             features.EnergyControlAttrEffectiveProductionLimit,
		"myProductionLimit":                    features.EnergyControlAttrMyProductionLimit,
		"effectiveCurrentLimitsConsumption":    features.EnergyControlAttrEffectiveCurrentLimitsConsumption,
		"myCurrentLimitsConsumption":           features.EnergyControlAttrMyCurrentLimitsConsumption,
		"effectiveCurrentLimitsProduction":     features.EnergyControlAttrEffectiveCurrentLimitsProduction,
		"myCurrentLimitsProduction":            features.EnergyControlAttrMyCurrentLimitsProduction,
		"effectiveConsumptionSetpoint":         features.EnergyControlAttrEffectiveConsumptionSetpoint,
		"myConsumptionSetpoint":                features.EnergyControlAttrMyConsumptionSetpoint,
		"effectiveProductionSetpoint":          features.EnergyControlAttrEffectiveProductionSetpoint,
		"myProductionSetpoint":                 features.EnergyControlAttrMyProductionSetpoint,
		"effectiveCurrentSetpointsConsumption": features.EnergyControlAttrEffectiveCurrentSetpointsConsumption,
		"myCurrentSetpointsConsumption":        features.EnergyControlAttrMyCurrentSetpointsConsumption,
		"effectiveCurrentSetpointsProduction":  features.EnergyControlAttrEffectiveCurrentSetpointsProduction,
		"myCurrentSetpointsProduction":         features.EnergyControlAttrMyCurrentSetpointsProduction,
		"failsafeConsumptionLimit":             features.EnergyControlAttrFailsafeConsumptionLimit,
		"failsafeProductionLimit":              features.EnergyControlAttrFailsafeProductionLimit,
		"failsafeDuration":                     features.EnergyControlAttrFailsafeDuration,
		"contractualConsumptionMax":            features.EnergyControlAttrContractualConsumptionMax,
		"contractualProductionMax":             features.EnergyControlAttrContractualProductionMax,
		"overrideReason":                       features.EnergyControlAttrOverrideReason,
		"overrideDirection":                    features.EnergyControlAttrOverrideDirection,
		"processState":                         features.EnergyControlAttrProcessState,
		"optionalProcess":                      features.EnergyControlAttrOptionalProcess,
		"minRunDuration":                       features.EnergyControlAttrMinRunDuration,
		"minPauseDuration":                     features.EnergyControlAttrMinPauseDuration,
		"maxRunDuration":                       features.EnergyControlAttrMaxRunDuration,
		"maxPauseDuration":                     features.EnergyControlAttrMaxPauseDuration,
		"optionalProcessPower":                 features.EnergyControlAttrOptionalProcessPower,
		"controlMode":                          features.EnergyControlAttrControlMode,
	}
	for k, v := range globalAttrs {
		energyControlAttrs[k] = v
	}
	attributeNames[uint8(model.FeatureEnergyControl)] = energyControlAttrs

	chargingSessionAttrs := map[string]uint16{
		"state":                           features.ChargingSessionAttrState,
		"sessionStartTime":                features.ChargingSessionAttrSessionStartTime,
		"sessionEndTime":                  features.ChargingSessionAttrSessionEndTime,
		"sessionEnergyCharged":            features.ChargingSessionAttrSessionEnergyCharged,
		"sessionEnergyDischarged":         features.ChargingSessionAttrSessionEnergyDischarged,
		"evIdentifications":               features.ChargingSessionAttrEVIdentifications,
		"evStateOfCharge":                 features.ChargingSessionAttrEVStateOfCharge,
		"evBatteryCapacity":               features.ChargingSessionAttrEVBatteryCapacity,
		"evMinStateOfCharge":              features.ChargingSessionAttrEVMinStateOfCharge,
		"evTargetStateOfCharge":           features.ChargingSessionAttrEVTargetStateOfCharge,
		"evDemandMode":                    features.ChargingSessionAttrEVDemandMode,
		"evMinEnergyRequest":              features.ChargingSessionAttrEVMinEnergyRequest,
		"evMaxEnergyRequest":              features.ChargingSessionAttrEVMaxEnergyRequest,
		"evTargetEnergyRequest":           features.ChargingSessionAttrEVTargetEnergyRequest,
		"evDepartureTime":                 features.ChargingSessionAttrEVDepartureTime,
		"evMinDischargingRequest":         features.ChargingSessionAttrEVMinDischargingRequest,
		"evMaxDischargingRequest":         features.ChargingSessionAttrEVMaxDischargingRequest,
		"evDischargeBelowTargetPermitted": features.ChargingSessionAttrEVDischargeBelowTargetPermitted,
		"estimatedTimeToMinSoC":           features.ChargingSessionAttrEstimatedTimeToMinSoC,
		"estimatedTimeToTargetSoC":        features.ChargingSessionAttrEstimatedTimeToTargetSoC,
		"estimatedTimeToFullSoC":          features.ChargingSessionAttrEstimatedTimeToFullSoC,
		"chargingMode":                    features.ChargingSessionAttrChargingMode,
		"supportedChargingModes":          features.ChargingSessionAttrSupportedChargingModes,
		"surplusThreshold":                features.ChargingSessionAttrSurplusThreshold,
		"startDelay":                      features.ChargingSessionAttrStartDelay,
		"stopDelay":                       features.ChargingSessionAttrStopDelay,
	}
	for k, v := range globalAttrs {
		chargingSessionAttrs[k] = v
	}
	attributeNames[uint8(model.FeatureChargingSession)] = chargingSessionAttrs

	statusAttrs := map[string]uint16{
		"operatingState": features.StatusAttrOperatingState,
		"stateDetail":    features.StatusAttrStateDetail,
		"faultCode":      features.StatusAttrFaultCode,
		"faultMessage":   features.StatusAttrFaultMessage,
	}
	for k, v := range globalAttrs {
		statusAttrs[k] = v
	}
	attributeNames[uint8(model.FeatureStatus)] = statusAttrs

	commandNames[uint8(model.FeatureTariff)] = map[string]uint8{
		"setTariff": features.TariffCmdSetTariff,
	}

	commandNames[uint8(model.FeatureSignals)] = map[string]uint8{
		"sendPriceSignal":      features.SignalsCmdSendPriceSignal,
		"sendConstraintSignal": features.SignalsCmdSendConstraintSignal,
		"sendForecastSignal":   features.SignalsCmdSendForecastSignal,
		"clearSignals":         features.SignalsCmdClearSignals,
	}

	commandNames[uint8(model.FeaturePlan)] = map[string]uint8{
		"requestPlan": features.PlanCmdRequestPlan,
		"acceptPlan":  features.PlanCmdAcceptPlan,
	}

	commandNames[uint8(model.FeatureTestControl)] = map[string]uint8{
		"triggerTestEvent":               features.TestControlCmdTriggerTestEvent,
		"setCommissioningWindowDuration": features.TestControlCmdSetCommissioningWindowDuration,
	}

	commandNames[uint8(model.FeatureDeviceInfo)] = map[string]uint8{
		"removeZone": features.DeviceInfoCmdRemoveZone,
	}

	commandNames[uint8(model.FeatureEnergyControl)] = map[string]uint8{
		"setLimit":              features.EnergyControlCmdSetLimit,
		"clearLimit":            features.EnergyControlCmdClearLimit,
		"setCurrentLimits":      features.EnergyControlCmdSetCurrentLimits,
		"clearCurrentLimits":    features.EnergyControlCmdClearCurrentLimits,
		"setSetpoint":           features.EnergyControlCmdSetSetpoint,
		"clearSetpoint":         features.EnergyControlCmdClearSetpoint,
		"setCurrentSetpoints":   features.EnergyControlCmdSetCurrentSetpoints,
		"clearCurrentSetpoints": features.EnergyControlCmdClearCurrentSetpoints,
		"pause":                 features.EnergyControlCmdPause,
		"resume":                features.EnergyControlCmdResume,
		"stop":                  features.EnergyControlCmdStop,
	}

	commandNames[uint8(model.FeatureChargingSession)] = map[string]uint8{
		"setChargingMode": features.ChargingSessionCmdSetChargingMode,
	}

}
