structname: Mock{{.InterfaceName}}
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/mash-protocol/mash-go/internal/testharness/runner:
    config:
      dir: '{{.InterfaceDir}}/mocks'
    interfaces:
      SuiteSession: {}
      ConnPool: {}
      ConnReader: {}
      ConnWriter: {}
      ConnLifecycle: {}
      RequestSender: {}
      NotificationBuffer: {}
      CommissioningOps: {}
      StateAccessor: {}
      LifecycleOps: {}
      WireOps: {}
      DiagnosticsOps: {}
      PreconditionHandler: {}
      Coordinator: {}
      ConnectionManager: {}
      Dialer: {}
  github.com/mash-protocol/mash-go/pkg/service:
    config:
      dir: '{{.InterfaceDir}}/mocks'
    interfaces:
      SubscriptionTracker: {}
      DeviceModel: {}
