structname: Mock{{.InterfaceName}}
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/mash-protocol/mash-go/internal/testharness/runner:
    config:
      dir: '{{.InterfaceDir}}/mocks'
    interfaces:
      SuiteSession: {}
      ConnPool: {}
      CommissioningOps: {}
      Coordinator: {}
