// Package cert provides X.509 certificate management for MASH.
//
// MASH uses a two-tier certificate hierarchy:
//
//  1. Zone CA - Generated by zone owners (controllers), used to sign operational certificates.
//     Validity: 10 years. Stored securely on the zone owner.
//
//  2. Operational Certificate - Issued to devices during commissioning.
//     Validity: 1 year, auto-renewed. Proves zone membership.
//
// Additionally, devices may have a Device Attestation Certificate (pre-installed at
// manufacturing) to prove manufacturer identity, but this is optional.
//
// Key operations:
//   - Zone owners generate a Zone CA using [GenerateZoneCA]
//   - Devices generate key pairs and CSRs using [GenerateKeyPair] and [CreateCSR]
//   - Zone owners sign CSRs using [SignCSR] to issue operational certificates
//   - Certificates are stored using the [Store] interface
//
// Certificate identification uses the Subject Key Identifier (SKI), which is
// derived from the public key and serves as the device's unique identifier
// within MASH.
package cert
