// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	net "net"

	mock "github.com/stretchr/testify/mock"

	tls "crypto/tls"
)

// MockServerConnection is an autogenerated mock type for the ServerConnection type
type MockServerConnection struct {
	mock.Mock
}

type MockServerConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerConnection) EXPECT() *MockServerConnection_Expecter {
	return &MockServerConnection_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockServerConnection) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerConnection_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockServerConnection_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockServerConnection_Expecter) Close() *MockServerConnection_Close_Call {
	return &MockServerConnection_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockServerConnection_Close_Call) Run(run func()) *MockServerConnection_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerConnection_Close_Call) Return(_a0 error) *MockServerConnection_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerConnection_Close_Call) RunAndReturn(run func() error) *MockServerConnection_Close_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteAddr provides a mock function with no fields
func (_m *MockServerConnection) RemoteAddr() net.Addr {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteAddr")
	}

	var r0 net.Addr
	if rf, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}

	return r0
}

// MockServerConnection_RemoteAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteAddr'
type MockServerConnection_RemoteAddr_Call struct {
	*mock.Call
}

// RemoteAddr is a helper method to define mock.On call
func (_e *MockServerConnection_Expecter) RemoteAddr() *MockServerConnection_RemoteAddr_Call {
	return &MockServerConnection_RemoteAddr_Call{Call: _e.mock.On("RemoteAddr")}
}

func (_c *MockServerConnection_RemoteAddr_Call) Run(run func()) *MockServerConnection_RemoteAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerConnection_RemoteAddr_Call) Return(_a0 net.Addr) *MockServerConnection_RemoteAddr_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerConnection_RemoteAddr_Call) RunAndReturn(run func() net.Addr) *MockServerConnection_RemoteAddr_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: data
func (_m *MockServerConnection) Send(data []byte) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerConnection_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockServerConnection_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - data []byte
func (_e *MockServerConnection_Expecter) Send(data interface{}) *MockServerConnection_Send_Call {
	return &MockServerConnection_Send_Call{Call: _e.mock.On("Send", data)}
}

func (_c *MockServerConnection_Send_Call) Run(run func(data []byte)) *MockServerConnection_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockServerConnection_Send_Call) Return(_a0 error) *MockServerConnection_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerConnection_Send_Call) RunAndReturn(run func([]byte) error) *MockServerConnection_Send_Call {
	_c.Call.Return(run)
	return _c
}

// TLSState provides a mock function with no fields
func (_m *MockServerConnection) TLSState() tls.ConnectionState {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TLSState")
	}

	var r0 tls.ConnectionState
	if rf, ok := ret.Get(0).(func() tls.ConnectionState); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(tls.ConnectionState)
	}

	return r0
}

// MockServerConnection_TLSState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TLSState'
type MockServerConnection_TLSState_Call struct {
	*mock.Call
}

// TLSState is a helper method to define mock.On call
func (_e *MockServerConnection_Expecter) TLSState() *MockServerConnection_TLSState_Call {
	return &MockServerConnection_TLSState_Call{Call: _e.mock.On("TLSState")}
}

func (_c *MockServerConnection_TLSState_Call) Run(run func()) *MockServerConnection_TLSState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerConnection_TLSState_Call) Return(_a0 tls.ConnectionState) *MockServerConnection_TLSState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerConnection_TLSState_Call) RunAndReturn(run func() tls.ConnectionState) *MockServerConnection_TLSState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerConnection creates a new instance of MockServerConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerConnection {
	mock := &MockServerConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
