// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockFrameReadWriter is an autogenerated mock type for the FrameReadWriter type
type MockFrameReadWriter struct {
	mock.Mock
}

type MockFrameReadWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFrameReadWriter) EXPECT() *MockFrameReadWriter_Expecter {
	return &MockFrameReadWriter_Expecter{mock: &_m.Mock}
}

// ReadFrame provides a mock function with no fields
func (_m *MockFrameReadWriter) ReadFrame() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadFrame")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFrameReadWriter_ReadFrame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFrame'
type MockFrameReadWriter_ReadFrame_Call struct {
	*mock.Call
}

// ReadFrame is a helper method to define mock.On call
func (_e *MockFrameReadWriter_Expecter) ReadFrame() *MockFrameReadWriter_ReadFrame_Call {
	return &MockFrameReadWriter_ReadFrame_Call{Call: _e.mock.On("ReadFrame")}
}

func (_c *MockFrameReadWriter_ReadFrame_Call) Run(run func()) *MockFrameReadWriter_ReadFrame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFrameReadWriter_ReadFrame_Call) Return(_a0 []byte, _a1 error) *MockFrameReadWriter_ReadFrame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFrameReadWriter_ReadFrame_Call) RunAndReturn(run func() ([]byte, error)) *MockFrameReadWriter_ReadFrame_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFrame provides a mock function with given fields: data
func (_m *MockFrameReadWriter) WriteFrame(data []byte) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for WriteFrame")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFrameReadWriter_WriteFrame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFrame'
type MockFrameReadWriter_WriteFrame_Call struct {
	*mock.Call
}

// WriteFrame is a helper method to define mock.On call
//   - data []byte
func (_e *MockFrameReadWriter_Expecter) WriteFrame(data interface{}) *MockFrameReadWriter_WriteFrame_Call {
	return &MockFrameReadWriter_WriteFrame_Call{Call: _e.mock.On("WriteFrame", data)}
}

func (_c *MockFrameReadWriter_WriteFrame_Call) Run(run func(data []byte)) *MockFrameReadWriter_WriteFrame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockFrameReadWriter_WriteFrame_Call) Return(_a0 error) *MockFrameReadWriter_WriteFrame_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFrameReadWriter_WriteFrame_Call) RunAndReturn(run func([]byte) error) *MockFrameReadWriter_WriteFrame_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFrameReadWriter creates a new instance of MockFrameReadWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFrameReadWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFrameReadWriter {
	mock := &MockFrameReadWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
