// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	net "net"

	mock "github.com/stretchr/testify/mock"

	time "time"

	tls "crypto/tls"
)

// MockClientConnection is an autogenerated mock type for the ClientConnection type
type MockClientConnection struct {
	mock.Mock
}

type MockClientConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientConnection) EXPECT() *MockClientConnection_Expecter {
	return &MockClientConnection_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockClientConnection) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientConnection_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClientConnection_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClientConnection_Expecter) Close() *MockClientConnection_Close_Call {
	return &MockClientConnection_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClientConnection_Close_Call) Run(run func()) *MockClientConnection_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientConnection_Close_Call) Return(_a0 error) *MockClientConnection_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientConnection_Close_Call) RunAndReturn(run func() error) *MockClientConnection_Close_Call {
	_c.Call.Return(run)
	return _c
}

// LocalAddr provides a mock function with no fields
func (_m *MockClientConnection) LocalAddr() net.Addr {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LocalAddr")
	}

	var r0 net.Addr
	if rf, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}

	return r0
}

// MockClientConnection_LocalAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalAddr'
type MockClientConnection_LocalAddr_Call struct {
	*mock.Call
}

// LocalAddr is a helper method to define mock.On call
func (_e *MockClientConnection_Expecter) LocalAddr() *MockClientConnection_LocalAddr_Call {
	return &MockClientConnection_LocalAddr_Call{Call: _e.mock.On("LocalAddr")}
}

func (_c *MockClientConnection_LocalAddr_Call) Run(run func()) *MockClientConnection_LocalAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientConnection_LocalAddr_Call) Return(_a0 net.Addr) *MockClientConnection_LocalAddr_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientConnection_LocalAddr_Call) RunAndReturn(run func() net.Addr) *MockClientConnection_LocalAddr_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function with given fields: timeout
func (_m *MockClientConnection) Receive(timeout time.Duration) ([]byte, error) {
	ret := _m.Called(timeout)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Duration) ([]byte, error)); ok {
		return rf(timeout)
	}
	if rf, ok := ret.Get(0).(func(time.Duration) []byte); ok {
		r0 = rf(timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Duration) error); ok {
		r1 = rf(timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientConnection_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type MockClientConnection_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - timeout time.Duration
func (_e *MockClientConnection_Expecter) Receive(timeout interface{}) *MockClientConnection_Receive_Call {
	return &MockClientConnection_Receive_Call{Call: _e.mock.On("Receive", timeout)}
}

func (_c *MockClientConnection_Receive_Call) Run(run func(timeout time.Duration)) *MockClientConnection_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *MockClientConnection_Receive_Call) Return(_a0 []byte, _a1 error) *MockClientConnection_Receive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientConnection_Receive_Call) RunAndReturn(run func(time.Duration) ([]byte, error)) *MockClientConnection_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteAddr provides a mock function with no fields
func (_m *MockClientConnection) RemoteAddr() net.Addr {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteAddr")
	}

	var r0 net.Addr
	if rf, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}

	return r0
}

// MockClientConnection_RemoteAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteAddr'
type MockClientConnection_RemoteAddr_Call struct {
	*mock.Call
}

// RemoteAddr is a helper method to define mock.On call
func (_e *MockClientConnection_Expecter) RemoteAddr() *MockClientConnection_RemoteAddr_Call {
	return &MockClientConnection_RemoteAddr_Call{Call: _e.mock.On("RemoteAddr")}
}

func (_c *MockClientConnection_RemoteAddr_Call) Run(run func()) *MockClientConnection_RemoteAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientConnection_RemoteAddr_Call) Return(_a0 net.Addr) *MockClientConnection_RemoteAddr_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientConnection_RemoteAddr_Call) RunAndReturn(run func() net.Addr) *MockClientConnection_RemoteAddr_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: data
func (_m *MockClientConnection) Send(data []byte) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientConnection_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockClientConnection_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - data []byte
func (_e *MockClientConnection_Expecter) Send(data interface{}) *MockClientConnection_Send_Call {
	return &MockClientConnection_Send_Call{Call: _e.mock.On("Send", data)}
}

func (_c *MockClientConnection_Send_Call) Run(run func(data []byte)) *MockClientConnection_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockClientConnection_Send_Call) Return(_a0 error) *MockClientConnection_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientConnection_Send_Call) RunAndReturn(run func([]byte) error) *MockClientConnection_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendClose provides a mock function with no fields
func (_m *MockClientConnection) SendClose() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendClose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientConnection_SendClose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendClose'
type MockClientConnection_SendClose_Call struct {
	*mock.Call
}

// SendClose is a helper method to define mock.On call
func (_e *MockClientConnection_Expecter) SendClose() *MockClientConnection_SendClose_Call {
	return &MockClientConnection_SendClose_Call{Call: _e.mock.On("SendClose")}
}

func (_c *MockClientConnection_SendClose_Call) Run(run func()) *MockClientConnection_SendClose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientConnection_SendClose_Call) Return(_a0 error) *MockClientConnection_SendClose_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientConnection_SendClose_Call) RunAndReturn(run func() error) *MockClientConnection_SendClose_Call {
	_c.Call.Return(run)
	return _c
}

// SendPing provides a mock function with given fields: seq
func (_m *MockClientConnection) SendPing(seq uint32) error {
	ret := _m.Called(seq)

	if len(ret) == 0 {
		panic("no return value specified for SendPing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint32) error); ok {
		r0 = rf(seq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientConnection_SendPing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPing'
type MockClientConnection_SendPing_Call struct {
	*mock.Call
}

// SendPing is a helper method to define mock.On call
//   - seq uint32
func (_e *MockClientConnection_Expecter) SendPing(seq interface{}) *MockClientConnection_SendPing_Call {
	return &MockClientConnection_SendPing_Call{Call: _e.mock.On("SendPing", seq)}
}

func (_c *MockClientConnection_SendPing_Call) Run(run func(seq uint32)) *MockClientConnection_SendPing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint32))
	})
	return _c
}

func (_c *MockClientConnection_SendPing_Call) Return(_a0 error) *MockClientConnection_SendPing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientConnection_SendPing_Call) RunAndReturn(run func(uint32) error) *MockClientConnection_SendPing_Call {
	_c.Call.Return(run)
	return _c
}

// TLSState provides a mock function with no fields
func (_m *MockClientConnection) TLSState() tls.ConnectionState {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TLSState")
	}

	var r0 tls.ConnectionState
	if rf, ok := ret.Get(0).(func() tls.ConnectionState); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(tls.ConnectionState)
	}

	return r0
}

// MockClientConnection_TLSState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TLSState'
type MockClientConnection_TLSState_Call struct {
	*mock.Call
}

// TLSState is a helper method to define mock.On call
func (_e *MockClientConnection_Expecter) TLSState() *MockClientConnection_TLSState_Call {
	return &MockClientConnection_TLSState_Call{Call: _e.mock.On("TLSState")}
}

func (_c *MockClientConnection_TLSState_Call) Run(run func()) *MockClientConnection_TLSState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientConnection_TLSState_Call) Return(_a0 tls.ConnectionState) *MockClientConnection_TLSState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientConnection_TLSState_Call) RunAndReturn(run func() tls.ConnectionState) *MockClientConnection_TLSState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientConnection creates a new instance of MockClientConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientConnection {
	mock := &MockClientConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
