// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runner

import (
	"context"

	"github.com/mash-protocol/mash-go/internal/testharness/engine"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWireOps creates a new instance of MockWireOps. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWireOps(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWireOps {
	mock := &MockWireOps{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWireOps is an autogenerated mock type for the WireOps type
type MockWireOps struct {
	mock.Mock
}

type MockWireOps_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWireOps) EXPECT() *MockWireOps_Expecter {
	return &MockWireOps_Expecter{mock: &_m.Mock}
}

// SendClearLimitInvoke provides a mock function for the type MockWireOps
func (_mock *MockWireOps) SendClearLimitInvoke(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SendClearLimitInvoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWireOps_SendClearLimitInvoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendClearLimitInvoke'
type MockWireOps_SendClearLimitInvoke_Call struct {
	*mock.Call
}

// SendClearLimitInvoke is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWireOps_Expecter) SendClearLimitInvoke(ctx interface{}) *MockWireOps_SendClearLimitInvoke_Call {
	return &MockWireOps_SendClearLimitInvoke_Call{Call: _e.mock.On("SendClearLimitInvoke", ctx)}
}

func (_c *MockWireOps_SendClearLimitInvoke_Call) Run(run func(ctx context.Context)) *MockWireOps_SendClearLimitInvoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWireOps_SendClearLimitInvoke_Call) Return(err error) *MockWireOps_SendClearLimitInvoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWireOps_SendClearLimitInvoke_Call) RunAndReturn(run func(ctx context.Context) error) *MockWireOps_SendClearLimitInvoke_Call {
	_c.Call.Return(run)
	return _c
}

// SendRemoveZone provides a mock function for the type MockWireOps
func (_mock *MockWireOps) SendRemoveZone() {
	_mock.Called()
	return
}

// MockWireOps_SendRemoveZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRemoveZone'
type MockWireOps_SendRemoveZone_Call struct {
	*mock.Call
}

// SendRemoveZone is a helper method to define mock.On call
func (_e *MockWireOps_Expecter) SendRemoveZone() *MockWireOps_SendRemoveZone_Call {
	return &MockWireOps_SendRemoveZone_Call{Call: _e.mock.On("SendRemoveZone")}
}

func (_c *MockWireOps_SendRemoveZone_Call) Run(run func()) *MockWireOps_SendRemoveZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWireOps_SendRemoveZone_Call) Return() *MockWireOps_SendRemoveZone_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWireOps_SendRemoveZone_Call) RunAndReturn(run func()) *MockWireOps_SendRemoveZone_Call {
	_c.Run(run)
	return _c
}

// SendRemoveZoneOnConn provides a mock function for the type MockWireOps
func (_mock *MockWireOps) SendRemoveZoneOnConn(conn *Connection, zoneID string) {
	_mock.Called(conn, zoneID)
	return
}

// MockWireOps_SendRemoveZoneOnConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRemoveZoneOnConn'
type MockWireOps_SendRemoveZoneOnConn_Call struct {
	*mock.Call
}

// SendRemoveZoneOnConn is a helper method to define mock.On call
//   - conn *Connection
//   - zoneID string
func (_e *MockWireOps_Expecter) SendRemoveZoneOnConn(conn interface{}, zoneID interface{}) *MockWireOps_SendRemoveZoneOnConn_Call {
	return &MockWireOps_SendRemoveZoneOnConn_Call{Call: _e.mock.On("SendRemoveZoneOnConn", conn, zoneID)}
}

func (_c *MockWireOps_SendRemoveZoneOnConn_Call) Run(run func(conn *Connection, zoneID string)) *MockWireOps_SendRemoveZoneOnConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Connection
		if args[0] != nil {
			arg0 = args[0].(*Connection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWireOps_SendRemoveZoneOnConn_Call) Return() *MockWireOps_SendRemoveZoneOnConn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWireOps_SendRemoveZoneOnConn_Call) RunAndReturn(run func(conn *Connection, zoneID string)) *MockWireOps_SendRemoveZoneOnConn_Call {
	_c.Run(run)
	return _c
}

// SendTriggerViaZone provides a mock function for the type MockWireOps
func (_mock *MockWireOps) SendTriggerViaZone(ctx context.Context, trigger uint64, state *engine.ExecutionState) error {
	ret := _mock.Called(ctx, trigger, state)

	if len(ret) == 0 {
		panic("no return value specified for SendTriggerViaZone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *engine.ExecutionState) error); ok {
		r0 = returnFunc(ctx, trigger, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWireOps_SendTriggerViaZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTriggerViaZone'
type MockWireOps_SendTriggerViaZone_Call struct {
	*mock.Call
}

// SendTriggerViaZone is a helper method to define mock.On call
//   - ctx context.Context
//   - trigger uint64
//   - state *engine.ExecutionState
func (_e *MockWireOps_Expecter) SendTriggerViaZone(ctx interface{}, trigger interface{}, state interface{}) *MockWireOps_SendTriggerViaZone_Call {
	return &MockWireOps_SendTriggerViaZone_Call{Call: _e.mock.On("SendTriggerViaZone", ctx, trigger, state)}
}

func (_c *MockWireOps_SendTriggerViaZone_Call) Run(run func(ctx context.Context, trigger uint64, state *engine.ExecutionState)) *MockWireOps_SendTriggerViaZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *engine.ExecutionState
		if args[2] != nil {
			arg2 = args[2].(*engine.ExecutionState)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWireOps_SendTriggerViaZone_Call) Return(err error) *MockWireOps_SendTriggerViaZone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWireOps_SendTriggerViaZone_Call) RunAndReturn(run func(ctx context.Context, trigger uint64, state *engine.ExecutionState) error) *MockWireOps_SendTriggerViaZone_Call {
	_c.Call.Return(run)
	return _c
}
