// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runner

import (
	"context"
	"time"

	"github.com/mash-protocol/mash-go/internal/testharness/engine"
	"github.com/mash-protocol/mash-go/internal/testharness/loader"
	"github.com/mash-protocol/mash-go/pkg/cert"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommissioningOps creates a new instance of MockCommissioningOps. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommissioningOps(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommissioningOps {
	mock := &MockCommissioningOps{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommissioningOps is an autogenerated mock type for the CommissioningOps type
type MockCommissioningOps struct {
	mock.Mock
}

type MockCommissioningOps_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommissioningOps) EXPECT() *MockCommissioningOps_Expecter {
	return &MockCommissioningOps_Expecter{mock: &_m.Mock}
}

// ClearWorkingCrypto provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) ClearWorkingCrypto() {
	_mock.Called()
	return
}

// MockCommissioningOps_ClearWorkingCrypto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearWorkingCrypto'
type MockCommissioningOps_ClearWorkingCrypto_Call struct {
	*mock.Call
}

// ClearWorkingCrypto is a helper method to define mock.On call
func (_e *MockCommissioningOps_Expecter) ClearWorkingCrypto() *MockCommissioningOps_ClearWorkingCrypto_Call {
	return &MockCommissioningOps_ClearWorkingCrypto_Call{Call: _e.mock.On("ClearWorkingCrypto")}
}

func (_c *MockCommissioningOps_ClearWorkingCrypto_Call) Run(run func()) *MockCommissioningOps_ClearWorkingCrypto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommissioningOps_ClearWorkingCrypto_Call) Return() *MockCommissioningOps_ClearWorkingCrypto_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommissioningOps_ClearWorkingCrypto_Call) RunAndReturn(run func()) *MockCommissioningOps_ClearWorkingCrypto_Call {
	_c.Run(run)
	return _c
}

// CommissionZoneType provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) CommissionZoneType() cert.ZoneType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CommissionZoneType")
	}

	var r0 cert.ZoneType
	if returnFunc, ok := ret.Get(0).(func() cert.ZoneType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(cert.ZoneType)
	}
	return r0
}

// MockCommissioningOps_CommissionZoneType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommissionZoneType'
type MockCommissioningOps_CommissionZoneType_Call struct {
	*mock.Call
}

// CommissionZoneType is a helper method to define mock.On call
func (_e *MockCommissioningOps_Expecter) CommissionZoneType() *MockCommissioningOps_CommissionZoneType_Call {
	return &MockCommissioningOps_CommissionZoneType_Call{Call: _e.mock.On("CommissionZoneType")}
}

func (_c *MockCommissioningOps_CommissionZoneType_Call) Run(run func()) *MockCommissioningOps_CommissionZoneType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommissioningOps_CommissionZoneType_Call) Return(zoneType cert.ZoneType) *MockCommissioningOps_CommissionZoneType_Call {
	_c.Call.Return(zoneType)
	return _c
}

func (_c *MockCommissioningOps_CommissionZoneType_Call) RunAndReturn(run func() cert.ZoneType) *MockCommissioningOps_CommissionZoneType_Call {
	_c.Call.Return(run)
	return _c
}

// DebugSnapshot provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) DebugSnapshot(label string) {
	_mock.Called(label)
	return
}

// MockCommissioningOps_DebugSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebugSnapshot'
type MockCommissioningOps_DebugSnapshot_Call struct {
	*mock.Call
}

// DebugSnapshot is a helper method to define mock.On call
//   - label string
func (_e *MockCommissioningOps_Expecter) DebugSnapshot(label interface{}) *MockCommissioningOps_DebugSnapshot_Call {
	return &MockCommissioningOps_DebugSnapshot_Call{Call: _e.mock.On("DebugSnapshot", label)}
}

func (_c *MockCommissioningOps_DebugSnapshot_Call) Run(run func(label string)) *MockCommissioningOps_DebugSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_DebugSnapshot_Call) Return() *MockCommissioningOps_DebugSnapshot_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommissioningOps_DebugSnapshot_Call) RunAndReturn(run func(label string)) *MockCommissioningOps_DebugSnapshot_Call {
	_c.Run(run)
	return _c
}

// DeviceStateModified provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) DeviceStateModified() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeviceStateModified")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockCommissioningOps_DeviceStateModified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeviceStateModified'
type MockCommissioningOps_DeviceStateModified_Call struct {
	*mock.Call
}

// DeviceStateModified is a helper method to define mock.On call
func (_e *MockCommissioningOps_Expecter) DeviceStateModified() *MockCommissioningOps_DeviceStateModified_Call {
	return &MockCommissioningOps_DeviceStateModified_Call{Call: _e.mock.On("DeviceStateModified")}
}

func (_c *MockCommissioningOps_DeviceStateModified_Call) Run(run func()) *MockCommissioningOps_DeviceStateModified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommissioningOps_DeviceStateModified_Call) Return(b bool) *MockCommissioningOps_DeviceStateModified_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockCommissioningOps_DeviceStateModified_Call) RunAndReturn(run func() bool) *MockCommissioningOps_DeviceStateModified_Call {
	_c.Call.Return(run)
	return _c
}

// DisconnectConnection provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) DisconnectConnection() {
	_mock.Called()
	return
}

// MockCommissioningOps_DisconnectConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectConnection'
type MockCommissioningOps_DisconnectConnection_Call struct {
	*mock.Call
}

// DisconnectConnection is a helper method to define mock.On call
func (_e *MockCommissioningOps_Expecter) DisconnectConnection() *MockCommissioningOps_DisconnectConnection_Call {
	return &MockCommissioningOps_DisconnectConnection_Call{Call: _e.mock.On("DisconnectConnection")}
}

func (_c *MockCommissioningOps_DisconnectConnection_Call) Run(run func()) *MockCommissioningOps_DisconnectConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommissioningOps_DisconnectConnection_Call) Return() *MockCommissioningOps_DisconnectConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommissioningOps_DisconnectConnection_Call) RunAndReturn(run func()) *MockCommissioningOps_DisconnectConnection_Call {
	_c.Run(run)
	return _c
}

// DiscoveredDiscriminator provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) DiscoveredDiscriminator() uint16 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DiscoveredDiscriminator")
	}

	var r0 uint16
	if returnFunc, ok := ret.Get(0).(func() uint16); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint16)
	}
	return r0
}

// MockCommissioningOps_DiscoveredDiscriminator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoveredDiscriminator'
type MockCommissioningOps_DiscoveredDiscriminator_Call struct {
	*mock.Call
}

// DiscoveredDiscriminator is a helper method to define mock.On call
func (_e *MockCommissioningOps_Expecter) DiscoveredDiscriminator() *MockCommissioningOps_DiscoveredDiscriminator_Call {
	return &MockCommissioningOps_DiscoveredDiscriminator_Call{Call: _e.mock.On("DiscoveredDiscriminator")}
}

func (_c *MockCommissioningOps_DiscoveredDiscriminator_Call) Run(run func()) *MockCommissioningOps_DiscoveredDiscriminator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommissioningOps_DiscoveredDiscriminator_Call) Return(v uint16) *MockCommissioningOps_DiscoveredDiscriminator_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockCommissioningOps_DiscoveredDiscriminator_Call) RunAndReturn(run func() uint16) *MockCommissioningOps_DiscoveredDiscriminator_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureCommissioned provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) EnsureCommissioned(ctx context.Context, state *engine.ExecutionState) error {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for EnsureCommissioned")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *engine.ExecutionState) error); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommissioningOps_EnsureCommissioned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureCommissioned'
type MockCommissioningOps_EnsureCommissioned_Call struct {
	*mock.Call
}

// EnsureCommissioned is a helper method to define mock.On call
//   - ctx context.Context
//   - state *engine.ExecutionState
func (_e *MockCommissioningOps_Expecter) EnsureCommissioned(ctx interface{}, state interface{}) *MockCommissioningOps_EnsureCommissioned_Call {
	return &MockCommissioningOps_EnsureCommissioned_Call{Call: _e.mock.On("EnsureCommissioned", ctx, state)}
}

func (_c *MockCommissioningOps_EnsureCommissioned_Call) Run(run func(ctx context.Context, state *engine.ExecutionState)) *MockCommissioningOps_EnsureCommissioned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *engine.ExecutionState
		if args[1] != nil {
			arg1 = args[1].(*engine.ExecutionState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_EnsureCommissioned_Call) Return(err error) *MockCommissioningOps_EnsureCommissioned_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommissioningOps_EnsureCommissioned_Call) RunAndReturn(run func(ctx context.Context, state *engine.ExecutionState) error) *MockCommissioningOps_EnsureCommissioned_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureConnected provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) EnsureConnected(ctx context.Context, state *engine.ExecutionState) error {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for EnsureConnected")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *engine.ExecutionState) error); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommissioningOps_EnsureConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureConnected'
type MockCommissioningOps_EnsureConnected_Call struct {
	*mock.Call
}

// EnsureConnected is a helper method to define mock.On call
//   - ctx context.Context
//   - state *engine.ExecutionState
func (_e *MockCommissioningOps_Expecter) EnsureConnected(ctx interface{}, state interface{}) *MockCommissioningOps_EnsureConnected_Call {
	return &MockCommissioningOps_EnsureConnected_Call{Call: _e.mock.On("EnsureConnected", ctx, state)}
}

func (_c *MockCommissioningOps_EnsureConnected_Call) Run(run func(ctx context.Context, state *engine.ExecutionState)) *MockCommissioningOps_EnsureConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *engine.ExecutionState
		if args[1] != nil {
			arg1 = args[1].(*engine.ExecutionState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_EnsureConnected_Call) Return(err error) *MockCommissioningOps_EnsureConnected_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommissioningOps_EnsureConnected_Call) RunAndReturn(run func(ctx context.Context, state *engine.ExecutionState) error) *MockCommissioningOps_EnsureConnected_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureDisconnected provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) EnsureDisconnected() {
	_mock.Called()
	return
}

// MockCommissioningOps_EnsureDisconnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureDisconnected'
type MockCommissioningOps_EnsureDisconnected_Call struct {
	*mock.Call
}

// EnsureDisconnected is a helper method to define mock.On call
func (_e *MockCommissioningOps_Expecter) EnsureDisconnected() *MockCommissioningOps_EnsureDisconnected_Call {
	return &MockCommissioningOps_EnsureDisconnected_Call{Call: _e.mock.On("EnsureDisconnected")}
}

func (_c *MockCommissioningOps_EnsureDisconnected_Call) Run(run func()) *MockCommissioningOps_EnsureDisconnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommissioningOps_EnsureDisconnected_Call) Return() *MockCommissioningOps_EnsureDisconnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommissioningOps_EnsureDisconnected_Call) RunAndReturn(run func()) *MockCommissioningOps_EnsureDisconnected_Call {
	_c.Run(run)
	return _c
}

// HandlePreconditionCases provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) HandlePreconditionCases(ctx context.Context, tc *loader.TestCase, state *engine.ExecutionState, preconds []loader.Condition, needsMultiZone *bool) error {
	ret := _mock.Called(ctx, tc, state, preconds, needsMultiZone)

	if len(ret) == 0 {
		panic("no return value specified for HandlePreconditionCases")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *loader.TestCase, *engine.ExecutionState, []loader.Condition, *bool) error); ok {
		r0 = returnFunc(ctx, tc, state, preconds, needsMultiZone)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommissioningOps_HandlePreconditionCases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandlePreconditionCases'
type MockCommissioningOps_HandlePreconditionCases_Call struct {
	*mock.Call
}

// HandlePreconditionCases is a helper method to define mock.On call
//   - ctx context.Context
//   - tc *loader.TestCase
//   - state *engine.ExecutionState
//   - preconds []loader.Condition
//   - needsMultiZone *bool
func (_e *MockCommissioningOps_Expecter) HandlePreconditionCases(ctx interface{}, tc interface{}, state interface{}, preconds interface{}, needsMultiZone interface{}) *MockCommissioningOps_HandlePreconditionCases_Call {
	return &MockCommissioningOps_HandlePreconditionCases_Call{Call: _e.mock.On("HandlePreconditionCases", ctx, tc, state, preconds, needsMultiZone)}
}

func (_c *MockCommissioningOps_HandlePreconditionCases_Call) Run(run func(ctx context.Context, tc *loader.TestCase, state *engine.ExecutionState, preconds []loader.Condition, needsMultiZone *bool)) *MockCommissioningOps_HandlePreconditionCases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *loader.TestCase
		if args[1] != nil {
			arg1 = args[1].(*loader.TestCase)
		}
		var arg2 *engine.ExecutionState
		if args[2] != nil {
			arg2 = args[2].(*engine.ExecutionState)
		}
		var arg3 []loader.Condition
		if args[3] != nil {
			arg3 = args[3].([]loader.Condition)
		}
		var arg4 *bool
		if args[4] != nil {
			arg4 = args[4].(*bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_HandlePreconditionCases_Call) Return(err error) *MockCommissioningOps_HandlePreconditionCases_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommissioningOps_HandlePreconditionCases_Call) RunAndReturn(run func(ctx context.Context, tc *loader.TestCase, state *engine.ExecutionState, preconds []loader.Condition, needsMultiZone *bool) error) *MockCommissioningOps_HandlePreconditionCases_Call {
	_c.Call.Return(run)
	return _c
}

// IsSuiteZoneCommission provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) IsSuiteZoneCommission() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsSuiteZoneCommission")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockCommissioningOps_IsSuiteZoneCommission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSuiteZoneCommission'
type MockCommissioningOps_IsSuiteZoneCommission_Call struct {
	*mock.Call
}

// IsSuiteZoneCommission is a helper method to define mock.On call
func (_e *MockCommissioningOps_Expecter) IsSuiteZoneCommission() *MockCommissioningOps_IsSuiteZoneCommission_Call {
	return &MockCommissioningOps_IsSuiteZoneCommission_Call{Call: _e.mock.On("IsSuiteZoneCommission")}
}

func (_c *MockCommissioningOps_IsSuiteZoneCommission_Call) Run(run func()) *MockCommissioningOps_IsSuiteZoneCommission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommissioningOps_IsSuiteZoneCommission_Call) Return(b bool) *MockCommissioningOps_IsSuiteZoneCommission_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockCommissioningOps_IsSuiteZoneCommission_Call) RunAndReturn(run func() bool) *MockCommissioningOps_IsSuiteZoneCommission_Call {
	_c.Call.Return(run)
	return _c
}

// LastDeviceConnClose provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) LastDeviceConnClose() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastDeviceConnClose")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockCommissioningOps_LastDeviceConnClose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastDeviceConnClose'
type MockCommissioningOps_LastDeviceConnClose_Call struct {
	*mock.Call
}

// LastDeviceConnClose is a helper method to define mock.On call
func (_e *MockCommissioningOps_Expecter) LastDeviceConnClose() *MockCommissioningOps_LastDeviceConnClose_Call {
	return &MockCommissioningOps_LastDeviceConnClose_Call{Call: _e.mock.On("LastDeviceConnClose")}
}

func (_c *MockCommissioningOps_LastDeviceConnClose_Call) Run(run func()) *MockCommissioningOps_LastDeviceConnClose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommissioningOps_LastDeviceConnClose_Call) Return(time1 time.Time) *MockCommissioningOps_LastDeviceConnClose_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockCommissioningOps_LastDeviceConnClose_Call) RunAndReturn(run func() time.Time) *MockCommissioningOps_LastDeviceConnClose_Call {
	_c.Call.Return(run)
	return _c
}

// PASEState provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) PASEState() *PASEState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PASEState")
	}

	var r0 *PASEState
	if returnFunc, ok := ret.Get(0).(func() *PASEState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PASEState)
		}
	}
	return r0
}

// MockCommissioningOps_PASEState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PASEState'
type MockCommissioningOps_PASEState_Call struct {
	*mock.Call
}

// PASEState is a helper method to define mock.On call
func (_e *MockCommissioningOps_Expecter) PASEState() *MockCommissioningOps_PASEState_Call {
	return &MockCommissioningOps_PASEState_Call{Call: _e.mock.On("PASEState")}
}

func (_c *MockCommissioningOps_PASEState_Call) Run(run func()) *MockCommissioningOps_PASEState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommissioningOps_PASEState_Call) Return(pASEState *PASEState) *MockCommissioningOps_PASEState_Call {
	_c.Call.Return(pASEState)
	return _c
}

func (_c *MockCommissioningOps_PASEState_Call) RunAndReturn(run func() *PASEState) *MockCommissioningOps_PASEState_Call {
	_c.Call.Return(run)
	return _c
}

// ProbeSessionHealth provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) ProbeSessionHealth() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProbeSessionHealth")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommissioningOps_ProbeSessionHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProbeSessionHealth'
type MockCommissioningOps_ProbeSessionHealth_Call struct {
	*mock.Call
}

// ProbeSessionHealth is a helper method to define mock.On call
func (_e *MockCommissioningOps_Expecter) ProbeSessionHealth() *MockCommissioningOps_ProbeSessionHealth_Call {
	return &MockCommissioningOps_ProbeSessionHealth_Call{Call: _e.mock.On("ProbeSessionHealth")}
}

func (_c *MockCommissioningOps_ProbeSessionHealth_Call) Run(run func()) *MockCommissioningOps_ProbeSessionHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommissioningOps_ProbeSessionHealth_Call) Return(err error) *MockCommissioningOps_ProbeSessionHealth_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommissioningOps_ProbeSessionHealth_Call) RunAndReturn(run func() error) *MockCommissioningOps_ProbeSessionHealth_Call {
	_c.Call.Return(run)
	return _c
}

// ReconnectToZone provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) ReconnectToZone(state *engine.ExecutionState) error {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for ReconnectToZone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*engine.ExecutionState) error); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommissioningOps_ReconnectToZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconnectToZone'
type MockCommissioningOps_ReconnectToZone_Call struct {
	*mock.Call
}

// ReconnectToZone is a helper method to define mock.On call
//   - state *engine.ExecutionState
func (_e *MockCommissioningOps_Expecter) ReconnectToZone(state interface{}) *MockCommissioningOps_ReconnectToZone_Call {
	return &MockCommissioningOps_ReconnectToZone_Call{Call: _e.mock.On("ReconnectToZone", state)}
}

func (_c *MockCommissioningOps_ReconnectToZone_Call) Run(run func(state *engine.ExecutionState)) *MockCommissioningOps_ReconnectToZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *engine.ExecutionState
		if args[0] != nil {
			arg0 = args[0].(*engine.ExecutionState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_ReconnectToZone_Call) Return(err error) *MockCommissioningOps_ReconnectToZone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommissioningOps_ReconnectToZone_Call) RunAndReturn(run func(state *engine.ExecutionState) error) *MockCommissioningOps_ReconnectToZone_Call {
	_c.Call.Return(run)
	return _c
}

// RequestDeviceState provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) RequestDeviceState(ctx context.Context, state *engine.ExecutionState) DeviceStateSnapshot {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for RequestDeviceState")
	}

	var r0 DeviceStateSnapshot
	if returnFunc, ok := ret.Get(0).(func(context.Context, *engine.ExecutionState) DeviceStateSnapshot); ok {
		r0 = returnFunc(ctx, state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(DeviceStateSnapshot)
		}
	}
	return r0
}

// MockCommissioningOps_RequestDeviceState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestDeviceState'
type MockCommissioningOps_RequestDeviceState_Call struct {
	*mock.Call
}

// RequestDeviceState is a helper method to define mock.On call
//   - ctx context.Context
//   - state *engine.ExecutionState
func (_e *MockCommissioningOps_Expecter) RequestDeviceState(ctx interface{}, state interface{}) *MockCommissioningOps_RequestDeviceState_Call {
	return &MockCommissioningOps_RequestDeviceState_Call{Call: _e.mock.On("RequestDeviceState", ctx, state)}
}

func (_c *MockCommissioningOps_RequestDeviceState_Call) Run(run func(ctx context.Context, state *engine.ExecutionState)) *MockCommissioningOps_RequestDeviceState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *engine.ExecutionState
		if args[1] != nil {
			arg1 = args[1].(*engine.ExecutionState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_RequestDeviceState_Call) Return(deviceStateSnapshot DeviceStateSnapshot) *MockCommissioningOps_RequestDeviceState_Call {
	_c.Call.Return(deviceStateSnapshot)
	return _c
}

func (_c *MockCommissioningOps_RequestDeviceState_Call) RunAndReturn(run func(ctx context.Context, state *engine.ExecutionState) DeviceStateSnapshot) *MockCommissioningOps_RequestDeviceState_Call {
	_c.Call.Return(run)
	return _c
}

// SendClearLimitInvoke provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) SendClearLimitInvoke(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SendClearLimitInvoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommissioningOps_SendClearLimitInvoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendClearLimitInvoke'
type MockCommissioningOps_SendClearLimitInvoke_Call struct {
	*mock.Call
}

// SendClearLimitInvoke is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCommissioningOps_Expecter) SendClearLimitInvoke(ctx interface{}) *MockCommissioningOps_SendClearLimitInvoke_Call {
	return &MockCommissioningOps_SendClearLimitInvoke_Call{Call: _e.mock.On("SendClearLimitInvoke", ctx)}
}

func (_c *MockCommissioningOps_SendClearLimitInvoke_Call) Run(run func(ctx context.Context)) *MockCommissioningOps_SendClearLimitInvoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_SendClearLimitInvoke_Call) Return(err error) *MockCommissioningOps_SendClearLimitInvoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommissioningOps_SendClearLimitInvoke_Call) RunAndReturn(run func(ctx context.Context) error) *MockCommissioningOps_SendClearLimitInvoke_Call {
	_c.Call.Return(run)
	return _c
}

// SendRemoveZone provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) SendRemoveZone() {
	_mock.Called()
	return
}

// MockCommissioningOps_SendRemoveZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRemoveZone'
type MockCommissioningOps_SendRemoveZone_Call struct {
	*mock.Call
}

// SendRemoveZone is a helper method to define mock.On call
func (_e *MockCommissioningOps_Expecter) SendRemoveZone() *MockCommissioningOps_SendRemoveZone_Call {
	return &MockCommissioningOps_SendRemoveZone_Call{Call: _e.mock.On("SendRemoveZone")}
}

func (_c *MockCommissioningOps_SendRemoveZone_Call) Run(run func()) *MockCommissioningOps_SendRemoveZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommissioningOps_SendRemoveZone_Call) Return() *MockCommissioningOps_SendRemoveZone_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommissioningOps_SendRemoveZone_Call) RunAndReturn(run func()) *MockCommissioningOps_SendRemoveZone_Call {
	_c.Run(run)
	return _c
}

// SendRemoveZoneOnConn provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) SendRemoveZoneOnConn(conn *Connection, zoneID string) {
	_mock.Called(conn, zoneID)
	return
}

// MockCommissioningOps_SendRemoveZoneOnConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRemoveZoneOnConn'
type MockCommissioningOps_SendRemoveZoneOnConn_Call struct {
	*mock.Call
}

// SendRemoveZoneOnConn is a helper method to define mock.On call
//   - conn *Connection
//   - zoneID string
func (_e *MockCommissioningOps_Expecter) SendRemoveZoneOnConn(conn interface{}, zoneID interface{}) *MockCommissioningOps_SendRemoveZoneOnConn_Call {
	return &MockCommissioningOps_SendRemoveZoneOnConn_Call{Call: _e.mock.On("SendRemoveZoneOnConn", conn, zoneID)}
}

func (_c *MockCommissioningOps_SendRemoveZoneOnConn_Call) Run(run func(conn *Connection, zoneID string)) *MockCommissioningOps_SendRemoveZoneOnConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Connection
		if args[0] != nil {
			arg0 = args[0].(*Connection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_SendRemoveZoneOnConn_Call) Return() *MockCommissioningOps_SendRemoveZoneOnConn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommissioningOps_SendRemoveZoneOnConn_Call) RunAndReturn(run func(conn *Connection, zoneID string)) *MockCommissioningOps_SendRemoveZoneOnConn_Call {
	_c.Run(run)
	return _c
}

// SendTriggerViaZone provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) SendTriggerViaZone(ctx context.Context, trigger uint64, state *engine.ExecutionState) error {
	ret := _mock.Called(ctx, trigger, state)

	if len(ret) == 0 {
		panic("no return value specified for SendTriggerViaZone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *engine.ExecutionState) error); ok {
		r0 = returnFunc(ctx, trigger, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommissioningOps_SendTriggerViaZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTriggerViaZone'
type MockCommissioningOps_SendTriggerViaZone_Call struct {
	*mock.Call
}

// SendTriggerViaZone is a helper method to define mock.On call
//   - ctx context.Context
//   - trigger uint64
//   - state *engine.ExecutionState
func (_e *MockCommissioningOps_Expecter) SendTriggerViaZone(ctx interface{}, trigger interface{}, state interface{}) *MockCommissioningOps_SendTriggerViaZone_Call {
	return &MockCommissioningOps_SendTriggerViaZone_Call{Call: _e.mock.On("SendTriggerViaZone", ctx, trigger, state)}
}

func (_c *MockCommissioningOps_SendTriggerViaZone_Call) Run(run func(ctx context.Context, trigger uint64, state *engine.ExecutionState)) *MockCommissioningOps_SendTriggerViaZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *engine.ExecutionState
		if args[2] != nil {
			arg2 = args[2].(*engine.ExecutionState)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_SendTriggerViaZone_Call) Return(err error) *MockCommissioningOps_SendTriggerViaZone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommissioningOps_SendTriggerViaZone_Call) RunAndReturn(run func(ctx context.Context, trigger uint64, state *engine.ExecutionState) error) *MockCommissioningOps_SendTriggerViaZone_Call {
	_c.Call.Return(run)
	return _c
}

// SetCommissionZoneType provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) SetCommissionZoneType(zt cert.ZoneType) {
	_mock.Called(zt)
	return
}

// MockCommissioningOps_SetCommissionZoneType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCommissionZoneType'
type MockCommissioningOps_SetCommissionZoneType_Call struct {
	*mock.Call
}

// SetCommissionZoneType is a helper method to define mock.On call
//   - zt cert.ZoneType
func (_e *MockCommissioningOps_Expecter) SetCommissionZoneType(zt interface{}) *MockCommissioningOps_SetCommissionZoneType_Call {
	return &MockCommissioningOps_SetCommissionZoneType_Call{Call: _e.mock.On("SetCommissionZoneType", zt)}
}

func (_c *MockCommissioningOps_SetCommissionZoneType_Call) Run(run func(zt cert.ZoneType)) *MockCommissioningOps_SetCommissionZoneType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cert.ZoneType
		if args[0] != nil {
			arg0 = args[0].(cert.ZoneType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_SetCommissionZoneType_Call) Return() *MockCommissioningOps_SetCommissionZoneType_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommissioningOps_SetCommissionZoneType_Call) RunAndReturn(run func(zt cert.ZoneType)) *MockCommissioningOps_SetCommissionZoneType_Call {
	_c.Run(run)
	return _c
}

// SetDeviceStateModified provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) SetDeviceStateModified(modified bool) {
	_mock.Called(modified)
	return
}

// MockCommissioningOps_SetDeviceStateModified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDeviceStateModified'
type MockCommissioningOps_SetDeviceStateModified_Call struct {
	*mock.Call
}

// SetDeviceStateModified is a helper method to define mock.On call
//   - modified bool
func (_e *MockCommissioningOps_Expecter) SetDeviceStateModified(modified interface{}) *MockCommissioningOps_SetDeviceStateModified_Call {
	return &MockCommissioningOps_SetDeviceStateModified_Call{Call: _e.mock.On("SetDeviceStateModified", modified)}
}

func (_c *MockCommissioningOps_SetDeviceStateModified_Call) Run(run func(modified bool)) *MockCommissioningOps_SetDeviceStateModified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_SetDeviceStateModified_Call) Return() *MockCommissioningOps_SetDeviceStateModified_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommissioningOps_SetDeviceStateModified_Call) RunAndReturn(run func(modified bool)) *MockCommissioningOps_SetDeviceStateModified_Call {
	_c.Run(run)
	return _c
}

// SetLastDeviceConnClose provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) SetLastDeviceConnClose(t time.Time) {
	_mock.Called(t)
	return
}

// MockCommissioningOps_SetLastDeviceConnClose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLastDeviceConnClose'
type MockCommissioningOps_SetLastDeviceConnClose_Call struct {
	*mock.Call
}

// SetLastDeviceConnClose is a helper method to define mock.On call
//   - t time.Time
func (_e *MockCommissioningOps_Expecter) SetLastDeviceConnClose(t interface{}) *MockCommissioningOps_SetLastDeviceConnClose_Call {
	return &MockCommissioningOps_SetLastDeviceConnClose_Call{Call: _e.mock.On("SetLastDeviceConnClose", t)}
}

func (_c *MockCommissioningOps_SetLastDeviceConnClose_Call) Run(run func(t time.Time)) *MockCommissioningOps_SetLastDeviceConnClose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_SetLastDeviceConnClose_Call) Return() *MockCommissioningOps_SetLastDeviceConnClose_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommissioningOps_SetLastDeviceConnClose_Call) RunAndReturn(run func(t time.Time)) *MockCommissioningOps_SetLastDeviceConnClose_Call {
	_c.Run(run)
	return _c
}

// SetPASEState provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) SetPASEState(ps *PASEState) {
	_mock.Called(ps)
	return
}

// MockCommissioningOps_SetPASEState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPASEState'
type MockCommissioningOps_SetPASEState_Call struct {
	*mock.Call
}

// SetPASEState is a helper method to define mock.On call
//   - ps *PASEState
func (_e *MockCommissioningOps_Expecter) SetPASEState(ps interface{}) *MockCommissioningOps_SetPASEState_Call {
	return &MockCommissioningOps_SetPASEState_Call{Call: _e.mock.On("SetPASEState", ps)}
}

func (_c *MockCommissioningOps_SetPASEState_Call) Run(run func(ps *PASEState)) *MockCommissioningOps_SetPASEState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *PASEState
		if args[0] != nil {
			arg0 = args[0].(*PASEState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_SetPASEState_Call) Return() *MockCommissioningOps_SetPASEState_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommissioningOps_SetPASEState_Call) RunAndReturn(run func(ps *PASEState)) *MockCommissioningOps_SetPASEState_Call {
	_c.Run(run)
	return _c
}

// SetWorkingCrypto provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) SetWorkingCrypto(crypto CryptoState) {
	_mock.Called(crypto)
	return
}

// MockCommissioningOps_SetWorkingCrypto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWorkingCrypto'
type MockCommissioningOps_SetWorkingCrypto_Call struct {
	*mock.Call
}

// SetWorkingCrypto is a helper method to define mock.On call
//   - crypto CryptoState
func (_e *MockCommissioningOps_Expecter) SetWorkingCrypto(crypto interface{}) *MockCommissioningOps_SetWorkingCrypto_Call {
	return &MockCommissioningOps_SetWorkingCrypto_Call{Call: _e.mock.On("SetWorkingCrypto", crypto)}
}

func (_c *MockCommissioningOps_SetWorkingCrypto_Call) Run(run func(crypto CryptoState)) *MockCommissioningOps_SetWorkingCrypto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 CryptoState
		if args[0] != nil {
			arg0 = args[0].(CryptoState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_SetWorkingCrypto_Call) Return() *MockCommissioningOps_SetWorkingCrypto_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommissioningOps_SetWorkingCrypto_Call) RunAndReturn(run func(crypto CryptoState)) *MockCommissioningOps_SetWorkingCrypto_Call {
	_c.Run(run)
	return _c
}

// WaitForCommissioningMode provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) WaitForCommissioningMode(ctx context.Context, timeout time.Duration) error {
	ret := _mock.Called(ctx, timeout)

	if len(ret) == 0 {
		panic("no return value specified for WaitForCommissioningMode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) error); ok {
		r0 = returnFunc(ctx, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommissioningOps_WaitForCommissioningMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForCommissioningMode'
type MockCommissioningOps_WaitForCommissioningMode_Call struct {
	*mock.Call
}

// WaitForCommissioningMode is a helper method to define mock.On call
//   - ctx context.Context
//   - timeout time.Duration
func (_e *MockCommissioningOps_Expecter) WaitForCommissioningMode(ctx interface{}, timeout interface{}) *MockCommissioningOps_WaitForCommissioningMode_Call {
	return &MockCommissioningOps_WaitForCommissioningMode_Call{Call: _e.mock.On("WaitForCommissioningMode", ctx, timeout)}
}

func (_c *MockCommissioningOps_WaitForCommissioningMode_Call) Run(run func(ctx context.Context, timeout time.Duration)) *MockCommissioningOps_WaitForCommissioningMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommissioningOps_WaitForCommissioningMode_Call) Return(err error) *MockCommissioningOps_WaitForCommissioningMode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommissioningOps_WaitForCommissioningMode_Call) RunAndReturn(run func(ctx context.Context, timeout time.Duration) error) *MockCommissioningOps_WaitForCommissioningMode_Call {
	_c.Call.Return(run)
	return _c
}

// WorkingCrypto provides a mock function for the type MockCommissioningOps
func (_mock *MockCommissioningOps) WorkingCrypto() CryptoState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WorkingCrypto")
	}

	var r0 CryptoState
	if returnFunc, ok := ret.Get(0).(func() CryptoState); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(CryptoState)
	}
	return r0
}

// MockCommissioningOps_WorkingCrypto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkingCrypto'
type MockCommissioningOps_WorkingCrypto_Call struct {
	*mock.Call
}

// WorkingCrypto is a helper method to define mock.On call
func (_e *MockCommissioningOps_Expecter) WorkingCrypto() *MockCommissioningOps_WorkingCrypto_Call {
	return &MockCommissioningOps_WorkingCrypto_Call{Call: _e.mock.On("WorkingCrypto")}
}

func (_c *MockCommissioningOps_WorkingCrypto_Call) Run(run func()) *MockCommissioningOps_WorkingCrypto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommissioningOps_WorkingCrypto_Call) Return(cryptoState CryptoState) *MockCommissioningOps_WorkingCrypto_Call {
	_c.Call.Return(cryptoState)
	return _c
}

func (_c *MockCommissioningOps_WorkingCrypto_Call) RunAndReturn(run func() CryptoState) *MockCommissioningOps_WorkingCrypto_Call {
	_c.Call.Return(run)
	return _c
}
