// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runner

import (
	"context"
	"crypto/tls"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDialer creates a new instance of MockDialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDialer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDialer {
	mock := &MockDialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDialer is an autogenerated mock type for the Dialer type
type MockDialer struct {
	mock.Mock
}

type MockDialer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDialer) EXPECT() *MockDialer_Expecter {
	return &MockDialer_Expecter{mock: &_m.Mock}
}

// DialCommissioning provides a mock function for the type MockDialer
func (_mock *MockDialer) DialCommissioning(ctx context.Context, target string) (*tls.Conn, error) {
	ret := _mock.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for DialCommissioning")
	}

	var r0 *tls.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*tls.Conn, error)); ok {
		return returnFunc(ctx, target)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *tls.Conn); ok {
		r0 = returnFunc(ctx, target)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDialer_DialCommissioning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DialCommissioning'
type MockDialer_DialCommissioning_Call struct {
	*mock.Call
}

// DialCommissioning is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
func (_e *MockDialer_Expecter) DialCommissioning(ctx interface{}, target interface{}) *MockDialer_DialCommissioning_Call {
	return &MockDialer_DialCommissioning_Call{Call: _e.mock.On("DialCommissioning", ctx, target)}
}

func (_c *MockDialer_DialCommissioning_Call) Run(run func(ctx context.Context, target string)) *MockDialer_DialCommissioning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDialer_DialCommissioning_Call) Return(conn *tls.Conn, err error) *MockDialer_DialCommissioning_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *MockDialer_DialCommissioning_Call) RunAndReturn(run func(ctx context.Context, target string) (*tls.Conn, error)) *MockDialer_DialCommissioning_Call {
	_c.Call.Return(run)
	return _c
}

// DialOperational provides a mock function for the type MockDialer
func (_mock *MockDialer) DialOperational(ctx context.Context, target string, crypto CryptoState) (*tls.Conn, error) {
	ret := _mock.Called(ctx, target, crypto)

	if len(ret) == 0 {
		panic("no return value specified for DialOperational")
	}

	var r0 *tls.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, CryptoState) (*tls.Conn, error)); ok {
		return returnFunc(ctx, target, crypto)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, CryptoState) *tls.Conn); ok {
		r0 = returnFunc(ctx, target, crypto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, CryptoState) error); ok {
		r1 = returnFunc(ctx, target, crypto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDialer_DialOperational_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DialOperational'
type MockDialer_DialOperational_Call struct {
	*mock.Call
}

// DialOperational is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
//   - crypto CryptoState
func (_e *MockDialer_Expecter) DialOperational(ctx interface{}, target interface{}, crypto interface{}) *MockDialer_DialOperational_Call {
	return &MockDialer_DialOperational_Call{Call: _e.mock.On("DialOperational", ctx, target, crypto)}
}

func (_c *MockDialer_DialOperational_Call) Run(run func(ctx context.Context, target string, crypto CryptoState)) *MockDialer_DialOperational_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 CryptoState
		if args[2] != nil {
			arg2 = args[2].(CryptoState)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDialer_DialOperational_Call) Return(conn *tls.Conn, err error) *MockDialer_DialOperational_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *MockDialer_DialOperational_Call) RunAndReturn(run func(ctx context.Context, target string, crypto CryptoState) (*tls.Conn, error)) *MockDialer_DialOperational_Call {
	_c.Call.Return(run)
	return _c
}
