// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runner

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnWriter creates a new instance of MockConnWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnWriter {
	mock := &MockConnWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnWriter is an autogenerated mock type for the ConnWriter type
type MockConnWriter struct {
	mock.Mock
}

type MockConnWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnWriter) EXPECT() *MockConnWriter_Expecter {
	return &MockConnWriter_Expecter{mock: &_m.Mock}
}

// RemoveSubscription provides a mock function for the type MockConnWriter
func (_mock *MockConnWriter) RemoveSubscription(subID uint32) {
	_mock.Called(subID)
	return
}

// MockConnWriter_RemoveSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSubscription'
type MockConnWriter_RemoveSubscription_Call struct {
	*mock.Call
}

// RemoveSubscription is a helper method to define mock.On call
//   - subID uint32
func (_e *MockConnWriter_Expecter) RemoveSubscription(subID interface{}) *MockConnWriter_RemoveSubscription_Call {
	return &MockConnWriter_RemoveSubscription_Call{Call: _e.mock.On("RemoveSubscription", subID)}
}

func (_c *MockConnWriter_RemoveSubscription_Call) Run(run func(subID uint32)) *MockConnWriter_RemoveSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnWriter_RemoveSubscription_Call) Return() *MockConnWriter_RemoveSubscription_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnWriter_RemoveSubscription_Call) RunAndReturn(run func(subID uint32)) *MockConnWriter_RemoveSubscription_Call {
	_c.Run(run)
	return _c
}

// SetMain provides a mock function for the type MockConnWriter
func (_mock *MockConnWriter) SetMain(conn *Connection) {
	_mock.Called(conn)
	return
}

// MockConnWriter_SetMain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMain'
type MockConnWriter_SetMain_Call struct {
	*mock.Call
}

// SetMain is a helper method to define mock.On call
//   - conn *Connection
func (_e *MockConnWriter_Expecter) SetMain(conn interface{}) *MockConnWriter_SetMain_Call {
	return &MockConnWriter_SetMain_Call{Call: _e.mock.On("SetMain", conn)}
}

func (_c *MockConnWriter_SetMain_Call) Run(run func(conn *Connection)) *MockConnWriter_SetMain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Connection
		if args[0] != nil {
			arg0 = args[0].(*Connection)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnWriter_SetMain_Call) Return() *MockConnWriter_SetMain_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnWriter_SetMain_Call) RunAndReturn(run func(conn *Connection)) *MockConnWriter_SetMain_Call {
	_c.Run(run)
	return _c
}

// TrackSubscription provides a mock function for the type MockConnWriter
func (_mock *MockConnWriter) TrackSubscription(subID uint32) {
	_mock.Called(subID)
	return
}

// MockConnWriter_TrackSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackSubscription'
type MockConnWriter_TrackSubscription_Call struct {
	*mock.Call
}

// TrackSubscription is a helper method to define mock.On call
//   - subID uint32
func (_e *MockConnWriter_Expecter) TrackSubscription(subID interface{}) *MockConnWriter_TrackSubscription_Call {
	return &MockConnWriter_TrackSubscription_Call{Call: _e.mock.On("TrackSubscription", subID)}
}

func (_c *MockConnWriter_TrackSubscription_Call) Run(run func(subID uint32)) *MockConnWriter_TrackSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnWriter_TrackSubscription_Call) Return() *MockConnWriter_TrackSubscription_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnWriter_TrackSubscription_Call) RunAndReturn(run func(subID uint32)) *MockConnWriter_TrackSubscription_Call {
	_c.Run(run)
	return _c
}

// TrackZone provides a mock function for the type MockConnWriter
func (_mock *MockConnWriter) TrackZone(key string, conn *Connection, zoneID string) {
	_mock.Called(key, conn, zoneID)
	return
}

// MockConnWriter_TrackZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackZone'
type MockConnWriter_TrackZone_Call struct {
	*mock.Call
}

// TrackZone is a helper method to define mock.On call
//   - key string
//   - conn *Connection
//   - zoneID string
func (_e *MockConnWriter_Expecter) TrackZone(key interface{}, conn interface{}, zoneID interface{}) *MockConnWriter_TrackZone_Call {
	return &MockConnWriter_TrackZone_Call{Call: _e.mock.On("TrackZone", key, conn, zoneID)}
}

func (_c *MockConnWriter_TrackZone_Call) Run(run func(key string, conn *Connection, zoneID string)) *MockConnWriter_TrackZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *Connection
		if args[1] != nil {
			arg1 = args[1].(*Connection)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnWriter_TrackZone_Call) Return() *MockConnWriter_TrackZone_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnWriter_TrackZone_Call) RunAndReturn(run func(key string, conn *Connection, zoneID string)) *MockConnWriter_TrackZone_Call {
	_c.Run(run)
	return _c
}

// UntrackZone provides a mock function for the type MockConnWriter
func (_mock *MockConnWriter) UntrackZone(key string) {
	_mock.Called(key)
	return
}

// MockConnWriter_UntrackZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UntrackZone'
type MockConnWriter_UntrackZone_Call struct {
	*mock.Call
}

// UntrackZone is a helper method to define mock.On call
//   - key string
func (_e *MockConnWriter_Expecter) UntrackZone(key interface{}) *MockConnWriter_UntrackZone_Call {
	return &MockConnWriter_UntrackZone_Call{Call: _e.mock.On("UntrackZone", key)}
}

func (_c *MockConnWriter_UntrackZone_Call) Run(run func(key string)) *MockConnWriter_UntrackZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnWriter_UntrackZone_Call) Return() *MockConnWriter_UntrackZone_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnWriter_UntrackZone_Call) RunAndReturn(run func(key string)) *MockConnWriter_UntrackZone_Call {
	_c.Run(run)
	return _c
}
