// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runner

import (
	"context"

	"github.com/mash-protocol/mash-go/pkg/wire"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRequestSender creates a new instance of MockRequestSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestSender {
	mock := &MockRequestSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRequestSender is an autogenerated mock type for the RequestSender type
type MockRequestSender struct {
	mock.Mock
}

type MockRequestSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestSender) EXPECT() *MockRequestSender_Expecter {
	return &MockRequestSender_Expecter{mock: &_m.Mock}
}

// SendRequest provides a mock function for the type MockRequestSender
func (_mock *MockRequestSender) SendRequest(data []byte, op string, expectedMsgID uint32) (*wire.Response, error) {
	ret := _mock.Called(data, op, expectedMsgID)

	if len(ret) == 0 {
		panic("no return value specified for SendRequest")
	}

	var r0 *wire.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, string, uint32) (*wire.Response, error)); ok {
		return returnFunc(data, op, expectedMsgID)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, string, uint32) *wire.Response); ok {
		r0 = returnFunc(data, op, expectedMsgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wire.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, string, uint32) error); ok {
		r1 = returnFunc(data, op, expectedMsgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequestSender_SendRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRequest'
type MockRequestSender_SendRequest_Call struct {
	*mock.Call
}

// SendRequest is a helper method to define mock.On call
//   - data []byte
//   - op string
//   - expectedMsgID uint32
func (_e *MockRequestSender_Expecter) SendRequest(data interface{}, op interface{}, expectedMsgID interface{}) *MockRequestSender_SendRequest_Call {
	return &MockRequestSender_SendRequest_Call{Call: _e.mock.On("SendRequest", data, op, expectedMsgID)}
}

func (_c *MockRequestSender_SendRequest_Call) Run(run func(data []byte, op string, expectedMsgID uint32)) *MockRequestSender_SendRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRequestSender_SendRequest_Call) Return(response *wire.Response, err error) *MockRequestSender_SendRequest_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRequestSender_SendRequest_Call) RunAndReturn(run func(data []byte, op string, expectedMsgID uint32) (*wire.Response, error)) *MockRequestSender_SendRequest_Call {
	_c.Call.Return(run)
	return _c
}

// SendRequestWithDeadline provides a mock function for the type MockRequestSender
func (_mock *MockRequestSender) SendRequestWithDeadline(ctx context.Context, data []byte, op string, expectedMsgID uint32) (*wire.Response, error) {
	ret := _mock.Called(ctx, data, op, expectedMsgID)

	if len(ret) == 0 {
		panic("no return value specified for SendRequestWithDeadline")
	}

	var r0 *wire.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, string, uint32) (*wire.Response, error)); ok {
		return returnFunc(ctx, data, op, expectedMsgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, string, uint32) *wire.Response); ok {
		r0 = returnFunc(ctx, data, op, expectedMsgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wire.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, string, uint32) error); ok {
		r1 = returnFunc(ctx, data, op, expectedMsgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequestSender_SendRequestWithDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRequestWithDeadline'
type MockRequestSender_SendRequestWithDeadline_Call struct {
	*mock.Call
}

// SendRequestWithDeadline is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
//   - op string
//   - expectedMsgID uint32
func (_e *MockRequestSender_Expecter) SendRequestWithDeadline(ctx interface{}, data interface{}, op interface{}, expectedMsgID interface{}) *MockRequestSender_SendRequestWithDeadline_Call {
	return &MockRequestSender_SendRequestWithDeadline_Call{Call: _e.mock.On("SendRequestWithDeadline", ctx, data, op, expectedMsgID)}
}

func (_c *MockRequestSender_SendRequestWithDeadline_Call) Run(run func(ctx context.Context, data []byte, op string, expectedMsgID uint32)) *MockRequestSender_SendRequestWithDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uint32
		if args[3] != nil {
			arg3 = args[3].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRequestSender_SendRequestWithDeadline_Call) Return(response *wire.Response, err error) *MockRequestSender_SendRequestWithDeadline_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRequestSender_SendRequestWithDeadline_Call) RunAndReturn(run func(ctx context.Context, data []byte, op string, expectedMsgID uint32) (*wire.Response, error)) *MockRequestSender_SendRequestWithDeadline_Call {
	_c.Call.Return(run)
	return _c
}
