// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runner

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"time"

	"github.com/mash-protocol/mash-go/internal/testharness/engine"
	"github.com/mash-protocol/mash-go/pkg/cert"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectionManager creates a new instance of MockConnectionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionManager {
	mock := &MockConnectionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionManager is an autogenerated mock type for the ConnectionManager type
type MockConnectionManager struct {
	mock.Mock
}

type MockConnectionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionManager) EXPECT() *MockConnectionManager_Expecter {
	return &MockConnectionManager_Expecter{mock: &_m.Mock}
}

// ClearWorkingCrypto provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) ClearWorkingCrypto() {
	_mock.Called()
	return
}

// MockConnectionManager_ClearWorkingCrypto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearWorkingCrypto'
type MockConnectionManager_ClearWorkingCrypto_Call struct {
	*mock.Call
}

// ClearWorkingCrypto is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) ClearWorkingCrypto() *MockConnectionManager_ClearWorkingCrypto_Call {
	return &MockConnectionManager_ClearWorkingCrypto_Call{Call: _e.mock.On("ClearWorkingCrypto")}
}

func (_c *MockConnectionManager_ClearWorkingCrypto_Call) Run(run func()) *MockConnectionManager_ClearWorkingCrypto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_ClearWorkingCrypto_Call) Return() *MockConnectionManager_ClearWorkingCrypto_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_ClearWorkingCrypto_Call) RunAndReturn(run func()) *MockConnectionManager_ClearWorkingCrypto_Call {
	_c.Run(run)
	return _c
}

// CommissionZoneType provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) CommissionZoneType() cert.ZoneType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CommissionZoneType")
	}

	var r0 cert.ZoneType
	if returnFunc, ok := ret.Get(0).(func() cert.ZoneType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(cert.ZoneType)
	}
	return r0
}

// MockConnectionManager_CommissionZoneType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommissionZoneType'
type MockConnectionManager_CommissionZoneType_Call struct {
	*mock.Call
}

// CommissionZoneType is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) CommissionZoneType() *MockConnectionManager_CommissionZoneType_Call {
	return &MockConnectionManager_CommissionZoneType_Call{Call: _e.mock.On("CommissionZoneType")}
}

func (_c *MockConnectionManager_CommissionZoneType_Call) Run(run func()) *MockConnectionManager_CommissionZoneType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_CommissionZoneType_Call) Return(zoneType cert.ZoneType) *MockConnectionManager_CommissionZoneType_Call {
	_c.Call.Return(zoneType)
	return _c
}

func (_c *MockConnectionManager_CommissionZoneType_Call) RunAndReturn(run func() cert.ZoneType) *MockConnectionManager_CommissionZoneType_Call {
	_c.Call.Return(run)
	return _c
}

// ControllerCert provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) ControllerCert() *cert.OperationalCert {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ControllerCert")
	}

	var r0 *cert.OperationalCert
	if returnFunc, ok := ret.Get(0).(func() *cert.OperationalCert); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cert.OperationalCert)
		}
	}
	return r0
}

// MockConnectionManager_ControllerCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ControllerCert'
type MockConnectionManager_ControllerCert_Call struct {
	*mock.Call
}

// ControllerCert is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) ControllerCert() *MockConnectionManager_ControllerCert_Call {
	return &MockConnectionManager_ControllerCert_Call{Call: _e.mock.On("ControllerCert")}
}

func (_c *MockConnectionManager_ControllerCert_Call) Run(run func()) *MockConnectionManager_ControllerCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_ControllerCert_Call) Return(operationalCert *cert.OperationalCert) *MockConnectionManager_ControllerCert_Call {
	_c.Call.Return(operationalCert)
	return _c
}

func (_c *MockConnectionManager_ControllerCert_Call) RunAndReturn(run func() *cert.OperationalCert) *MockConnectionManager_ControllerCert_Call {
	_c.Call.Return(run)
	return _c
}

// DeviceStateModified provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) DeviceStateModified() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeviceStateModified")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConnectionManager_DeviceStateModified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeviceStateModified'
type MockConnectionManager_DeviceStateModified_Call struct {
	*mock.Call
}

// DeviceStateModified is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) DeviceStateModified() *MockConnectionManager_DeviceStateModified_Call {
	return &MockConnectionManager_DeviceStateModified_Call{Call: _e.mock.On("DeviceStateModified")}
}

func (_c *MockConnectionManager_DeviceStateModified_Call) Run(run func()) *MockConnectionManager_DeviceStateModified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_DeviceStateModified_Call) Return(b bool) *MockConnectionManager_DeviceStateModified_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConnectionManager_DeviceStateModified_Call) RunAndReturn(run func() bool) *MockConnectionManager_DeviceStateModified_Call {
	_c.Call.Return(run)
	return _c
}

// DisconnectConnection provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) DisconnectConnection() {
	_mock.Called()
	return
}

// MockConnectionManager_DisconnectConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectConnection'
type MockConnectionManager_DisconnectConnection_Call struct {
	*mock.Call
}

// DisconnectConnection is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) DisconnectConnection() *MockConnectionManager_DisconnectConnection_Call {
	return &MockConnectionManager_DisconnectConnection_Call{Call: _e.mock.On("DisconnectConnection")}
}

func (_c *MockConnectionManager_DisconnectConnection_Call) Run(run func()) *MockConnectionManager_DisconnectConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_DisconnectConnection_Call) Return() *MockConnectionManager_DisconnectConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_DisconnectConnection_Call) RunAndReturn(run func()) *MockConnectionManager_DisconnectConnection_Call {
	_c.Run(run)
	return _c
}

// DiscoveredDiscriminator provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) DiscoveredDiscriminator() uint16 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DiscoveredDiscriminator")
	}

	var r0 uint16
	if returnFunc, ok := ret.Get(0).(func() uint16); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint16)
	}
	return r0
}

// MockConnectionManager_DiscoveredDiscriminator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoveredDiscriminator'
type MockConnectionManager_DiscoveredDiscriminator_Call struct {
	*mock.Call
}

// DiscoveredDiscriminator is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) DiscoveredDiscriminator() *MockConnectionManager_DiscoveredDiscriminator_Call {
	return &MockConnectionManager_DiscoveredDiscriminator_Call{Call: _e.mock.On("DiscoveredDiscriminator")}
}

func (_c *MockConnectionManager_DiscoveredDiscriminator_Call) Run(run func()) *MockConnectionManager_DiscoveredDiscriminator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_DiscoveredDiscriminator_Call) Return(v uint16) *MockConnectionManager_DiscoveredDiscriminator_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockConnectionManager_DiscoveredDiscriminator_Call) RunAndReturn(run func() uint16) *MockConnectionManager_DiscoveredDiscriminator_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureCommissioned provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) EnsureCommissioned(ctx context.Context, state *engine.ExecutionState) error {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for EnsureCommissioned")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *engine.ExecutionState) error); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionManager_EnsureCommissioned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureCommissioned'
type MockConnectionManager_EnsureCommissioned_Call struct {
	*mock.Call
}

// EnsureCommissioned is a helper method to define mock.On call
//   - ctx context.Context
//   - state *engine.ExecutionState
func (_e *MockConnectionManager_Expecter) EnsureCommissioned(ctx interface{}, state interface{}) *MockConnectionManager_EnsureCommissioned_Call {
	return &MockConnectionManager_EnsureCommissioned_Call{Call: _e.mock.On("EnsureCommissioned", ctx, state)}
}

func (_c *MockConnectionManager_EnsureCommissioned_Call) Run(run func(ctx context.Context, state *engine.ExecutionState)) *MockConnectionManager_EnsureCommissioned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *engine.ExecutionState
		if args[1] != nil {
			arg1 = args[1].(*engine.ExecutionState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectionManager_EnsureCommissioned_Call) Return(err error) *MockConnectionManager_EnsureCommissioned_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionManager_EnsureCommissioned_Call) RunAndReturn(run func(ctx context.Context, state *engine.ExecutionState) error) *MockConnectionManager_EnsureCommissioned_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureConnected provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) EnsureConnected(ctx context.Context, state *engine.ExecutionState) error {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for EnsureConnected")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *engine.ExecutionState) error); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionManager_EnsureConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureConnected'
type MockConnectionManager_EnsureConnected_Call struct {
	*mock.Call
}

// EnsureConnected is a helper method to define mock.On call
//   - ctx context.Context
//   - state *engine.ExecutionState
func (_e *MockConnectionManager_Expecter) EnsureConnected(ctx interface{}, state interface{}) *MockConnectionManager_EnsureConnected_Call {
	return &MockConnectionManager_EnsureConnected_Call{Call: _e.mock.On("EnsureConnected", ctx, state)}
}

func (_c *MockConnectionManager_EnsureConnected_Call) Run(run func(ctx context.Context, state *engine.ExecutionState)) *MockConnectionManager_EnsureConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *engine.ExecutionState
		if args[1] != nil {
			arg1 = args[1].(*engine.ExecutionState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectionManager_EnsureConnected_Call) Return(err error) *MockConnectionManager_EnsureConnected_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionManager_EnsureConnected_Call) RunAndReturn(run func(ctx context.Context, state *engine.ExecutionState) error) *MockConnectionManager_EnsureConnected_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureDisconnected provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) EnsureDisconnected() {
	_mock.Called()
	return
}

// MockConnectionManager_EnsureDisconnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureDisconnected'
type MockConnectionManager_EnsureDisconnected_Call struct {
	*mock.Call
}

// EnsureDisconnected is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) EnsureDisconnected() *MockConnectionManager_EnsureDisconnected_Call {
	return &MockConnectionManager_EnsureDisconnected_Call{Call: _e.mock.On("EnsureDisconnected")}
}

func (_c *MockConnectionManager_EnsureDisconnected_Call) Run(run func()) *MockConnectionManager_EnsureDisconnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_EnsureDisconnected_Call) Return() *MockConnectionManager_EnsureDisconnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_EnsureDisconnected_Call) RunAndReturn(run func()) *MockConnectionManager_EnsureDisconnected_Call {
	_c.Run(run)
	return _c
}

// IsSuiteZoneCommission provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) IsSuiteZoneCommission() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsSuiteZoneCommission")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConnectionManager_IsSuiteZoneCommission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSuiteZoneCommission'
type MockConnectionManager_IsSuiteZoneCommission_Call struct {
	*mock.Call
}

// IsSuiteZoneCommission is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) IsSuiteZoneCommission() *MockConnectionManager_IsSuiteZoneCommission_Call {
	return &MockConnectionManager_IsSuiteZoneCommission_Call{Call: _e.mock.On("IsSuiteZoneCommission")}
}

func (_c *MockConnectionManager_IsSuiteZoneCommission_Call) Run(run func()) *MockConnectionManager_IsSuiteZoneCommission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_IsSuiteZoneCommission_Call) Return(b bool) *MockConnectionManager_IsSuiteZoneCommission_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConnectionManager_IsSuiteZoneCommission_Call) RunAndReturn(run func() bool) *MockConnectionManager_IsSuiteZoneCommission_Call {
	_c.Call.Return(run)
	return _c
}

// IssuedDeviceCert provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) IssuedDeviceCert() *x509.Certificate {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IssuedDeviceCert")
	}

	var r0 *x509.Certificate
	if returnFunc, ok := ret.Get(0).(func() *x509.Certificate); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*x509.Certificate)
		}
	}
	return r0
}

// MockConnectionManager_IssuedDeviceCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssuedDeviceCert'
type MockConnectionManager_IssuedDeviceCert_Call struct {
	*mock.Call
}

// IssuedDeviceCert is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) IssuedDeviceCert() *MockConnectionManager_IssuedDeviceCert_Call {
	return &MockConnectionManager_IssuedDeviceCert_Call{Call: _e.mock.On("IssuedDeviceCert")}
}

func (_c *MockConnectionManager_IssuedDeviceCert_Call) Run(run func()) *MockConnectionManager_IssuedDeviceCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_IssuedDeviceCert_Call) Return(certificate *x509.Certificate) *MockConnectionManager_IssuedDeviceCert_Call {
	_c.Call.Return(certificate)
	return _c
}

func (_c *MockConnectionManager_IssuedDeviceCert_Call) RunAndReturn(run func() *x509.Certificate) *MockConnectionManager_IssuedDeviceCert_Call {
	_c.Call.Return(run)
	return _c
}

// LastDeviceConnClose provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) LastDeviceConnClose() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastDeviceConnClose")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockConnectionManager_LastDeviceConnClose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastDeviceConnClose'
type MockConnectionManager_LastDeviceConnClose_Call struct {
	*mock.Call
}

// LastDeviceConnClose is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) LastDeviceConnClose() *MockConnectionManager_LastDeviceConnClose_Call {
	return &MockConnectionManager_LastDeviceConnClose_Call{Call: _e.mock.On("LastDeviceConnClose")}
}

func (_c *MockConnectionManager_LastDeviceConnClose_Call) Run(run func()) *MockConnectionManager_LastDeviceConnClose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_LastDeviceConnClose_Call) Return(time1 time.Time) *MockConnectionManager_LastDeviceConnClose_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockConnectionManager_LastDeviceConnClose_Call) RunAndReturn(run func() time.Time) *MockConnectionManager_LastDeviceConnClose_Call {
	_c.Call.Return(run)
	return _c
}

// OperationalTLSConfig provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) OperationalTLSConfig() *tls.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OperationalTLSConfig")
	}

	var r0 *tls.Config
	if returnFunc, ok := ret.Get(0).(func() *tls.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.Config)
		}
	}
	return r0
}

// MockConnectionManager_OperationalTLSConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OperationalTLSConfig'
type MockConnectionManager_OperationalTLSConfig_Call struct {
	*mock.Call
}

// OperationalTLSConfig is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) OperationalTLSConfig() *MockConnectionManager_OperationalTLSConfig_Call {
	return &MockConnectionManager_OperationalTLSConfig_Call{Call: _e.mock.On("OperationalTLSConfig")}
}

func (_c *MockConnectionManager_OperationalTLSConfig_Call) Run(run func()) *MockConnectionManager_OperationalTLSConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_OperationalTLSConfig_Call) Return(config *tls.Config) *MockConnectionManager_OperationalTLSConfig_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *MockConnectionManager_OperationalTLSConfig_Call) RunAndReturn(run func() *tls.Config) *MockConnectionManager_OperationalTLSConfig_Call {
	_c.Call.Return(run)
	return _c
}

// PASEState provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) PASEState() *PASEState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PASEState")
	}

	var r0 *PASEState
	if returnFunc, ok := ret.Get(0).(func() *PASEState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PASEState)
		}
	}
	return r0
}

// MockConnectionManager_PASEState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PASEState'
type MockConnectionManager_PASEState_Call struct {
	*mock.Call
}

// PASEState is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) PASEState() *MockConnectionManager_PASEState_Call {
	return &MockConnectionManager_PASEState_Call{Call: _e.mock.On("PASEState")}
}

func (_c *MockConnectionManager_PASEState_Call) Run(run func()) *MockConnectionManager_PASEState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_PASEState_Call) Return(pASEState *PASEState) *MockConnectionManager_PASEState_Call {
	_c.Call.Return(pASEState)
	return _c
}

func (_c *MockConnectionManager_PASEState_Call) RunAndReturn(run func() *PASEState) *MockConnectionManager_PASEState_Call {
	_c.Call.Return(run)
	return _c
}

// ProbeSessionHealth provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) ProbeSessionHealth() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProbeSessionHealth")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionManager_ProbeSessionHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProbeSessionHealth'
type MockConnectionManager_ProbeSessionHealth_Call struct {
	*mock.Call
}

// ProbeSessionHealth is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) ProbeSessionHealth() *MockConnectionManager_ProbeSessionHealth_Call {
	return &MockConnectionManager_ProbeSessionHealth_Call{Call: _e.mock.On("ProbeSessionHealth")}
}

func (_c *MockConnectionManager_ProbeSessionHealth_Call) Run(run func()) *MockConnectionManager_ProbeSessionHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_ProbeSessionHealth_Call) Return(err error) *MockConnectionManager_ProbeSessionHealth_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionManager_ProbeSessionHealth_Call) RunAndReturn(run func() error) *MockConnectionManager_ProbeSessionHealth_Call {
	_c.Call.Return(run)
	return _c
}

// ReconnectToZone provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) ReconnectToZone(state *engine.ExecutionState) error {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for ReconnectToZone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*engine.ExecutionState) error); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionManager_ReconnectToZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconnectToZone'
type MockConnectionManager_ReconnectToZone_Call struct {
	*mock.Call
}

// ReconnectToZone is a helper method to define mock.On call
//   - state *engine.ExecutionState
func (_e *MockConnectionManager_Expecter) ReconnectToZone(state interface{}) *MockConnectionManager_ReconnectToZone_Call {
	return &MockConnectionManager_ReconnectToZone_Call{Call: _e.mock.On("ReconnectToZone", state)}
}

func (_c *MockConnectionManager_ReconnectToZone_Call) Run(run func(state *engine.ExecutionState)) *MockConnectionManager_ReconnectToZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *engine.ExecutionState
		if args[0] != nil {
			arg0 = args[0].(*engine.ExecutionState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_ReconnectToZone_Call) Return(err error) *MockConnectionManager_ReconnectToZone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionManager_ReconnectToZone_Call) RunAndReturn(run func(state *engine.ExecutionState) error) *MockConnectionManager_ReconnectToZone_Call {
	_c.Call.Return(run)
	return _c
}

// SetCommissionZoneType provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) SetCommissionZoneType(zt cert.ZoneType) {
	_mock.Called(zt)
	return
}

// MockConnectionManager_SetCommissionZoneType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCommissionZoneType'
type MockConnectionManager_SetCommissionZoneType_Call struct {
	*mock.Call
}

// SetCommissionZoneType is a helper method to define mock.On call
//   - zt cert.ZoneType
func (_e *MockConnectionManager_Expecter) SetCommissionZoneType(zt interface{}) *MockConnectionManager_SetCommissionZoneType_Call {
	return &MockConnectionManager_SetCommissionZoneType_Call{Call: _e.mock.On("SetCommissionZoneType", zt)}
}

func (_c *MockConnectionManager_SetCommissionZoneType_Call) Run(run func(zt cert.ZoneType)) *MockConnectionManager_SetCommissionZoneType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cert.ZoneType
		if args[0] != nil {
			arg0 = args[0].(cert.ZoneType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_SetCommissionZoneType_Call) Return() *MockConnectionManager_SetCommissionZoneType_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_SetCommissionZoneType_Call) RunAndReturn(run func(zt cert.ZoneType)) *MockConnectionManager_SetCommissionZoneType_Call {
	_c.Run(run)
	return _c
}

// SetControllerCert provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) SetControllerCert(c *cert.OperationalCert) {
	_mock.Called(c)
	return
}

// MockConnectionManager_SetControllerCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetControllerCert'
type MockConnectionManager_SetControllerCert_Call struct {
	*mock.Call
}

// SetControllerCert is a helper method to define mock.On call
//   - c *cert.OperationalCert
func (_e *MockConnectionManager_Expecter) SetControllerCert(c interface{}) *MockConnectionManager_SetControllerCert_Call {
	return &MockConnectionManager_SetControllerCert_Call{Call: _e.mock.On("SetControllerCert", c)}
}

func (_c *MockConnectionManager_SetControllerCert_Call) Run(run func(c *cert.OperationalCert)) *MockConnectionManager_SetControllerCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *cert.OperationalCert
		if args[0] != nil {
			arg0 = args[0].(*cert.OperationalCert)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_SetControllerCert_Call) Return() *MockConnectionManager_SetControllerCert_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_SetControllerCert_Call) RunAndReturn(run func(c *cert.OperationalCert)) *MockConnectionManager_SetControllerCert_Call {
	_c.Run(run)
	return _c
}

// SetDeviceStateModified provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) SetDeviceStateModified(modified bool) {
	_mock.Called(modified)
	return
}

// MockConnectionManager_SetDeviceStateModified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDeviceStateModified'
type MockConnectionManager_SetDeviceStateModified_Call struct {
	*mock.Call
}

// SetDeviceStateModified is a helper method to define mock.On call
//   - modified bool
func (_e *MockConnectionManager_Expecter) SetDeviceStateModified(modified interface{}) *MockConnectionManager_SetDeviceStateModified_Call {
	return &MockConnectionManager_SetDeviceStateModified_Call{Call: _e.mock.On("SetDeviceStateModified", modified)}
}

func (_c *MockConnectionManager_SetDeviceStateModified_Call) Run(run func(modified bool)) *MockConnectionManager_SetDeviceStateModified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_SetDeviceStateModified_Call) Return() *MockConnectionManager_SetDeviceStateModified_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_SetDeviceStateModified_Call) RunAndReturn(run func(modified bool)) *MockConnectionManager_SetDeviceStateModified_Call {
	_c.Run(run)
	return _c
}

// SetDiscoveredDiscriminator provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) SetDiscoveredDiscriminator(d uint16) {
	_mock.Called(d)
	return
}

// MockConnectionManager_SetDiscoveredDiscriminator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDiscoveredDiscriminator'
type MockConnectionManager_SetDiscoveredDiscriminator_Call struct {
	*mock.Call
}

// SetDiscoveredDiscriminator is a helper method to define mock.On call
//   - d uint16
func (_e *MockConnectionManager_Expecter) SetDiscoveredDiscriminator(d interface{}) *MockConnectionManager_SetDiscoveredDiscriminator_Call {
	return &MockConnectionManager_SetDiscoveredDiscriminator_Call{Call: _e.mock.On("SetDiscoveredDiscriminator", d)}
}

func (_c *MockConnectionManager_SetDiscoveredDiscriminator_Call) Run(run func(d uint16)) *MockConnectionManager_SetDiscoveredDiscriminator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint16
		if args[0] != nil {
			arg0 = args[0].(uint16)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_SetDiscoveredDiscriminator_Call) Return() *MockConnectionManager_SetDiscoveredDiscriminator_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_SetDiscoveredDiscriminator_Call) RunAndReturn(run func(d uint16)) *MockConnectionManager_SetDiscoveredDiscriminator_Call {
	_c.Run(run)
	return _c
}

// SetIssuedDeviceCert provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) SetIssuedDeviceCert(c *x509.Certificate) {
	_mock.Called(c)
	return
}

// MockConnectionManager_SetIssuedDeviceCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIssuedDeviceCert'
type MockConnectionManager_SetIssuedDeviceCert_Call struct {
	*mock.Call
}

// SetIssuedDeviceCert is a helper method to define mock.On call
//   - c *x509.Certificate
func (_e *MockConnectionManager_Expecter) SetIssuedDeviceCert(c interface{}) *MockConnectionManager_SetIssuedDeviceCert_Call {
	return &MockConnectionManager_SetIssuedDeviceCert_Call{Call: _e.mock.On("SetIssuedDeviceCert", c)}
}

func (_c *MockConnectionManager_SetIssuedDeviceCert_Call) Run(run func(c *x509.Certificate)) *MockConnectionManager_SetIssuedDeviceCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *x509.Certificate
		if args[0] != nil {
			arg0 = args[0].(*x509.Certificate)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_SetIssuedDeviceCert_Call) Return() *MockConnectionManager_SetIssuedDeviceCert_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_SetIssuedDeviceCert_Call) RunAndReturn(run func(c *x509.Certificate)) *MockConnectionManager_SetIssuedDeviceCert_Call {
	_c.Run(run)
	return _c
}

// SetLastDeviceConnClose provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) SetLastDeviceConnClose(t time.Time) {
	_mock.Called(t)
	return
}

// MockConnectionManager_SetLastDeviceConnClose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLastDeviceConnClose'
type MockConnectionManager_SetLastDeviceConnClose_Call struct {
	*mock.Call
}

// SetLastDeviceConnClose is a helper method to define mock.On call
//   - t time.Time
func (_e *MockConnectionManager_Expecter) SetLastDeviceConnClose(t interface{}) *MockConnectionManager_SetLastDeviceConnClose_Call {
	return &MockConnectionManager_SetLastDeviceConnClose_Call{Call: _e.mock.On("SetLastDeviceConnClose", t)}
}

func (_c *MockConnectionManager_SetLastDeviceConnClose_Call) Run(run func(t time.Time)) *MockConnectionManager_SetLastDeviceConnClose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_SetLastDeviceConnClose_Call) Return() *MockConnectionManager_SetLastDeviceConnClose_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_SetLastDeviceConnClose_Call) RunAndReturn(run func(t time.Time)) *MockConnectionManager_SetLastDeviceConnClose_Call {
	_c.Run(run)
	return _c
}

// SetPASEState provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) SetPASEState(ps *PASEState) {
	_mock.Called(ps)
	return
}

// MockConnectionManager_SetPASEState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPASEState'
type MockConnectionManager_SetPASEState_Call struct {
	*mock.Call
}

// SetPASEState is a helper method to define mock.On call
//   - ps *PASEState
func (_e *MockConnectionManager_Expecter) SetPASEState(ps interface{}) *MockConnectionManager_SetPASEState_Call {
	return &MockConnectionManager_SetPASEState_Call{Call: _e.mock.On("SetPASEState", ps)}
}

func (_c *MockConnectionManager_SetPASEState_Call) Run(run func(ps *PASEState)) *MockConnectionManager_SetPASEState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *PASEState
		if args[0] != nil {
			arg0 = args[0].(*PASEState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_SetPASEState_Call) Return() *MockConnectionManager_SetPASEState_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_SetPASEState_Call) RunAndReturn(run func(ps *PASEState)) *MockConnectionManager_SetPASEState_Call {
	_c.Run(run)
	return _c
}

// SetWorkingCrypto provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) SetWorkingCrypto(crypto CryptoState) {
	_mock.Called(crypto)
	return
}

// MockConnectionManager_SetWorkingCrypto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWorkingCrypto'
type MockConnectionManager_SetWorkingCrypto_Call struct {
	*mock.Call
}

// SetWorkingCrypto is a helper method to define mock.On call
//   - crypto CryptoState
func (_e *MockConnectionManager_Expecter) SetWorkingCrypto(crypto interface{}) *MockConnectionManager_SetWorkingCrypto_Call {
	return &MockConnectionManager_SetWorkingCrypto_Call{Call: _e.mock.On("SetWorkingCrypto", crypto)}
}

func (_c *MockConnectionManager_SetWorkingCrypto_Call) Run(run func(crypto CryptoState)) *MockConnectionManager_SetWorkingCrypto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 CryptoState
		if args[0] != nil {
			arg0 = args[0].(CryptoState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_SetWorkingCrypto_Call) Return() *MockConnectionManager_SetWorkingCrypto_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_SetWorkingCrypto_Call) RunAndReturn(run func(crypto CryptoState)) *MockConnectionManager_SetWorkingCrypto_Call {
	_c.Run(run)
	return _c
}

// SetZoneCA provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) SetZoneCA(z *cert.ZoneCA) {
	_mock.Called(z)
	return
}

// MockConnectionManager_SetZoneCA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetZoneCA'
type MockConnectionManager_SetZoneCA_Call struct {
	*mock.Call
}

// SetZoneCA is a helper method to define mock.On call
//   - z *cert.ZoneCA
func (_e *MockConnectionManager_Expecter) SetZoneCA(z interface{}) *MockConnectionManager_SetZoneCA_Call {
	return &MockConnectionManager_SetZoneCA_Call{Call: _e.mock.On("SetZoneCA", z)}
}

func (_c *MockConnectionManager_SetZoneCA_Call) Run(run func(z *cert.ZoneCA)) *MockConnectionManager_SetZoneCA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *cert.ZoneCA
		if args[0] != nil {
			arg0 = args[0].(*cert.ZoneCA)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_SetZoneCA_Call) Return() *MockConnectionManager_SetZoneCA_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_SetZoneCA_Call) RunAndReturn(run func(z *cert.ZoneCA)) *MockConnectionManager_SetZoneCA_Call {
	_c.Run(run)
	return _c
}

// SetZoneCAPool provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) SetZoneCAPool(p *x509.CertPool) {
	_mock.Called(p)
	return
}

// MockConnectionManager_SetZoneCAPool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetZoneCAPool'
type MockConnectionManager_SetZoneCAPool_Call struct {
	*mock.Call
}

// SetZoneCAPool is a helper method to define mock.On call
//   - p *x509.CertPool
func (_e *MockConnectionManager_Expecter) SetZoneCAPool(p interface{}) *MockConnectionManager_SetZoneCAPool_Call {
	return &MockConnectionManager_SetZoneCAPool_Call{Call: _e.mock.On("SetZoneCAPool", p)}
}

func (_c *MockConnectionManager_SetZoneCAPool_Call) Run(run func(p *x509.CertPool)) *MockConnectionManager_SetZoneCAPool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *x509.CertPool
		if args[0] != nil {
			arg0 = args[0].(*x509.CertPool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_SetZoneCAPool_Call) Return() *MockConnectionManager_SetZoneCAPool_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_SetZoneCAPool_Call) RunAndReturn(run func(p *x509.CertPool)) *MockConnectionManager_SetZoneCAPool_Call {
	_c.Run(run)
	return _c
}

// TransitionToOperational provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) TransitionToOperational(state *engine.ExecutionState) error {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for TransitionToOperational")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*engine.ExecutionState) error); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionManager_TransitionToOperational_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionToOperational'
type MockConnectionManager_TransitionToOperational_Call struct {
	*mock.Call
}

// TransitionToOperational is a helper method to define mock.On call
//   - state *engine.ExecutionState
func (_e *MockConnectionManager_Expecter) TransitionToOperational(state interface{}) *MockConnectionManager_TransitionToOperational_Call {
	return &MockConnectionManager_TransitionToOperational_Call{Call: _e.mock.On("TransitionToOperational", state)}
}

func (_c *MockConnectionManager_TransitionToOperational_Call) Run(run func(state *engine.ExecutionState)) *MockConnectionManager_TransitionToOperational_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *engine.ExecutionState
		if args[0] != nil {
			arg0 = args[0].(*engine.ExecutionState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_TransitionToOperational_Call) Return(err error) *MockConnectionManager_TransitionToOperational_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionManager_TransitionToOperational_Call) RunAndReturn(run func(state *engine.ExecutionState) error) *MockConnectionManager_TransitionToOperational_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForCommissioningMode provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) WaitForCommissioningMode(ctx context.Context, timeout time.Duration) error {
	ret := _mock.Called(ctx, timeout)

	if len(ret) == 0 {
		panic("no return value specified for WaitForCommissioningMode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) error); ok {
		r0 = returnFunc(ctx, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionManager_WaitForCommissioningMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForCommissioningMode'
type MockConnectionManager_WaitForCommissioningMode_Call struct {
	*mock.Call
}

// WaitForCommissioningMode is a helper method to define mock.On call
//   - ctx context.Context
//   - timeout time.Duration
func (_e *MockConnectionManager_Expecter) WaitForCommissioningMode(ctx interface{}, timeout interface{}) *MockConnectionManager_WaitForCommissioningMode_Call {
	return &MockConnectionManager_WaitForCommissioningMode_Call{Call: _e.mock.On("WaitForCommissioningMode", ctx, timeout)}
}

func (_c *MockConnectionManager_WaitForCommissioningMode_Call) Run(run func(ctx context.Context, timeout time.Duration)) *MockConnectionManager_WaitForCommissioningMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectionManager_WaitForCommissioningMode_Call) Return(err error) *MockConnectionManager_WaitForCommissioningMode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionManager_WaitForCommissioningMode_Call) RunAndReturn(run func(ctx context.Context, timeout time.Duration) error) *MockConnectionManager_WaitForCommissioningMode_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForOperationalReady provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) WaitForOperationalReady(timeout time.Duration) error {
	ret := _mock.Called(timeout)

	if len(ret) == 0 {
		panic("no return value specified for WaitForOperationalReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Duration) error); ok {
		r0 = returnFunc(timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionManager_WaitForOperationalReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForOperationalReady'
type MockConnectionManager_WaitForOperationalReady_Call struct {
	*mock.Call
}

// WaitForOperationalReady is a helper method to define mock.On call
//   - timeout time.Duration
func (_e *MockConnectionManager_Expecter) WaitForOperationalReady(timeout interface{}) *MockConnectionManager_WaitForOperationalReady_Call {
	return &MockConnectionManager_WaitForOperationalReady_Call{Call: _e.mock.On("WaitForOperationalReady", timeout)}
}

func (_c *MockConnectionManager_WaitForOperationalReady_Call) Run(run func(timeout time.Duration)) *MockConnectionManager_WaitForOperationalReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_WaitForOperationalReady_Call) Return(err error) *MockConnectionManager_WaitForOperationalReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionManager_WaitForOperationalReady_Call) RunAndReturn(run func(timeout time.Duration) error) *MockConnectionManager_WaitForOperationalReady_Call {
	_c.Call.Return(run)
	return _c
}

// WorkingCrypto provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) WorkingCrypto() CryptoState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WorkingCrypto")
	}

	var r0 CryptoState
	if returnFunc, ok := ret.Get(0).(func() CryptoState); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(CryptoState)
	}
	return r0
}

// MockConnectionManager_WorkingCrypto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkingCrypto'
type MockConnectionManager_WorkingCrypto_Call struct {
	*mock.Call
}

// WorkingCrypto is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) WorkingCrypto() *MockConnectionManager_WorkingCrypto_Call {
	return &MockConnectionManager_WorkingCrypto_Call{Call: _e.mock.On("WorkingCrypto")}
}

func (_c *MockConnectionManager_WorkingCrypto_Call) Run(run func()) *MockConnectionManager_WorkingCrypto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_WorkingCrypto_Call) Return(cryptoState CryptoState) *MockConnectionManager_WorkingCrypto_Call {
	_c.Call.Return(cryptoState)
	return _c
}

func (_c *MockConnectionManager_WorkingCrypto_Call) RunAndReturn(run func() CryptoState) *MockConnectionManager_WorkingCrypto_Call {
	_c.Call.Return(run)
	return _c
}

// ZoneCA provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) ZoneCA() *cert.ZoneCA {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ZoneCA")
	}

	var r0 *cert.ZoneCA
	if returnFunc, ok := ret.Get(0).(func() *cert.ZoneCA); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cert.ZoneCA)
		}
	}
	return r0
}

// MockConnectionManager_ZoneCA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZoneCA'
type MockConnectionManager_ZoneCA_Call struct {
	*mock.Call
}

// ZoneCA is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) ZoneCA() *MockConnectionManager_ZoneCA_Call {
	return &MockConnectionManager_ZoneCA_Call{Call: _e.mock.On("ZoneCA")}
}

func (_c *MockConnectionManager_ZoneCA_Call) Run(run func()) *MockConnectionManager_ZoneCA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_ZoneCA_Call) Return(zoneCA *cert.ZoneCA) *MockConnectionManager_ZoneCA_Call {
	_c.Call.Return(zoneCA)
	return _c
}

func (_c *MockConnectionManager_ZoneCA_Call) RunAndReturn(run func() *cert.ZoneCA) *MockConnectionManager_ZoneCA_Call {
	_c.Call.Return(run)
	return _c
}

// ZoneCAPool provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) ZoneCAPool() *x509.CertPool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ZoneCAPool")
	}

	var r0 *x509.CertPool
	if returnFunc, ok := ret.Get(0).(func() *x509.CertPool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*x509.CertPool)
		}
	}
	return r0
}

// MockConnectionManager_ZoneCAPool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZoneCAPool'
type MockConnectionManager_ZoneCAPool_Call struct {
	*mock.Call
}

// ZoneCAPool is a helper method to define mock.On call
func (_e *MockConnectionManager_Expecter) ZoneCAPool() *MockConnectionManager_ZoneCAPool_Call {
	return &MockConnectionManager_ZoneCAPool_Call{Call: _e.mock.On("ZoneCAPool")}
}

func (_c *MockConnectionManager_ZoneCAPool_Call) Run(run func()) *MockConnectionManager_ZoneCAPool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionManager_ZoneCAPool_Call) Return(certPool *x509.CertPool) *MockConnectionManager_ZoneCAPool_Call {
	_c.Call.Return(certPool)
	return _c
}

func (_c *MockConnectionManager_ZoneCAPool_Call) RunAndReturn(run func() *x509.CertPool) *MockConnectionManager_ZoneCAPool_Call {
	_c.Call.Return(run)
	return _c
}
