// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runner

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConnLifecycle creates a new instance of MockConnLifecycle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnLifecycle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnLifecycle {
	mock := &MockConnLifecycle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnLifecycle is an autogenerated mock type for the ConnLifecycle type
type MockConnLifecycle struct {
	mock.Mock
}

type MockConnLifecycle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnLifecycle) EXPECT() *MockConnLifecycle_Expecter {
	return &MockConnLifecycle_Expecter{mock: &_m.Mock}
}

// CloseAllZones provides a mock function for the type MockConnLifecycle
func (_mock *MockConnLifecycle) CloseAllZones() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseAllZones")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockConnLifecycle_CloseAllZones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAllZones'
type MockConnLifecycle_CloseAllZones_Call struct {
	*mock.Call
}

// CloseAllZones is a helper method to define mock.On call
func (_e *MockConnLifecycle_Expecter) CloseAllZones() *MockConnLifecycle_CloseAllZones_Call {
	return &MockConnLifecycle_CloseAllZones_Call{Call: _e.mock.On("CloseAllZones")}
}

func (_c *MockConnLifecycle_CloseAllZones_Call) Run(run func()) *MockConnLifecycle_CloseAllZones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnLifecycle_CloseAllZones_Call) Return(time1 time.Time) *MockConnLifecycle_CloseAllZones_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockConnLifecycle_CloseAllZones_Call) RunAndReturn(run func() time.Time) *MockConnLifecycle_CloseAllZones_Call {
	_c.Call.Return(run)
	return _c
}

// CloseZonesExcept provides a mock function for the type MockConnLifecycle
func (_mock *MockConnLifecycle) CloseZonesExcept(exceptKey string) time.Time {
	ret := _mock.Called(exceptKey)

	if len(ret) == 0 {
		panic("no return value specified for CloseZonesExcept")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = returnFunc(exceptKey)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockConnLifecycle_CloseZonesExcept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseZonesExcept'
type MockConnLifecycle_CloseZonesExcept_Call struct {
	*mock.Call
}

// CloseZonesExcept is a helper method to define mock.On call
//   - exceptKey string
func (_e *MockConnLifecycle_Expecter) CloseZonesExcept(exceptKey interface{}) *MockConnLifecycle_CloseZonesExcept_Call {
	return &MockConnLifecycle_CloseZonesExcept_Call{Call: _e.mock.On("CloseZonesExcept", exceptKey)}
}

func (_c *MockConnLifecycle_CloseZonesExcept_Call) Run(run func(exceptKey string)) *MockConnLifecycle_CloseZonesExcept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnLifecycle_CloseZonesExcept_Call) Return(time1 time.Time) *MockConnLifecycle_CloseZonesExcept_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockConnLifecycle_CloseZonesExcept_Call) RunAndReturn(run func(exceptKey string) time.Time) *MockConnLifecycle_CloseZonesExcept_Call {
	_c.Call.Return(run)
	return _c
}

// UnsubscribeAll provides a mock function for the type MockConnLifecycle
func (_mock *MockConnLifecycle) UnsubscribeAll(conn *Connection) {
	_mock.Called(conn)
	return
}

// MockConnLifecycle_UnsubscribeAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsubscribeAll'
type MockConnLifecycle_UnsubscribeAll_Call struct {
	*mock.Call
}

// UnsubscribeAll is a helper method to define mock.On call
//   - conn *Connection
func (_e *MockConnLifecycle_Expecter) UnsubscribeAll(conn interface{}) *MockConnLifecycle_UnsubscribeAll_Call {
	return &MockConnLifecycle_UnsubscribeAll_Call{Call: _e.mock.On("UnsubscribeAll", conn)}
}

func (_c *MockConnLifecycle_UnsubscribeAll_Call) Run(run func(conn *Connection)) *MockConnLifecycle_UnsubscribeAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Connection
		if args[0] != nil {
			arg0 = args[0].(*Connection)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnLifecycle_UnsubscribeAll_Call) Return() *MockConnLifecycle_UnsubscribeAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnLifecycle_UnsubscribeAll_Call) RunAndReturn(run func(conn *Connection)) *MockConnLifecycle_UnsubscribeAll_Call {
	_c.Run(run)
	return _c
}
