// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runner

import (
	"time"

	"github.com/mash-protocol/mash-go/pkg/cert"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStateAccessor creates a new instance of MockStateAccessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateAccessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateAccessor {
	mock := &MockStateAccessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStateAccessor is an autogenerated mock type for the StateAccessor type
type MockStateAccessor struct {
	mock.Mock
}

type MockStateAccessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateAccessor) EXPECT() *MockStateAccessor_Expecter {
	return &MockStateAccessor_Expecter{mock: &_m.Mock}
}

// ClearWorkingCrypto provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) ClearWorkingCrypto() {
	_mock.Called()
	return
}

// MockStateAccessor_ClearWorkingCrypto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearWorkingCrypto'
type MockStateAccessor_ClearWorkingCrypto_Call struct {
	*mock.Call
}

// ClearWorkingCrypto is a helper method to define mock.On call
func (_e *MockStateAccessor_Expecter) ClearWorkingCrypto() *MockStateAccessor_ClearWorkingCrypto_Call {
	return &MockStateAccessor_ClearWorkingCrypto_Call{Call: _e.mock.On("ClearWorkingCrypto")}
}

func (_c *MockStateAccessor_ClearWorkingCrypto_Call) Run(run func()) *MockStateAccessor_ClearWorkingCrypto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateAccessor_ClearWorkingCrypto_Call) Return() *MockStateAccessor_ClearWorkingCrypto_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStateAccessor_ClearWorkingCrypto_Call) RunAndReturn(run func()) *MockStateAccessor_ClearWorkingCrypto_Call {
	_c.Run(run)
	return _c
}

// CommissionZoneType provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) CommissionZoneType() cert.ZoneType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CommissionZoneType")
	}

	var r0 cert.ZoneType
	if returnFunc, ok := ret.Get(0).(func() cert.ZoneType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(cert.ZoneType)
	}
	return r0
}

// MockStateAccessor_CommissionZoneType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommissionZoneType'
type MockStateAccessor_CommissionZoneType_Call struct {
	*mock.Call
}

// CommissionZoneType is a helper method to define mock.On call
func (_e *MockStateAccessor_Expecter) CommissionZoneType() *MockStateAccessor_CommissionZoneType_Call {
	return &MockStateAccessor_CommissionZoneType_Call{Call: _e.mock.On("CommissionZoneType")}
}

func (_c *MockStateAccessor_CommissionZoneType_Call) Run(run func()) *MockStateAccessor_CommissionZoneType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateAccessor_CommissionZoneType_Call) Return(zoneType cert.ZoneType) *MockStateAccessor_CommissionZoneType_Call {
	_c.Call.Return(zoneType)
	return _c
}

func (_c *MockStateAccessor_CommissionZoneType_Call) RunAndReturn(run func() cert.ZoneType) *MockStateAccessor_CommissionZoneType_Call {
	_c.Call.Return(run)
	return _c
}

// DeviceStateModified provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) DeviceStateModified() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeviceStateModified")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockStateAccessor_DeviceStateModified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeviceStateModified'
type MockStateAccessor_DeviceStateModified_Call struct {
	*mock.Call
}

// DeviceStateModified is a helper method to define mock.On call
func (_e *MockStateAccessor_Expecter) DeviceStateModified() *MockStateAccessor_DeviceStateModified_Call {
	return &MockStateAccessor_DeviceStateModified_Call{Call: _e.mock.On("DeviceStateModified")}
}

func (_c *MockStateAccessor_DeviceStateModified_Call) Run(run func()) *MockStateAccessor_DeviceStateModified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateAccessor_DeviceStateModified_Call) Return(b bool) *MockStateAccessor_DeviceStateModified_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockStateAccessor_DeviceStateModified_Call) RunAndReturn(run func() bool) *MockStateAccessor_DeviceStateModified_Call {
	_c.Call.Return(run)
	return _c
}

// DiscoveredDiscriminator provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) DiscoveredDiscriminator() uint16 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DiscoveredDiscriminator")
	}

	var r0 uint16
	if returnFunc, ok := ret.Get(0).(func() uint16); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint16)
	}
	return r0
}

// MockStateAccessor_DiscoveredDiscriminator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoveredDiscriminator'
type MockStateAccessor_DiscoveredDiscriminator_Call struct {
	*mock.Call
}

// DiscoveredDiscriminator is a helper method to define mock.On call
func (_e *MockStateAccessor_Expecter) DiscoveredDiscriminator() *MockStateAccessor_DiscoveredDiscriminator_Call {
	return &MockStateAccessor_DiscoveredDiscriminator_Call{Call: _e.mock.On("DiscoveredDiscriminator")}
}

func (_c *MockStateAccessor_DiscoveredDiscriminator_Call) Run(run func()) *MockStateAccessor_DiscoveredDiscriminator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateAccessor_DiscoveredDiscriminator_Call) Return(v uint16) *MockStateAccessor_DiscoveredDiscriminator_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockStateAccessor_DiscoveredDiscriminator_Call) RunAndReturn(run func() uint16) *MockStateAccessor_DiscoveredDiscriminator_Call {
	_c.Call.Return(run)
	return _c
}

// IsSuiteZoneCommission provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) IsSuiteZoneCommission() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsSuiteZoneCommission")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockStateAccessor_IsSuiteZoneCommission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSuiteZoneCommission'
type MockStateAccessor_IsSuiteZoneCommission_Call struct {
	*mock.Call
}

// IsSuiteZoneCommission is a helper method to define mock.On call
func (_e *MockStateAccessor_Expecter) IsSuiteZoneCommission() *MockStateAccessor_IsSuiteZoneCommission_Call {
	return &MockStateAccessor_IsSuiteZoneCommission_Call{Call: _e.mock.On("IsSuiteZoneCommission")}
}

func (_c *MockStateAccessor_IsSuiteZoneCommission_Call) Run(run func()) *MockStateAccessor_IsSuiteZoneCommission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateAccessor_IsSuiteZoneCommission_Call) Return(b bool) *MockStateAccessor_IsSuiteZoneCommission_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockStateAccessor_IsSuiteZoneCommission_Call) RunAndReturn(run func() bool) *MockStateAccessor_IsSuiteZoneCommission_Call {
	_c.Call.Return(run)
	return _c
}

// LastDeviceConnClose provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) LastDeviceConnClose() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastDeviceConnClose")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockStateAccessor_LastDeviceConnClose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastDeviceConnClose'
type MockStateAccessor_LastDeviceConnClose_Call struct {
	*mock.Call
}

// LastDeviceConnClose is a helper method to define mock.On call
func (_e *MockStateAccessor_Expecter) LastDeviceConnClose() *MockStateAccessor_LastDeviceConnClose_Call {
	return &MockStateAccessor_LastDeviceConnClose_Call{Call: _e.mock.On("LastDeviceConnClose")}
}

func (_c *MockStateAccessor_LastDeviceConnClose_Call) Run(run func()) *MockStateAccessor_LastDeviceConnClose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateAccessor_LastDeviceConnClose_Call) Return(time1 time.Time) *MockStateAccessor_LastDeviceConnClose_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockStateAccessor_LastDeviceConnClose_Call) RunAndReturn(run func() time.Time) *MockStateAccessor_LastDeviceConnClose_Call {
	_c.Call.Return(run)
	return _c
}

// PASEState provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) PASEState() *PASEState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PASEState")
	}

	var r0 *PASEState
	if returnFunc, ok := ret.Get(0).(func() *PASEState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PASEState)
		}
	}
	return r0
}

// MockStateAccessor_PASEState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PASEState'
type MockStateAccessor_PASEState_Call struct {
	*mock.Call
}

// PASEState is a helper method to define mock.On call
func (_e *MockStateAccessor_Expecter) PASEState() *MockStateAccessor_PASEState_Call {
	return &MockStateAccessor_PASEState_Call{Call: _e.mock.On("PASEState")}
}

func (_c *MockStateAccessor_PASEState_Call) Run(run func()) *MockStateAccessor_PASEState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateAccessor_PASEState_Call) Return(pASEState *PASEState) *MockStateAccessor_PASEState_Call {
	_c.Call.Return(pASEState)
	return _c
}

func (_c *MockStateAccessor_PASEState_Call) RunAndReturn(run func() *PASEState) *MockStateAccessor_PASEState_Call {
	_c.Call.Return(run)
	return _c
}

// SetCommissionZoneType provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) SetCommissionZoneType(zt cert.ZoneType) {
	_mock.Called(zt)
	return
}

// MockStateAccessor_SetCommissionZoneType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCommissionZoneType'
type MockStateAccessor_SetCommissionZoneType_Call struct {
	*mock.Call
}

// SetCommissionZoneType is a helper method to define mock.On call
//   - zt cert.ZoneType
func (_e *MockStateAccessor_Expecter) SetCommissionZoneType(zt interface{}) *MockStateAccessor_SetCommissionZoneType_Call {
	return &MockStateAccessor_SetCommissionZoneType_Call{Call: _e.mock.On("SetCommissionZoneType", zt)}
}

func (_c *MockStateAccessor_SetCommissionZoneType_Call) Run(run func(zt cert.ZoneType)) *MockStateAccessor_SetCommissionZoneType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cert.ZoneType
		if args[0] != nil {
			arg0 = args[0].(cert.ZoneType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStateAccessor_SetCommissionZoneType_Call) Return() *MockStateAccessor_SetCommissionZoneType_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStateAccessor_SetCommissionZoneType_Call) RunAndReturn(run func(zt cert.ZoneType)) *MockStateAccessor_SetCommissionZoneType_Call {
	_c.Run(run)
	return _c
}

// SetDeviceStateModified provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) SetDeviceStateModified(modified bool) {
	_mock.Called(modified)
	return
}

// MockStateAccessor_SetDeviceStateModified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDeviceStateModified'
type MockStateAccessor_SetDeviceStateModified_Call struct {
	*mock.Call
}

// SetDeviceStateModified is a helper method to define mock.On call
//   - modified bool
func (_e *MockStateAccessor_Expecter) SetDeviceStateModified(modified interface{}) *MockStateAccessor_SetDeviceStateModified_Call {
	return &MockStateAccessor_SetDeviceStateModified_Call{Call: _e.mock.On("SetDeviceStateModified", modified)}
}

func (_c *MockStateAccessor_SetDeviceStateModified_Call) Run(run func(modified bool)) *MockStateAccessor_SetDeviceStateModified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStateAccessor_SetDeviceStateModified_Call) Return() *MockStateAccessor_SetDeviceStateModified_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStateAccessor_SetDeviceStateModified_Call) RunAndReturn(run func(modified bool)) *MockStateAccessor_SetDeviceStateModified_Call {
	_c.Run(run)
	return _c
}

// SetLastDeviceConnClose provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) SetLastDeviceConnClose(t time.Time) {
	_mock.Called(t)
	return
}

// MockStateAccessor_SetLastDeviceConnClose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLastDeviceConnClose'
type MockStateAccessor_SetLastDeviceConnClose_Call struct {
	*mock.Call
}

// SetLastDeviceConnClose is a helper method to define mock.On call
//   - t time.Time
func (_e *MockStateAccessor_Expecter) SetLastDeviceConnClose(t interface{}) *MockStateAccessor_SetLastDeviceConnClose_Call {
	return &MockStateAccessor_SetLastDeviceConnClose_Call{Call: _e.mock.On("SetLastDeviceConnClose", t)}
}

func (_c *MockStateAccessor_SetLastDeviceConnClose_Call) Run(run func(t time.Time)) *MockStateAccessor_SetLastDeviceConnClose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStateAccessor_SetLastDeviceConnClose_Call) Return() *MockStateAccessor_SetLastDeviceConnClose_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStateAccessor_SetLastDeviceConnClose_Call) RunAndReturn(run func(t time.Time)) *MockStateAccessor_SetLastDeviceConnClose_Call {
	_c.Run(run)
	return _c
}

// SetPASEState provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) SetPASEState(ps *PASEState) {
	_mock.Called(ps)
	return
}

// MockStateAccessor_SetPASEState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPASEState'
type MockStateAccessor_SetPASEState_Call struct {
	*mock.Call
}

// SetPASEState is a helper method to define mock.On call
//   - ps *PASEState
func (_e *MockStateAccessor_Expecter) SetPASEState(ps interface{}) *MockStateAccessor_SetPASEState_Call {
	return &MockStateAccessor_SetPASEState_Call{Call: _e.mock.On("SetPASEState", ps)}
}

func (_c *MockStateAccessor_SetPASEState_Call) Run(run func(ps *PASEState)) *MockStateAccessor_SetPASEState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *PASEState
		if args[0] != nil {
			arg0 = args[0].(*PASEState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStateAccessor_SetPASEState_Call) Return() *MockStateAccessor_SetPASEState_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStateAccessor_SetPASEState_Call) RunAndReturn(run func(ps *PASEState)) *MockStateAccessor_SetPASEState_Call {
	_c.Run(run)
	return _c
}

// SetWorkingCrypto provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) SetWorkingCrypto(crypto CryptoState) {
	_mock.Called(crypto)
	return
}

// MockStateAccessor_SetWorkingCrypto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWorkingCrypto'
type MockStateAccessor_SetWorkingCrypto_Call struct {
	*mock.Call
}

// SetWorkingCrypto is a helper method to define mock.On call
//   - crypto CryptoState
func (_e *MockStateAccessor_Expecter) SetWorkingCrypto(crypto interface{}) *MockStateAccessor_SetWorkingCrypto_Call {
	return &MockStateAccessor_SetWorkingCrypto_Call{Call: _e.mock.On("SetWorkingCrypto", crypto)}
}

func (_c *MockStateAccessor_SetWorkingCrypto_Call) Run(run func(crypto CryptoState)) *MockStateAccessor_SetWorkingCrypto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 CryptoState
		if args[0] != nil {
			arg0 = args[0].(CryptoState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStateAccessor_SetWorkingCrypto_Call) Return() *MockStateAccessor_SetWorkingCrypto_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStateAccessor_SetWorkingCrypto_Call) RunAndReturn(run func(crypto CryptoState)) *MockStateAccessor_SetWorkingCrypto_Call {
	_c.Run(run)
	return _c
}

// WorkingCrypto provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) WorkingCrypto() CryptoState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WorkingCrypto")
	}

	var r0 CryptoState
	if returnFunc, ok := ret.Get(0).(func() CryptoState); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(CryptoState)
	}
	return r0
}

// MockStateAccessor_WorkingCrypto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkingCrypto'
type MockStateAccessor_WorkingCrypto_Call struct {
	*mock.Call
}

// WorkingCrypto is a helper method to define mock.On call
func (_e *MockStateAccessor_Expecter) WorkingCrypto() *MockStateAccessor_WorkingCrypto_Call {
	return &MockStateAccessor_WorkingCrypto_Call{Call: _e.mock.On("WorkingCrypto")}
}

func (_c *MockStateAccessor_WorkingCrypto_Call) Run(run func()) *MockStateAccessor_WorkingCrypto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateAccessor_WorkingCrypto_Call) Return(cryptoState CryptoState) *MockStateAccessor_WorkingCrypto_Call {
	_c.Call.Return(cryptoState)
	return _c
}

func (_c *MockStateAccessor_WorkingCrypto_Call) RunAndReturn(run func() CryptoState) *MockStateAccessor_WorkingCrypto_Call {
	_c.Call.Return(run)
	return _c
}
