// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runner

import (
	"context"

	"github.com/mash-protocol/mash-go/internal/testharness/engine"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLifecycleOps creates a new instance of MockLifecycleOps. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLifecycleOps(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLifecycleOps {
	mock := &MockLifecycleOps{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLifecycleOps is an autogenerated mock type for the LifecycleOps type
type MockLifecycleOps struct {
	mock.Mock
}

type MockLifecycleOps_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLifecycleOps) EXPECT() *MockLifecycleOps_Expecter {
	return &MockLifecycleOps_Expecter{mock: &_m.Mock}
}

// DisconnectConnection provides a mock function for the type MockLifecycleOps
func (_mock *MockLifecycleOps) DisconnectConnection() {
	_mock.Called()
	return
}

// MockLifecycleOps_DisconnectConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectConnection'
type MockLifecycleOps_DisconnectConnection_Call struct {
	*mock.Call
}

// DisconnectConnection is a helper method to define mock.On call
func (_e *MockLifecycleOps_Expecter) DisconnectConnection() *MockLifecycleOps_DisconnectConnection_Call {
	return &MockLifecycleOps_DisconnectConnection_Call{Call: _e.mock.On("DisconnectConnection")}
}

func (_c *MockLifecycleOps_DisconnectConnection_Call) Run(run func()) *MockLifecycleOps_DisconnectConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLifecycleOps_DisconnectConnection_Call) Return() *MockLifecycleOps_DisconnectConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLifecycleOps_DisconnectConnection_Call) RunAndReturn(run func()) *MockLifecycleOps_DisconnectConnection_Call {
	_c.Run(run)
	return _c
}

// EnsureCommissioned provides a mock function for the type MockLifecycleOps
func (_mock *MockLifecycleOps) EnsureCommissioned(ctx context.Context, state *engine.ExecutionState) error {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for EnsureCommissioned")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *engine.ExecutionState) error); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLifecycleOps_EnsureCommissioned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureCommissioned'
type MockLifecycleOps_EnsureCommissioned_Call struct {
	*mock.Call
}

// EnsureCommissioned is a helper method to define mock.On call
//   - ctx context.Context
//   - state *engine.ExecutionState
func (_e *MockLifecycleOps_Expecter) EnsureCommissioned(ctx interface{}, state interface{}) *MockLifecycleOps_EnsureCommissioned_Call {
	return &MockLifecycleOps_EnsureCommissioned_Call{Call: _e.mock.On("EnsureCommissioned", ctx, state)}
}

func (_c *MockLifecycleOps_EnsureCommissioned_Call) Run(run func(ctx context.Context, state *engine.ExecutionState)) *MockLifecycleOps_EnsureCommissioned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *engine.ExecutionState
		if args[1] != nil {
			arg1 = args[1].(*engine.ExecutionState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLifecycleOps_EnsureCommissioned_Call) Return(err error) *MockLifecycleOps_EnsureCommissioned_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLifecycleOps_EnsureCommissioned_Call) RunAndReturn(run func(ctx context.Context, state *engine.ExecutionState) error) *MockLifecycleOps_EnsureCommissioned_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureConnected provides a mock function for the type MockLifecycleOps
func (_mock *MockLifecycleOps) EnsureConnected(ctx context.Context, state *engine.ExecutionState) error {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for EnsureConnected")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *engine.ExecutionState) error); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLifecycleOps_EnsureConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureConnected'
type MockLifecycleOps_EnsureConnected_Call struct {
	*mock.Call
}

// EnsureConnected is a helper method to define mock.On call
//   - ctx context.Context
//   - state *engine.ExecutionState
func (_e *MockLifecycleOps_Expecter) EnsureConnected(ctx interface{}, state interface{}) *MockLifecycleOps_EnsureConnected_Call {
	return &MockLifecycleOps_EnsureConnected_Call{Call: _e.mock.On("EnsureConnected", ctx, state)}
}

func (_c *MockLifecycleOps_EnsureConnected_Call) Run(run func(ctx context.Context, state *engine.ExecutionState)) *MockLifecycleOps_EnsureConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *engine.ExecutionState
		if args[1] != nil {
			arg1 = args[1].(*engine.ExecutionState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLifecycleOps_EnsureConnected_Call) Return(err error) *MockLifecycleOps_EnsureConnected_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLifecycleOps_EnsureConnected_Call) RunAndReturn(run func(ctx context.Context, state *engine.ExecutionState) error) *MockLifecycleOps_EnsureConnected_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureDisconnected provides a mock function for the type MockLifecycleOps
func (_mock *MockLifecycleOps) EnsureDisconnected() {
	_mock.Called()
	return
}

// MockLifecycleOps_EnsureDisconnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureDisconnected'
type MockLifecycleOps_EnsureDisconnected_Call struct {
	*mock.Call
}

// EnsureDisconnected is a helper method to define mock.On call
func (_e *MockLifecycleOps_Expecter) EnsureDisconnected() *MockLifecycleOps_EnsureDisconnected_Call {
	return &MockLifecycleOps_EnsureDisconnected_Call{Call: _e.mock.On("EnsureDisconnected")}
}

func (_c *MockLifecycleOps_EnsureDisconnected_Call) Run(run func()) *MockLifecycleOps_EnsureDisconnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLifecycleOps_EnsureDisconnected_Call) Return() *MockLifecycleOps_EnsureDisconnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLifecycleOps_EnsureDisconnected_Call) RunAndReturn(run func()) *MockLifecycleOps_EnsureDisconnected_Call {
	_c.Run(run)
	return _c
}

// ReconnectToZone provides a mock function for the type MockLifecycleOps
func (_mock *MockLifecycleOps) ReconnectToZone(state *engine.ExecutionState) error {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for ReconnectToZone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*engine.ExecutionState) error); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLifecycleOps_ReconnectToZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconnectToZone'
type MockLifecycleOps_ReconnectToZone_Call struct {
	*mock.Call
}

// ReconnectToZone is a helper method to define mock.On call
//   - state *engine.ExecutionState
func (_e *MockLifecycleOps_Expecter) ReconnectToZone(state interface{}) *MockLifecycleOps_ReconnectToZone_Call {
	return &MockLifecycleOps_ReconnectToZone_Call{Call: _e.mock.On("ReconnectToZone", state)}
}

func (_c *MockLifecycleOps_ReconnectToZone_Call) Run(run func(state *engine.ExecutionState)) *MockLifecycleOps_ReconnectToZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *engine.ExecutionState
		if args[0] != nil {
			arg0 = args[0].(*engine.ExecutionState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLifecycleOps_ReconnectToZone_Call) Return(err error) *MockLifecycleOps_ReconnectToZone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLifecycleOps_ReconnectToZone_Call) RunAndReturn(run func(state *engine.ExecutionState) error) *MockLifecycleOps_ReconnectToZone_Call {
	_c.Call.Return(run)
	return _c
}
