// Code generated by mash-featgen. DO NOT EDIT.

package model

// FeatureType identifies the type of a feature.
type FeatureType uint8

const (
	// FeatureDeviceInfo: device identity and structure.
	FeatureDeviceInfo FeatureType = 0x01
	// FeatureStatus: operating state and fault information.
	FeatureStatus FeatureType = 0x02
	// FeatureElectrical: static electrical configuration.
	FeatureElectrical FeatureType = 0x03
	// FeatureMeasurement: power, energy, voltage, current telemetry.
	FeatureMeasurement FeatureType = 0x04
	// FeatureEnergyControl: limits, setpoints, and control commands.
	FeatureEnergyControl FeatureType = 0x05
	// FeatureChargingSession: eV charging session data.
	FeatureChargingSession FeatureType = 0x06
	// FeatureTariff: price structure and power tiers.
	FeatureTariff FeatureType = 0x07
	// FeatureSignals: time-slotted prices, limits, and forecasts.
	FeatureSignals FeatureType = 0x08
	// FeaturePlan: device intended behavior/schedule.
	FeaturePlan FeatureType = 0x09
	// FeatureTestControl: test control and event triggering.
	FeatureTestControl FeatureType = 0x0A
)

// String returns the feature type name.
func (f FeatureType) String() string {
	switch f {
	case FeatureDeviceInfo:
		return "DeviceInfo"
	case FeatureStatus:
		return "Status"
	case FeatureElectrical:
		return "Electrical"
	case FeatureMeasurement:
		return "Measurement"
	case FeatureEnergyControl:
		return "EnergyControl"
	case FeatureChargingSession:
		return "ChargingSession"
	case FeatureTariff:
		return "Tariff"
	case FeatureSignals:
		return "Signals"
	case FeaturePlan:
		return "Plan"
	case FeatureTestControl:
		return "TestControl"
	default:
		if f >= FeatureVendorBase {
			return "Vendor"
		}
		return "Unknown"
	}
}
