// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/mash-protocol/mash-go/internal/testharness/runner"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSuiteSession creates a new instance of MockSuiteSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSuiteSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSuiteSession {
	mock := &MockSuiteSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSuiteSession is an autogenerated mock type for the SuiteSession type
type MockSuiteSession struct {
	mock.Mock
}

type MockSuiteSession_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSuiteSession) EXPECT() *MockSuiteSession_Expecter {
	return &MockSuiteSession_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockSuiteSession
func (_mock *MockSuiteSession) Clear() {
	_mock.Called()
	return
}

// MockSuiteSession_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockSuiteSession_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockSuiteSession_Expecter) Clear() *MockSuiteSession_Clear_Call {
	return &MockSuiteSession_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockSuiteSession_Clear_Call) Run(run func()) *MockSuiteSession_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSuiteSession_Clear_Call) Return() *MockSuiteSession_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSuiteSession_Clear_Call) RunAndReturn(run func()) *MockSuiteSession_Clear_Call {
	_c.Run(run)
	return _c
}

// ConnKey provides a mock function for the type MockSuiteSession
func (_mock *MockSuiteSession) ConnKey() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConnKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSuiteSession_ConnKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnKey'
type MockSuiteSession_ConnKey_Call struct {
	*mock.Call
}

// ConnKey is a helper method to define mock.On call
func (_e *MockSuiteSession_Expecter) ConnKey() *MockSuiteSession_ConnKey_Call {
	return &MockSuiteSession_ConnKey_Call{Call: _e.mock.On("ConnKey")}
}

func (_c *MockSuiteSession_ConnKey_Call) Run(run func()) *MockSuiteSession_ConnKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSuiteSession_ConnKey_Call) Return(s string) *MockSuiteSession_ConnKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSuiteSession_ConnKey_Call) RunAndReturn(run func() string) *MockSuiteSession_ConnKey_Call {
	_c.Call.Return(run)
	return _c
}

// Crypto provides a mock function for the type MockSuiteSession
func (_mock *MockSuiteSession) Crypto() runner.CryptoState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Crypto")
	}

	var r0 runner.CryptoState
	if returnFunc, ok := ret.Get(0).(func() runner.CryptoState); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(runner.CryptoState)
	}
	return r0
}

// MockSuiteSession_Crypto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Crypto'
type MockSuiteSession_Crypto_Call struct {
	*mock.Call
}

// Crypto is a helper method to define mock.On call
func (_e *MockSuiteSession_Expecter) Crypto() *MockSuiteSession_Crypto_Call {
	return &MockSuiteSession_Crypto_Call{Call: _e.mock.On("Crypto")}
}

func (_c *MockSuiteSession_Crypto_Call) Run(run func()) *MockSuiteSession_Crypto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSuiteSession_Crypto_Call) Return(cryptoState runner.CryptoState) *MockSuiteSession_Crypto_Call {
	_c.Call.Return(cryptoState)
	return _c
}

func (_c *MockSuiteSession_Crypto_Call) RunAndReturn(run func() runner.CryptoState) *MockSuiteSession_Crypto_Call {
	_c.Call.Return(run)
	return _c
}

// IsCommissioned provides a mock function for the type MockSuiteSession
func (_mock *MockSuiteSession) IsCommissioned() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsCommissioned")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSuiteSession_IsCommissioned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCommissioned'
type MockSuiteSession_IsCommissioned_Call struct {
	*mock.Call
}

// IsCommissioned is a helper method to define mock.On call
func (_e *MockSuiteSession_Expecter) IsCommissioned() *MockSuiteSession_IsCommissioned_Call {
	return &MockSuiteSession_IsCommissioned_Call{Call: _e.mock.On("IsCommissioned")}
}

func (_c *MockSuiteSession_IsCommissioned_Call) Run(run func()) *MockSuiteSession_IsCommissioned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSuiteSession_IsCommissioned_Call) Return(b bool) *MockSuiteSession_IsCommissioned_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSuiteSession_IsCommissioned_Call) RunAndReturn(run func() bool) *MockSuiteSession_IsCommissioned_Call {
	_c.Call.Return(run)
	return _c
}

// Record provides a mock function for the type MockSuiteSession
func (_mock *MockSuiteSession) Record(zoneID string, crypto runner.CryptoState) {
	_mock.Called(zoneID, crypto)
	return
}

// MockSuiteSession_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockSuiteSession_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - zoneID string
//   - crypto runner.CryptoState
func (_e *MockSuiteSession_Expecter) Record(zoneID interface{}, crypto interface{}) *MockSuiteSession_Record_Call {
	return &MockSuiteSession_Record_Call{Call: _e.mock.On("Record", zoneID, crypto)}
}

func (_c *MockSuiteSession_Record_Call) Run(run func(zoneID string, crypto runner.CryptoState)) *MockSuiteSession_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 runner.CryptoState
		if args[1] != nil {
			arg1 = args[1].(runner.CryptoState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSuiteSession_Record_Call) Return() *MockSuiteSession_Record_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSuiteSession_Record_Call) RunAndReturn(run func(zoneID string, crypto runner.CryptoState)) *MockSuiteSession_Record_Call {
	_c.Run(run)
	return _c
}

// ZoneID provides a mock function for the type MockSuiteSession
func (_mock *MockSuiteSession) ZoneID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ZoneID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSuiteSession_ZoneID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZoneID'
type MockSuiteSession_ZoneID_Call struct {
	*mock.Call
}

// ZoneID is a helper method to define mock.On call
func (_e *MockSuiteSession_Expecter) ZoneID() *MockSuiteSession_ZoneID_Call {
	return &MockSuiteSession_ZoneID_Call{Call: _e.mock.On("ZoneID")}
}

func (_c *MockSuiteSession_ZoneID_Call) Run(run func()) *MockSuiteSession_ZoneID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSuiteSession_ZoneID_Call) Return(s string) *MockSuiteSession_ZoneID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSuiteSession_ZoneID_Call) RunAndReturn(run func() string) *MockSuiteSession_ZoneID_Call {
	_c.Call.Return(run)
	return _c
}
